### ISSUE TITLE
Being able to cascade remove without populate

### ISSUE THREAD

**Issue by standup75** [mikro-orm/mikro-orm#1011]
**Is your feature request related to a problem? Please describe.**
I just spent a couple of hours trying to figure out why deleting my entity didn't delete its connected 1:m entity, and after stepping into the code, I realize I needed to populate the relationship first

**Describe the solution you'd like**
If this was clear in the Cascading part of the doc, I think it would have saved me some time

**Describe alternatives you've considered**
Would it be a problem if the framework was populating the relationship to make sure it cascades correctly?

**Additional context**
Could also return a more explicit error message

**Comment by B4nan** [comment]
Can you show me some code that was problematic? What driver are you talking about? 

Its weird, I remember stating this somewhere in the docs... 

> Would it be a problem if the framework was populating the relationship to make sure it cascades correctly?

Not really, loading is async, but cascading happens via sync method. And it does sound like a bad idea to me (from performance standpoint).

**Comment by standup75** [comment]
I was implementing a bulk remove of an entity Subscriber for my api:
This, didn't work:
```
const subscribers = await orm.em.find(
  Subscriber,
  { id: { $in: subscriberIds } }
);
await orm.em.removeAndFlush(subscribers);
```
It would fail to destroy a 1:m relationship between the subcribers to remove and another entity called Message with the following error:
```
previous error: delete from "subscriber" where "id" in (4) - update or delete on table "subscriber" violates foreign key constraint "message_recepient_id_foreign" on table "message"
```

My workaround, populating the messages:
```
  const subscribers = await orm.em.find(
    Subscriber,
    { id: { $in: subscriberIds } },
    ['messages']
  );
  await orm.em.removeAndFlush(subscribers);
```

**Comment by B4nan** [comment]
There are two things - one is app level cascading, for that it should be quite obvious that things need to be populated, as otherwise there is nothing to cascade on. Will add a hint to the docs, it should be there for sure.

Then there is db level cascading - also known as referential integrity. It is defined on the other end of the relation and that works automatically without populating. So here instead of marking a collection to cascade delete (which means "when the owner is removed, we cascade delete on the collection items), you can mark the m:1 counterpart as `onDelete: 'cascade' (which means "if the referenced row gets deleted, I will wipe myself too"). 

Usually its better to go with the second approach, app level cascading it meant mainly for mongo where no FKs exist.

**Comment by dakotacookenmaster** [comment]
@B4nan Would you mind updating the docs, at some point, to indicate specifically for cascade deletion via `Cascade.ALL` or `Cascade.REMOVE` that the collection has to be populated? I realize it's likely supposed to be intuitive, since you're dealing with the ORM, but I know that I just ran into an issue in a production app where I had assumed that adding `Cascade.ALL` on the `@OneToMany()` side would propagate down to its children, and I got a referential integrity error and my clients were seeing 500 errors. It definitely makes sense to me now, but the only comment in the docs is for cascade persistence:

```
When cascade persisting collections, keep in mind only fully initialized collections will be cascade persisted.
```

I appreciate your help, and I love using Mikro-ORM.

**Comment by B4nan** [comment]
But it is mentioned there, at the very beginning of the docs:

<img width="1011" height="389" alt="Image" src="https://github.com/user-attachments/assets/cbd070a9-6b34-43c3-8e74-2814163541d9" />

**Comment by dakotacookenmaster** [comment]
> But it is mentioned there, at the very beginning of the docs:
> 
> <img alt="Image" width="1011" height="389" src="https://private-user-images.githubusercontent.com/615580/534373079-cbd070a9-6b34-43c3-8e74-2814163541d9.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjgxNTAxMjEsIm5iZiI6MTc2ODE0OTgyMSwicGF0aCI6Ii82MTU1ODAvNTM0MzczMDc5LWNiZDA3MGE5LTZiMzQtNDNjMy04ZTc0LTI4MTQxNjM1NDFkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDExMVQxNjQzNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MDMzOTZmNTNmNGUwNzM1Zjk1OTA2MjhkZjJjZGI5ZWJkNmI2OTY0NzMxMzE1N2ViZWE5ZjQzYzMwZmU0YmFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.G0r-JEZ93TGI8koggjAKs7S2AjPA5i91FYuO3XRyvQk">

Oh wow, I don’t know how I missed it! I guess there’s just a specific one for persistence that’s not there for delete as well.
