### ISSUE TITLE
orphanRemoval flag does not work

### ISSUE THREAD

**Issue by st-devlop** [mikro-orm/mikro-orm#1018]
**Describe the bug**
orphanRemoval flag does not work when we use Collection.set() and orm.em.transactional together.

**To Reproduce**
We have created a test code to reproduce it. Test case 1 passes, but test case 2 fails.
https://github.com/st-devlop/mikro-orm/commit/0e39d26e4886d92f2e75d27ba103d26fe40b4bdc

**Expected behavior**
Collection.set() orphan remove original items.

**Versions**

| Dependency | Version |
| - | - |
| node | 12.18.2 |
| typescript | 3.9.7 |
| mikro-orm | 4.2.1 |
| your-driver | mikro-orm/mysql: 4.2.1 |

**Comment by B4nan** [comment]
You can't just move the flush call inside `em.transactional`, the whole code should be inside the callback and you should not work with anything that was created from the outer scope (like with the `author` entity). Inside the callback new context is created, and you need to do things there, not in the outer scope.

This works fine in master:

```ts
await orm.em.transactional(async em => {
  author.books.set([book2]); // this is where the orphan removal is triggered
  em.persist(author); // no need to flush, as that happens automatically here
});
```

And I am quite sure it works due to recent improvements from #959. So with latest stable, you might need to do this (which is definitely more correct approach):

```ts
await orm.em.transactional(async em => {
  const _author = await em.findOneOrFail(Author, author.id); // load author into the inner scope
  const book2 = new Book(_author);
  _author.books.set([book2]);
  em.persist(_author);
});
```

Also this is wrong (or rather a no-op, as the entity type has precedence):

```ts
@ManyToOne(() => Author, { type: BigIntType }) // type is Author, not BigIntType (that is type of its PK, not of this property)
author: Author;
```
