### ISSUE TITLE
STI entity as relation mapped to parent entity class instead of child entity class

### ISSUE THREAD

**Issue by alisd23** [mikro-orm/mikro-orm#1050]
**Describe the bug**
When defining an STI parent entity as part of a relationship (for example when the relation could be any of the sub classes), the relation is not mapped to the correct subclass when populated. Instead the values of the child entity are populated correctly, but the constructor is incorrect.

I only noticed this because in some of my code I do `if (entity instanceof ChildEntity) {}` checks, though I could get rid of these for now.

**To Reproduce**
1. Reproduction here: https://github.com/alisd23/mikro-orm-nestjs-starter/tree/issue/child-sti-entity-relationship-incorrect-class
2. Run `yarn test`
3. Check the `Should map child entity to correct class `spec`

**Expected behavior**
In the following case (taken from the repro above), the driver's `vehicle` relation property should an instance of the `Car`class, not the `Vehicle` class.

```ts
@Entity({
  discriminatorColumn: 'type',
  abstract: true,
})
export abstract class Vehicle {
  @PrimaryKey()
  id!: number;

  @Enum()
  type!: 'car' | 'bicycle';

  @OneToMany(
    () => Driver,
    driver => driver.vehicle,
  )
  drivers = new Collection<Driver>(this);
}

@Entity({ discriminatorValue: 'car' })
export class Car extends Vehicle {
  constructor(engine: string) {
    super();
    this.type = 'car';
    this.engine = engine;
  }

  @Property()
  public engine: string;
}

@Entity({ discriminatorValue: 'bicycle' })
export class Bicycle extends Vehicle {
  constructor(noOfGears: number) {
    super();
    this.type = 'bicycle';
    this.noOfGears = noOfGears;
  }

  @Property()
  public noOfGears: number;
}

@Entity()
export class Driver {
  constructor(name: string, person: Vehicle) {
    this.name = name;
    this.vehicle = person;
  }

  @PrimaryKey()
  id: number;

  @Property()
  name: string;

  @ManyToOne(() => Vehicle)
  vehicle: Vehicle;
}

// Test

const car = new Car('V8');
const driver = new Driver('Bob', car);
await em.fork().persistAndFlush([car, driver]);

const driverWithVehicle = await em.findOne(Driver, driver.id, [
  'vehicle',
]);

expect(driverWithVehicle.vehicle.type).toBe('car'); // PASS - correct type
expect((driverWithVehicle.vehicle as Car).engine).toBe('V8'); // PASS - has car-specific properties
expect(driverWithVehicle.vehicle).toBeInstanceOf(Car); // FAIL - wrong class, is an instance of 'Vehicle' instead of 'Car'

```

I believe this is a bug because it mostly works, and fetching a child entity using the parent class (e.g. `em.findOne(Vehicle, car.id)` does return the correct instance type). Let me know if I'm wrong.

**Versions**

| Dependency | Version |
| - | - |
| node | 12 |
| typescript | 4.0.3 |
| mikro-orm | 4.2.4-dev.103 |
| your-driver | MySQL |

**Comment by B4nan** [comment]
This is a limitation of STI with the select-in loading strategy. Once entity is in the identity map, we cannot change its type (as that would change its key in the identity map as well as break the invariant of having single instance of the entity). And with the default select-in strategy, we first load the parent, and create a reference from the m:1 relation. At that point, we do not know its type, because we have just the PK, but we need to have the entity instance already.

What you can do is to use `joined` strategy, where we have all the data from single query and therefore we can tell the right type:

```ts
const driverWithVehicle = await em.findOne(Driver, driver.id, {
  populate: ['vehicle'],
  strategy: LoadStrategy.JOINED,
});
```

Btw few notes for future reproductions: 
- prefer single file reproductions that can be copy pasted to the ORM repository
- drop unnecessary things, e.g. this is not about nestjs adapter, also no need for migrations, no need for CLI config
- prefer sqlite in memory database, so there is no need to create the db, and it is extremely fast to drop and create between tests
- do not require any configuration - this is the biggest pain point for me, I am not interested in setting up some `env` file :] reproductions should be simple, this is unnecessary level of abstraction. 
- the fact that it was not a master branch also added a bit of a headache (bad dependencies installed initially)
	
While the reproduction is fine, it took me ~30 min to get it to the right shape to actually start debugging, if it were a single file in memory sqlite thing, it would be more like 30 seconds :] Best thing about that is, that I knew what is happening right ahead, before even looking at your repo, but spent 30 min just to verify it :D

**Comment by alisd23** [comment]
Ok perfect, thanks for this 👍 

And yeah on the reproduction, I initially meant that repository for a NestJS issue and never changed it back. I'll make it simpler next time, and only include MySQL if the bug relates to it (which could sometimes be the case)
