### ISSUE TITLE
Cross-database joins and cross-schema joins

### ISSUE THREAD

**Issue by lewispham** [mikro-orm/mikro-orm#106]
I'm pretty new to mikro-orm and I don't really know whether or not mikro orm supports cross-database joins and cross-schema joins. In typeorm, you can do something like this
```
course_repo.createQueryBuilder('course')
  .select('course.name')
  .addSelect('student.name')
  .innerJoin("someDatabase.student", 'student', 'student.id = course.student_id')
  .getRawMany()
```

**Comment by B4nan** [comment]
Hey there, this is currently not supported, but I am open for PRs. 

Btw looking at typeorm docs (https://github.com/typeorm/typeorm/blob/master/docs/multiple-connections.md), do you know how the semantics of this feature works? I guess one could do cross schema queries natively in some databases (that should be easy to support)? Or is it just 1 connection ~ 1 database/schema? What happens in the background, how do actual SQL queries look like? 

Because it looks like they do support this also on multiple connections level (and even different drivers should be supported), which could work only by mimicking the join via multiple actual queries (one for each connection). On the other hand I can imagine having db credentials that allow working with multiple databases, so one connection would be enough and only required change would be adjusting the query builder. 

Btw I am currently working on #77 which might be somehow relevant (it will be good first step to support multiple write connections).

**Comment by lewispham** [comment]
@B4nan I think I'm not qualified enough to answer your questions. But still anyway, it actually depends on the database. I think one single connection with proper permissions across databases should be enough. Here are some related Stackoverflow articles.

MySQL: https://stackoverflow.com/questions/1972943/how-do-i-construct-a-cross-database-query-in-mysql
POSTGRES: https://stackoverflow.com/questions/46324/possible-to-perform-cross-database-queries-with-postgresql

I plan to use mikro-orm for my current project but unfortunately this issue is killing the idea since we need to create foreign keys and joins tables across databases (or schemas).

**Comment by B4nan** [comment]
Ok good, as I said, I believe supporting this on single connection level should be pretty easy. I will be happy to look into this after I am done with #80. 

Btw I am not really sure if you can achieve proper foreign keys with referential integrity (e.g. on delete cascades) with this approach. Although MikroORM implements cascading on application level, so if you have your entities fetched, it will properly cascade regardless of what database you are using (aka it works for mongo as well).

**Comment by B4nan** [comment]
Actually looks like this is already supported, just add your database/schema name to the entity name in collection decorator:

```typescript
@Entity({ collection: 'my_db_1.foo_bar' })
export class FooBar { ... }

@Entity({ collection: 'my_db_2.foo_baz' })
export class FooBaz { ... }
```

**Comment by B4nan** [comment]
@lewispham does it work for you? I already updated docs in dev branch

**Comment by B4nan** [comment]
Closing this as resolved, feel free to reopen if it does not work for you.
