### ISSUE TITLE
Bug searching in embedded object mode with postgresql

### ISSUE THREAD

**Issue by francisco-sanchez-molina** [mikro-orm/mikro-orm#1091]
https://github.com/mikro-orm/mikro-orm/blob/584854cca4b0a0bf96902524f8c6d171317e7d98/packages/core/src/metadata/MetadataDiscovery.ts#L570

search over embedded field build this query:

```
select count(distinct("e0"."id")) as "count" from "document_recurrent" as "e0" left join "document_template" as "e1" on "e0"."document_template_id" = "e1"."id" where "e1"."totals->total" = '200' and "e0"."owner_id" = '56effe74-6445-4f99-9210-2a0ce9a15846' and "e0"."deleted_at" is null
```

but postgresql requires this change: 

```
"e1"."totals"->'total'
```

I am investigating, but I am not able to find the solution

**Comment by B4nan** [comment]
Weird, I see an error there for postgres, as by default it is using `jsonb` columns that require to use `->>` operator instead of `->`, but it does not quote as in your example.

Added a fix that should handle quoting as well: 

https://github.com/mikro-orm/mikro-orm/commit/78c93738ba875eb7195460fe6503da784db038a1#diff-65e7a69add97dde401a8f2acee56c0ed2709f35ecf7a85c380295461770610ccR212

You can try the dev version `4.3.1-dev.18`.
