### ISSUE TITLE
One to one, left join with no cascade.

### ISSUE THREAD

**Issue by sptGabriel** [mikro-orm/mikro-orm#1107]
Employee Entity:

```
@Entity({ tableName: 'employees' })
@Unique({ properties: ['position', 'departament'] })
export class Employee {
  @PrimaryKey()
  public readonly id: string;
  @Property()
  public matricula: string;
  @Property()
  public first_name: string;
  @Property()
  public last_name: string;
  @Enum()
  public position: Positions;
  @ManyToOne({ entity: () => Departament, name: 'departament_id' })
  public departament: Departament;
  @OneToOne({
    entity: () => User,
    mappedBy: 'employee',
    cascade:[]
  })
  public user:User;
  @Property()
  public createdAt = new Date();
  @Property({ onUpdate: () => new Date() })
  public updatedAt = new Date();
  @Property()
  public deletedAt?: Date;
  constructor(container: EmployeeContainer) {
    this.id = container.id ? container.id : v4();
    this.matricula = container.matricula;
    this.first_name = container.first_name;
    this.last_name = container.last_name;
    this.departament = container.departament;
    this.position = container.position;
  }
}
```

User Entity:

```
@Entity({tableName: 'users'})
export class User {
  @OneToOne(() => Employee, employee => employee.user, {
    owner: true,
    primary:true,
    cascade: [],
    fieldName: 'id',
  })
  public readonly employee: Employee;
  @Property()
  public login:string;
  @Property()
  public password:string;
  @Property({default:false})
  public active:boolean;
  constructor(){

  }
}
```
For some reason when using a select in the table employee, even with the cascade null in both entities it is giving a select left join with users:

`const employee = await this.em.findOne(Employee, { matricula:matricula });`

query with error:

```
[query] select "e0".*, "e1"."id" as "user_id" from "employees" as "e0" left join "users" as "e1" on "e0"."id" = "e1"."id" where "e0"."matricula" = 'a' limit 1 [took 3 
ms]
DriverException: select "e0".*, "e1"."id" as "user_id" from "employees" as "e0" left join "users" as "e1" on "e0"."id" = "e1"."id" where "e0"."matricula" = 'a' limit 1 - operator does not exist: uuid = integer
```

I wanted to use cascade in delete and update, but how could I solve this problem?

I try to search for an employee with the registration field and give a left join to the user, this seems strange.

**Comment by B4nan** [comment]
> For some reason when using a select in the table employee, even with the cascade null in both entities it is giving a select left join with users:

Cascading has literally nothing to do with joining. In 99% cases you should not disable cascading as you are doing, as I am almost certain you don't really know what that does :] You are disabling cascade persisting, which is hardly what you want.

That join also have nothing to do with your error. The join is there because you are selecting inverse side of 1:1 relation, and you can optionally disable this behaviour via `autoJoinOneToOneOwner: false`. Search the issues for this configuration for more information before you actually disable it, as this has really nothing to do with the error. 

> I wanted to use cascade in delete and update, but how could I solve this problem?

There is no "cascade update", only cascade persist and that is only for new entities (those that will issue insert query). You don't need "cascade update", it happens automatically, all managed entities (those loaded via entity manager) will be checked for changes.

https://mikro-orm.io/docs/cascading/

> operator does not exist: uuid = integer

Have you even tried to google your error? Because the error comes from postgres, not from MikroORM. Your column is of type UUID, and, as the error clearly says, you can't compare UUID type with numbers. This most probably means your schema is wrong or out of sync, and one of your tables have the PK defined as UUID while the other uses a number.
