### ISSUE TITLE
How to insert with a database auto generated primary key?

### ISSUE THREAD

**Issue by chaoyangnz** [mikro-orm/mikro-orm#119]
Cannot find any documentation

**Comment by B4nan** [comment]
Not sure what do you mean? Like UUID generated from database instead of your code? Or auto increment id (serial in postgres)?

Auto increment is normally supported, just define the column with `@PrimaryKey` decorator. Then persist your entity (and flush) and the property will be updated with the AI value.

For UUID you should generate it in your entity manually instead: https://github.com/mikro-orm/mikro-orm/blob/master/tests/entities-sql/Book2.ts#L12

In postgre columns with default database value (`default` option in `@Property` decorator) should also automatically update the value after flushing as it should be returned via `returning` clause in insert/update queries.

**Comment by chaoyangnz** [comment]
I addressed it. I generate a sequence and then assign to the id manually.

**Comment by DenKorn** [comment]
@chaoyangnz Could you please share your workaround for it? 

The best thing I came to was to use manual DBAL query fetching new sequence value before each entity **.persist()** call. But that's terrible. I really loved how that could be done in Doctrine via primary key strategy.

**Comment by fvclaus** [comment]
This issue comes up on top on google. So here is how I "solved" the issue.

I have the following sql for my postgres instance:
```
create sequence countries_id_seq start 100000;
create table countries(id integer not null default nextval('countries_id_seq'), name varchar(255) not null);
```
When I persist an new country the following query is generated:
```
[query] insert into "countries" ("name") values ('foo') returning "id" [took 3 ms]
```
The id is returned and set as primary key. It did not work for me at first, because i forgot to `await` the flush operation. I then debugged the source code. Here are the relevant parts:
- [PostgreSQLConnection.transformRawResult](https://github.com/mikro-orm/mikro-orm/blob/f5f413503cdff35110c83277884096ae37e331cb/packages/postgresql/src/PostgreSqlConnection.ts#L39) will retrieve the new id from the result
- [ChangeSetPersister.persistNewEntity](https://github.com/mikro-orm/mikro-orm/blob/f5f413503cdff35110c83277884096ae37e331cb/packages/core/src/unit-of-work/ChangeSetPersister.ts#L71) will set the new id
