### ISSUE TITLE
Disable Identity Map mechanism

### ISSUE THREAD

**Issue by DanTsk** [mikro-orm/mikro-orm#1216]
Hello. We really enjoyed using `mikro-orm` in our projects. Currently, we are working on a high-load system, so data throughput and performance are critical for us. Is there any option to disable Identity Map mechanism and use `mikro-orm` as advanced query-builder/data-mapper?

**Comment by B4nan** [comment]
I don't think there is easy way to not use identity map. You could clear the state manually, but for population and change set tracking to work, identity map is needed. For read only purposes, we could have an option to disable identity map look ups, but that would not help much with performance I guess.

Can you elaborate how do you expect that to work and what are the actual issues/constraints? Because identity map is capable of high loads, check the 10k entities benchmark: 

https://github.com/mikro-orm/benchmark

**Comment by B4nan** [comment]
Closing in favour of #1267.

**Comment by jtomaszewski** [comment]
I'd like to disable identity map globally, not just for a single query. Would you be open for such a PR @B4nan ?

**Comment by B4nan** [comment]
we already have a global config for that. i would still very much discourage doing that. i don't see any point in using this ORM if you don't want the persistence from it, its the main selling point, but you do you :]

**Comment by jtomaszewski** [comment]
Type safety, migrations mechanism, easy query building - there's still a few very good reasons to use this library ;) And we're very happy we went with it.

I just don't like the idea of mutations happening magically in the background - I'm afraid it might cause some unwanted queries here and there, if we don't force them to explicitly write "insert/update/delete this, please".

Plus, the infinite identity map causes a lot of memory & CPU troubles in our background workers, that iterate over whole datasets. That's why we consider disabling the identity map globally, at least in there.

Thanks a lot for the quick reply - I'll try the global config option then :)

**Comment by B4nan** [comment]
> Plus, the infinite identity map causes a lot of memory & CPU troubles in our background workers, that iterate over whole datasets

you should have a fork per handler there, not a global identity map.

**Comment by jtomaszewski** [comment]
> you should have a fork per handler there, not a global identity map.

We do have a fork for each job execution, but a single job can last very long, because it iterates over millions of records. This over time causes our workers to go out-of-memory.

So now we have to either:

1. disable identity map globally,
2. disable identity map in some specific queries, depending on whether they are used in a long-running code,
3. fork the entity manager in some parts of the application code, depending whether a given part is used in a long-running code.

As it's easy to make a mistake in this "should the identity map be disabled/forked here?" guessing, and I don't like polluting the app code with such details, for now I'm leaning towards disabling identity map globally. (And just enabling it where it's needed for the persistence.)

(Another thing is that I'd prefer devs to explicitly say "insert/update/delete this, please", rather than rely on some magic in happening the background, but let's say that's a matter of taste and not relevant to this problem.)
