### ISSUE TITLE
Simple example project in v3

### ISSUE THREAD

**Issue by lookfirst** [mikro-orm/mikro-orm#131]
[relations-mikro.zip](https://github.com/mikro-orm/mikro-orm/files/3631375/relations-mikro.zip)

Maybe others can benefit from this simple example that I put together. It uses the upcoming 3.x.

**Comment by B4nan** [comment]
Thanks, will keep this open until I update all example repositories. I am also thinking about splitting them instead of having single examples repo.

**Comment by vimmerru** [comment]
> id!: string;

Why you use ! if you assign field in constructor explicitly? In general it would be nice to see things how to handle complex relations, enums, optional fields and etc... Current documentation unfortunately doesn't provide enough clarity.

**Comment by lookfirst** [comment]
@vimmerru You're right, that can be removed. It was left over while I was figuring this out.

**Comment by lookfirst** [comment]
I agree, building this into a more complex example is a nice dream. That said, after testing other orm tools, they couldn't even pass this simple test. =( Of course it could have been me doing something wrong, but something so simple, shouldn't be so hard!

https://github.com/RobinBuschmann/sequelize-typescript/issues/680

**Comment by B4nan** [comment]
> > id!: string;
> 
> Why you use ! if you assign field in constructor explicitly? In general it would be nice to see things how to handle complex relations, enums, optional fields and etc... Current documentation unfortunately doesn't provide enough clarity.

Have you looked in ORM’s tests and entity definitions? Pretty much everything that is supported should be covered there, if you are looking for more complex things. EntityManager tests cover vast majority of features as integration tests, so that could be helpful. I will be happy to add more complex examples to the examples repository, just let me know what exactly would you expect there (same applies to docs). 

Btw the main purpose with example repos was to show how to integrate the ORM with existing frameworks, not really to showcase its features - that is why they are so simple. 

Obviously some things might not yet be properly supported (just like those optional props with undefined, but that’s already fixed now). 

Generally I seek for concrete suggestions, then we can move things forward :)

**Comment by lookfirst** [comment]
For others that find this, I've been working on something here: https://github.com/lookfirst/mikro-example

It is basically what probably already exists in unit tests here, but I'm using it to make sure that my model is correct as I'm developing it.

**Comment by B4nan** [comment]
Another more complex example added - rewrite of realworld example app in nestjs from TypeORM to MikroORM v3:

https://github.com/mikro-orm/nestjs-realworld-example-app

**Comment by B4nan** [comment]
Example projects updated to v3, closing this now.
