### ISSUE TITLE
setFilterParams does not set arguments for Repositories

### ISSUE THREAD

**Issue by visurel** [mikro-orm/mikro-orm#1312]
**Describe the bug**
I have defined a filter on an Entity:
```typescript
@Filter<Author>({
  name: 'minAge',
  cond: args => ({
    age: {
      $gte: args.age
    }
  }),
  default: true
})
```
And wanted to globally set a value for the "Filter Arguments" like this:
```typescript
this.em.setFilterParams('minAge', {
  age: 10
});
```
After doing this and you query using: 
```typescript
this.em.findOne(Author, { id: 123 });
```
The filter gets applied correctly.

**But:**
If you try to query using the AuthorRepository:
```typescript
this.em.getRepository(Author).findOne({ id: 123 });
```
The EntityManager throws an error `Error: No arguments provided for filter 'minAge'`

**Stack trace**
```typescript
Error: No arguments provided for filter 'minAge'
at SqlEntityManager.applyFilters (\nestjs-example-app\node_modules\@mikro-orm\core\EntityManager.js:145:27)
at SqlEntityManager.find (\nestjs-example-app\node_modules\@mikro-orm\core\EntityManager.js:80:28)
at SqlEntityRepository.findAll (\nestjs-example-app\node_modules\@mikro-orm\core\entity\EntityRepository.js:63:24)
at AuthorController.<anonymous> (\nestjs-example-app\src\modules\author\author.controller.ts:17:40)
at Generator.next (<anonymous>)
at \nestjs-example-app\src\modules\author\author.controller.ts:20:71
at new Promise (<anonymous>)
at __awaiter (\nestjs-example-app\src\modules\author\author.controller.ts:16:12)
at AuthorController.find (\nestjs-example-app\src\modules\author\author.controller.ts:35:16)
at \nestjs-example-app\node_modules\@nestjs\core\router\router-execution-context.js:38:29
```

**To Reproduce**
Reproduction Repository: https://github.com/visurel/mikro-orm-filter-issue/commit/992f5070573e2f4537b5a3170a0944869691d163
1. Install as described in README
2. Do GET to /author and see the error

**Expected behavior**
I would expect to be able to query through Repositories and directly from the EntityManager using global "Filter Arguments" and not have to pass the Filter Arguments to the method every time.

**Additional context**

**Versions**

Current MikroORM CLI configuration
 - dependencies:
   - mikro-orm 4.3.4
   - node 14.7.0
   - knex 0.21.12
   - typescript 4.1.3

**Comment by B4nan** [comment]
Should be fixed in `4.3.5-dev.82`, will be available in few minutes.

**Comment by visurel** [comment]
Thanks a lot for the quick fix 💪

**Comment by webbster-dev** [comment]
Sorry to re-open this issue, but I'm seeing this behaviour as well in a NestJS application.

I've got some auth middleware which sets filter params:
```typescript
this.em.setFilterParams('tenant', { tenant: user.tenant.id });
```

In the Entity, I've got the same relation registered:
```typescript
@Filter<User>({
  name: 'tenant',
  cond: (args) => {
    if (!args.tenant) {
      return {};
    }

    return { tenant: args.tenant };
  },
  default: true,
})
```

I've got an abstract `ResourceService` which handles all the CRUD stuff, and I'd like to keep everything as abstract as possible. So that just receives a bunch or query params whether to filter/order.
```typescript
let query: FindOptions<T> = {
        populate: this.getIncludes(metaQuery?._includes) as never[],
        orderBy: this.getOrders(metaQuery._orders),
        limit: metaQuery?._per_page,
        strategy: LoadStrategy.SELECT_IN,
      };

const [data, total] = await this.repository.findAndCount(
        this.getFilters(metaQuery?._filters) as FilterQuery<T>,
        query,
      );
```

And here I get the error:
```
Error: No arguments provided for filter 'tenant'
```

I've tried a lot of things, scoping the Services on Request, shuffling middlewares, but it does not seem to help. One thing I can think of, is that the global `EntityManager` has a different context than the `EntityRepository` I'm injecting to the Service.

I'm on version 5.0.5

**Comment by B4nan** [comment]
Maybe you are setting the filter params on a fork? You can check the `em.id` to verify you set it on the same instance that is then used for querying.

**Comment by webbster-dev** [comment]
I've checked the id's, and they are different.

In the middleware, I inject the `EntityManager`:
```typescript
constructor(
    private readonly em: EntityManager,
  ) {}
```

This ID is 6.

In my service, I inject the `EntityRepository`:
```typescript
constructor(
    @InjectRepository(User)
    protected readonly repository: EntityRepository<User>,
  ) {
    super(repository);
  }
```

This repository gets passed to the abstract class which does querying on this instance.

I've changed this code so that I inject a `EntityManager` here and get the repository via `em.getRepository(User)`, for the sake of testing.

That ID is 7.

**Comment by B4nan** [comment]
They need to be same, otherwise it can't work. This sounds like you have something wrongly setup, not an issue with the ORM itself, definitely not the same as this one, as that was about setting the params on the global instance (and global instance will have ID 1, not 6 or 7 - that sounds more like you have two following requests).

**Comment by webbster-dev** [comment]
Interesting! I posted it here because it was the only thread I could find that resembled my issue. I'll debug a bit further. Thanks for the help 👍🏻

**Comment by B4nan** [comment]
You can always open a new one, with a new reproduction :] Will be happy to look into it, of course it might be a bug, but the underlying problem is definitely setting the params on a wrong fork. Maybe try putting some logging to the `em.fork()` method, you can also log `new Error().stack` to see where was it called from.

**Comment by webbster-dev** [comment]
I found out that if I set `allowGlobalContext: true` and remove the MikroORM middleware (I got that from [here](https://github.com/mikro-orm/nestjs-realworld-example-app/blob/master/src/app.module.ts#L35)), it works. The ID's are now `1` and my filter is used.

**Comment by B4nan** [comment]
[You need contexts.](https://mikro-orm.io/docs/identity-map#why-is-request-context-needed)

**Comment by webbster-dev** [comment]
Yeah, I read that as well, that's why I had not tried it before, definitely seems like `allowGlobalContext` is not the way to go :(
