### ISSUE TITLE
[feat] cli outputs resolved paths for entitiesDirs*

### ISSUE THREAD

**Issue by lookfirst** [mikro-orm/mikro-orm#136]
When setting up the cli-config file, it would be nice if the cli could output paths to the directories that got resolved. It would lower my mental math when setting things up.

Super low priority feature request.

**Comment by B4nan** [comment]
i am not sure if i wanna dump that when everything succeeds (`cli-config` file is found and some entities are discovered). currently it dumps checked paths when `cli-config` file was not found. it also validates when no entities were discovered. 

i already implemented validation (just not yet pushed) for putting file globs instead of directories in those `entitiesDirs` options (that was your particular problem), so it will again print something more informative.

do you have some other possible problem in mind? we can definitely create new command for debugging, that would print all paths to `cli-config`, if it was resolved, if it used ts-node and if so, then what `entitiesDirs` paths were given in the configuration (ideally absolute paths). it could be simply the default command with a `--verbose` or maybe `--debug` flag.

**Comment by lookfirst** [comment]
I have a `cli-config.ts` file that is in `./src/db/` I tsc into `./build/`. Figuring out the path settings inside of `cli-config.ts` involves me printing out `__dirname` and running the command and then doing mental gymnastics to `../..`. Whatever we can do, even with a debug setting to make that easier for me would be appreciated.

**Comment by B4nan** [comment]
sneak peak

<img src="https://user-images.githubusercontent.com/615580/65354804-b6fa4600-dbf0-11e9-9b2a-6e5edad5227e.png" alt="drawing" width="600"/>

**Comment by B4nan** [comment]
Available for testing in `3.0.0-alpha.9`. Closing as resolved, feel free to reopen if you have some issue with it.

**Comment by lookfirst** [comment]
Dude, this is *excellent*. I imagine that as this project grows, and it will (because well, great job), this will lower the bug reports greatly... or at least make them easier to debug.

**Comment by lookfirst** [comment]
Only other suggestion is to throw version numbers in there so that people can copy/paste it. =)

**Comment by B4nan** [comment]
<img src="https://user-images.githubusercontent.com/615580/65372036-e188e500-dc6a-11e9-8710-b6a4d2235121.png" alt="drawing" width="600"/>

**Comment by lookfirst** [comment]
Sexy. I bet you could add that to stack traces so that when people report issues.... ;-)

**Comment by B4nan** [comment]
I am planning to add a hint about this debug command into errors raised during ORM initialization. I dont want to print that madly for every single error, like when running some malformed query, as it could really pollute logs (we use papertrail so it actually cost money to log too much things).

**Comment by B4nan** [comment]
Dependency versions part published as `3.0.0-alpha.10`
