### ISSUE TITLE
Docs request: comparison against various ORMs

### ISSUE THREAD

**Issue by divyanshu013** [mikro-orm/mikro-orm#1458]
**Is your feature request related to a problem? Please describe.**
Evaluating an ORM for a new product is quite tough. This mostly involves going through various blogs, links, other ORMs, their docs, asking around and trying it out yourself. Since TypeScript is a crucial piece for me it helped in narrowing down choices to TypeORM, MikroORM (and maybe Prisma 2). But I still can't easily tell the differences from other ORMs and what sets MikroORM apart from other ORMs (I did go through docs and understood this is based on "unit of work").

**Describe the solution you'd like**
I think for people like me it would be really helpful to have a table of comparison in the README or maybe a section in the official docs that compares Mikro ORM against other ORMs. I also think this would be best done by the project author (since they would have most context). Happy to hear your thoughts. Cheers!

**Describe alternatives you've considered**
No alternatives other than going through different ORM docs.

**Additional context**
N/A

**Comment by B4nan** [comment]
Yes, agreed this would be nice, but what makes you think I should learn all other tools to make some comparison? :] I never really used any of the other tools, and I am not really interested in learning them.

>  But I still can't easily tell the differences from other ORMs and what sets MikroORM apart from other ORMs (I did go through docs and understood this is based on "unit of work").

Well, here you say you read the docs and at the same time I see you missed the point. UoW is the major differentiator - but it is a huge one. All the other ORMs just make a user API for working with specific entities - this is all abstracted in MikroORM, you load entity, you change it, you flush the changes - and not just one, the whole entity graph. This also allows for implicit transactions - I am not aware of other tools doing that and it should be a big deal for sane developers. The concept of UoW is very different from the rest. Since v4.1 everything is also batched, so if you care about performance, MikroORM should be faster than TypeORM or Prisma. You persist 100 entities, only one query is made. You update 100 entities, only one query is made.... Check the bechmark and article:

https://github.com/mikro-orm/benchmark
https://mikro-orm.io/blog/mikro-orm-4-1-released

For me the main differences are well described in the readme. I don't really see much benefit in having "side by side" table comparison. Comparing ORMs based on features, yeah that sounds nice, until you realize that the same feature might have very different implementation, and you end up comparing apples and oranges. Like look at the TypeORM feature list - they also say they support cascades - but afaik this means only the db level cascading - e.g. this is just about entity definition, not actual feature of the ORM. On the other hand MikroORM has app level cascading - so it works with mongo too, where the DB does not support FKs natively. Or transactions - already mentioned the implicit transactions in MikroORM - nothing other ORMs would to. Or mongo support - that is actually what I tried with TypeORM myself, and it was truly unusable for me - while MikroORM was mongo first library in the early days, and the support for mongo is on high level. 

To be honest, I find it hard to pick something from the list of TypeORM features that would be not possible in MikroORM (yes, there are some for sure, but rather niche features). 

> I also think this would be best done by the project author (since they would have most context). 

Yeah I have the most context about MikroORM, but I have close to zero context on the rest. If I knew the tools, I would already made a comparison myself.

Btw prisma guys already did [some kind of comparison](https://www.prisma.io/dataguide/database-tools/evaluating-type-safety-in-the-top-8-typescript-orms) - but as one can expect, it is more of a marketing rather than a true comparison - obviously they want to promote their own work. All the tools have strong claims about how perfect they are - you need to actually use them to be able to compare if the claims are true and which one is better. If I were paid like them, I would be very happy to spend the time to learn and understand other tools to make a comparison. But as I am not, I don't fell like spending my free time that way :] To be honest I find it a bit discouraging seeing how much money and marketing is spent on promoting prisma - hard to battle with a team of paid devs that are actively promoting and improving the library, when I have just a few small amount of sponsors (it would pay me maybe one working day a month) and a regular daily job 🤷

**Comment by divyanshu013** [comment]
Thanks for your detailed answer. I'll go over the docs again to understand things better.

I went through the comparison you linked from Prisma, true it doesn't do justice at all to anything apart from Prisma.

I think this may be closed since a table of comparison may not be the best approach for this, especially if it requires lot of work on your side going through various ORMs and their docs. I also got some good insights from your answer. Thanks for your time.
