### ISSUE TITLE
`EntityManager.populate` ignores lazy scalar properties.

### ISSUE THREAD

**Issue by mukaschultze** [mikro-orm/mikro-orm#1479]
**Describe the bug**
`EntityManager.populate` does not work with lazy scalar properties.

**To Reproduce**
```ts
import { Entity, JsonType, MikroORM, PrimaryKey, Property } from '@mikro-orm/core';

@Entity()
class A {

  @PrimaryKey()
  id!: number;

  @Property({ type: JsonType, lazy:true })
  lazyProp = {
    a: 0,
    b: 1,
    c: 2,
    d: 3,
  };

}

describe('GH issue 1479', () => {

  let orm: MikroORM;

  beforeAll(async () => {
    orm = await MikroORM.init({
      entities: [A],
      dbName: `:memory:`,
      type: 'sqlite',
    });
    await orm.getSchemaGenerator().createSchema();
  });

  afterAll(() => orm.close(true));

  test(`GH issue 1479`, async () => {
    const fixture = new A();
    await orm.em.persistAndFlush(fixture);
    orm.em.clear();

    const found = await orm.em.findOneOrFail(A, fixture.id);
    const canPopulate = orm.em.canPopulate(A, 'lazyProp');

    await orm.em.populate(found, ['lazyProp'], undefined, undefined, true); // refresh: true

    expect(canPopulate).toBe(true);
    expect(found.lazyProp).toEqual({ a: 0, b: 1, c: 2, d: 3 });
  });
});

```

**Expected behavior**
`EntityManager.populate` should load lazy properties the same way `EntityManager.find` does. Or it should fail the same way it does for non-populatable props.

**Additional context**
[Mikro-orm explicitly ignores the loading of the lazy properties](https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/entity/EntityLoader.ts#L139).

**Versions**

| Dependency | Version |
| - | - |
| node | v15.9.0 |
| typescript | ^4.1.5 |
| mikro-orm | master |
| your-driver | ? |

**Comment by jeesus** [comment]
Can confirm. Using version `4.4.4`. Seems to be only `findOne()` issue though, cannot reproduce with `find()`. 

What's more on lazy properties... when you define the fields to select (including lazy prop), then MySQL gives unknown column error. So there's no way to query for say ID and a lazy property only.

**Comment by B4nan** [comment]
I don't really see this as a bug - `em.populate` is about loading relations, and lazy property is not a relation - populating it means reloading the entity from the first parameter - which is not what `em.populate` does, it only loads its relation properties. 

But agreed this should be working somehow, when using `refresh: true` (that will be probably required).

> What's more on lazy properties... when you define the fields to select (including lazy prop), then MySQL gives unknown column error. So there's no way to query for say ID and a lazy property only.

Please provide repro for that.

**Comment by nspaeth** [comment]
I think where this would be especially useful is when using something like `graphql-fields-to-relations`'s `fieldsToRelations`.

When someone makes a graphql query:
```gql
query {
  myEntity {
	myLazyEntity { id other }
    myNormalField { id other } // e.g., a json column?
  }
}
```
`fieldsToRelations` will turn that into a list of 
`['myLazyEntity', 'myLazyEntity.id', 'myLazyEntity.other', 'myNormalField', 'myNormalField.id', 'myNormalField.other']`

Which will cause an error because `myNormalField` is just a regular column. It would nice if those fields were just ignored.

**Comment by s524797336** [comment]
1、`find/findOne` can `populate: ['lazy']` but can't use `em. populate` sounds wired. they all are populate right?
2、I'm enter the issue when i'm using graphql
schema:
```typescript
@Entity()
class Article {
  @PrimaryKey()
  id!: number;

  @Property({ lazy:true })
  lazyProp: string;
}
```
graphql
```graphql
type Mutation {
  saveArticle(data: SaveArticleInput!): Article!
}

type Article {
  id: String!
  lazyProp: String!
}

input SaveArticleInput {
  id: String
  lazyProp: String
}
```
I use `em.flush()` before response and lazyProp is a field resolver
The life cycle:
```
user request -> mtation saveArticle(update or insert) -> filed resolver lazyProp -> em.flush() -> response
```
The issues:
1. If i load content via `find/findOne` with `populate: ['lazyProp']`, `em.flush()` will not `update/insert` any thing, because `Article` is refreshed.
2. Only when requested graphql query has `lazyProp` field then server should populate `lazyProp`
So there is no way i process `lazyProp` in my field resolver, I can only process it in my query, and code is ugly.
Even `em.populate` can't populate lazy fields, it must has some other method to do the same thing.

**Comment by jeesus** [comment]
I personally didn't understand much, but perhaps you could provide more detailed output of the code you're running.
