### ISSUE TITLE
[bug] SQLite3 Foreign & Primary keys may only be added on create

### ISSUE THREAD

**Issue by lookfirst** [mikro-orm/mikro-orm#150]
Not the end of the world, but starting to see a lot of these in my unit test runs... maybe it can be silenced a bit? ;-)

```
SQLite3 Foreign & Primary keys may only be added on create
SQLite3 Foreign & Primary keys may only be added on create
SQLite3 Foreign & Primary keys may only be added on create
SQLite3 Foreign & Primary keys may only be added on create
SQLite3 Foreign & Primary keys may only be added on create
SQLite3 Foreign & Primary keys may only be added on create
SQLite3 Foreign & Primary keys may only be added on create
SQLite3 Foreign & Primary keys may only be added on create
SQLite3 Foreign & Primary keys may only be added on create
SQLite3 Foreign & Primary keys may only be added on create
SQLite3 Foreign & Primary keys may only be added on create
SQLite3 Foreign & Primary keys may only be added on create
```

**Comment by B4nan** [comment]
This is a bug in knex, or a missing feature maybe. I created an issue there, but they pretty much ignored it :/ 

https://github.com/tgriesser/knex/issues/3351

I am keeping it there as I am still thinking about doing this part myself without knex to have 100% control. I also don't like how they have alter column implemented in postgre (runs many unnecessary queries). 

I would love to rather fix those things in knex, but I want to focus on MikroORM development rather than knex' internals...

**Comment by lookfirst** [comment]
Cool. I'll close this then. Sorry for the dupe.

**Comment by kibertoad** [comment]
@B4nan This is finally supported on knex side.
