### ISSUE TITLE
@Formula and filter conditions for a computed column

### ISSUE THREAD

**Issue by thatsnotright** [mikro-orm/mikro-orm#1599]
**Describe the bug**
I created a field `ageInDays` which is calculated via the Formula decorator as such:

    @Formula(
        (alias) => `case 
        when ${alias}.age_unit='year' then ${alias}.age_value * 365 
        when ${alias}.age_unit='month' then ${alias}.age_value * 30 
        when ${alias}.age_unit='week' then ${alias}.age_value*7 
        else ${alias}.age_value end`
      )
      ageInDays?: number

and I would like to filter on this property, but it seems this filtering is being put in the WHERE clause and not in a HAVING clause for MySQL.

I saw this issue https://github.com/mikro-orm/mikro-orm/issues/734 and also that the Formula decorator is setting persist false but in that commit it looks like only queries using the QueryBuilder were fixed, and we are trying to use the EntityRepository.find method.

**To Reproduce**
Make a Formula column and add conditions to it, then call repository.find(conditions)

**Expected behavior**
I would expect the ORM to extract the computed property in to a HAVING clause 

**Versions**
4.4.4

**Comment by B4nan** [comment]
Formulas were meant for reading so this is more of a feature request. 

Btw you can control the having clause from em.find too, via FindOptions. 

> I saw this issue #734 and also that the Formula decorator is setting persist false but in that commit it looks like only queries using the QueryBuilder were fixed, and we are trying to use the EntityRepository.find method.

EM is using the very same QB under the hood.

**Comment by thatsnotright** [comment]
I can try moving this one clause, the reason it shows up with the other conditions is that the filter is being generated on the UI as JSONLogic or the DevExtreme filter conditions and I convert that to filter conditions of MikroORM without special consideration for the fields.

I can look in to fixing this in a PR if it's a feature request (when I found the other issue I assumed this was a bug) but might need a hint or two on where to start.  I'm working through the code now, and I modified EntityManager.mysql.test.ts to fail this very same way.

Thanks for the feedback and your work on this project.

**Comment by thatsnotright** [comment]
If I move this formula field to the findOptions `having` key and call `findAndCount` I get an invalid field name because the formula isn't used.

**Comment by B4nan** [comment]
Maybe let's start with a proper repro, you said you were able to reproduce it in the tests, so please share how and what exact different would you expect. Also as a rule of thumb, if you are talking about some errors, please share the exact error message and the stack trace. 

> when I found the other issue I assumed this was a bug

The other issue is about prefixing the name (e.g. instead of `ageInDays` it would be `e0.ageInDays` which is obviously invalid). This feels like you are talking about something quite different (moving conditions from `where` to `having`).

**Comment by B4nan** [comment]
Looking at your test case, and I am not sure how you expect the second one to be working. Count query selects only the count, and you want to use a formula and filter by that in having clause? 

We could inline the formula in such case I guess, but this all feels like a lot of magic, hard to understand why you called this a bug in the first place :P

**Comment by thatsnotright** [comment]
What is invalid about wanting the count of all records matching the criteria as well as a partial result for pagination reasons?  If I want all books where the price after tax is < 2 with a limit 10, this is a valid query and in order to know how many pages of results this would generate I need the count of matching records.  The bug is that MikroORM is not including this criteria properly to give me the total count of all records.  This is valid SQL, I'm not understanding why you don't see it as a bug in MikroORM.

**Comment by B4nan** [comment]
> What is invalid about wanting the count of all records matching the criteria as well as a partial result for pagination reasons? 

Nothing, not sure where you read that. I was just explaining the issue you linked, as it has pretty much nothing to do with this, I am not trying to say this one is invalid.

> If I want all books where the price after tax is < 2 with a limit 10, this is a valid query and in order to know how many pages of results this would generate I need the count of matching records. 

You say "this is a valid query", but we are talking about how you use/instruct the ORM, not about SQL. And in that sense, this is not a valid query. Virtual properties were not mean to be used that way, not in the current implementation. They were introduced to allow few things (mainly mapping of computed properties to entities), but this was none of them.

> The bug is that MikroORM is not including this criteria properly to give me the total count of all records. This is valid SQL

What is a valid SQL? I am literally asking you to provide what exact query you would expect in such case. Again, I am talking about the second test with count query.

> I'm not understanding why you don't see it as a bug in MikroORM.

Worth nothing that are expecting things to work somehow (and I am not even sure how exactly, hence asking), but they were neither designed, nor documented that way. So that is why I don't consider this a bug. With this thinking, everything you try and is not working would be a bug (and indeed, many people act that way, which is quite discouraging for library maintainers).

It's friday evening (at least in where I live), so let's not be offensive. I do not consider this a bug, but I am all in for supporting it. But as you are the one who raised it (and you clearly have a vision how it should work), I want you to provide the details how you expect it to work.
