### ISSUE TITLE
docs: add section about deploying to production

### ISSUE THREAD

**Issue by B4nan** [mikro-orm/mikro-orm#167]
- how does entity discovery work when running against compiled code via `node`
- how to deploy only compiled output (providing `type/entity` attributes where needed)

Based on #165.

**Comment by RichardBosworth** [comment]
This would be very useful.
I'm trying to deploy a NestJS Mikro app (via a monorepo) to a Docker container, and get the error of:
`Source file for entity /feedback-email.model.ts not found, check your 'entitiesDirsTs' option`

I'm running the Dockerfile as such:
```
FROM node:latest as build

RUN npm install -g @nestjs/cli

RUN mkdir /build
WORKDIR /build
COPY . /build

RUN ls -l

RUN npm install
RUN npm run build:dependencies
RUN nest build ${IMAGE_NAME}


FROM node:alpine as app
RUN mkdir /app
WORKDIR /app
COPY package.json nest-cli.json tsconfig.build.json tsconfig.json libs ./
COPY --from=build /build/dist/ ./dist/
RUN ls -l
RUN npm install --only=production
ENTRYPOINT ["node", "/app/dist/apps/${IMAGE_NAME}/main.js"]
```

As you can see, I'm using the first image to build the NodeJS application, then using the alpine version to run it.

I've had to include the "libs" folder .ts files for most of the projects (as it contains shared entity classes), but for the "email" microservice, the .ts entity file is contained within the app src folder, so is built to a .js file.

Any advice about this in documentation would be great.

If you would like me to start a new issue, I can?

**Comment by B4nan** [comment]
> I've had to include the "libs" folder .ts files for most of the projects (as it contains shared entity classes), but for the "email" microservice, the .ts entity file is contained within the app src folder, so is built to a .js file.

Why not copying that file by name, like you do with those json configs?

> If you would like me to start a new issue, I can?

Nope, this is about deployment, so why not to have it here :] 

Have you seen this? The deployment section will be pretty much based on this answer. You can remove the requirement for deploying TS source files of entities by stating all `type` or `entity` attributes in entity decorators (so that could be another way to solve your issue with the `feedback-email.model.ts` not being copied - you could fill the decorators just on this one).

https://stackoverflow.com/questions/55523319/how-to-release-or-distribute-an-application-that-uses-mikro-orm

Btw personally I am also deploying NestJS app bundled to docker, and I just copy all the source files - is there any particular reason why you do not want that? I would guess it won't matter much regarding the image size. 

Recently I was thinking about this problem, and one idea I had is to introduce new CLI command, that would modify your existing entities, reading the TS types and filling the decorators for you. Just an early idea how to ease the deployment. Also tagging @lookfirst, WDYT?

**Comment by lookfirst** [comment]
I'm currently deploying to firebase/google cloud functions, which basically 'spins' up an instance of my app in a container and runs it. There isn't much control over deployment, it seems to just take what is in your `package.json::main` and the rest of the directory structure and copies it up to the cloud. It looks like I'm just deploying the `.js` files and I can see	`entitiesDirs: ['./build/src/db/model'],` is what is used. I can't tell if it copies up the generated .json files, but I don't think so.

Pretty much every request that comes in (I have apollo in front providing a graphql api) gets a new container because they are effectively run single request. They even tell you to set the connection pool to 1 cause a burst of requests will spin up that many connections.

Right now, I'm getting this ~500ms penalty `[discovery] - entity discovery finished after 475 ms` on almost every request that comes in. I only have 7 entities and as my app grows, will only get slower. I can see that it does use the 'cached' files though (`using cached metadata for...`), so that is nice.  Frankly, entity processing hit sucks though. I'd rather find a way to not have it.

I will likely move off cloud functions at some point and onto an AppEngine Flexible instance... which tends to not shut down as much and I can resize to larger instances for speed.

One tip I see in the above Dockerfile is... use yarn. It is vastly faster than npm. Copy over the yarn.lock file and you get reproducible builds. I just put "*" in my package.json versions now.

**Comment by B4nan** [comment]
500ms sounds weird if it hits cache for all entities, it should be much faster I would say. Btw the slowness comes from initial hit in ts-morph, so if you hit cache 6 times out of 7 entities, it will be pretty much same as without the cache. 

Also, it is correct that you see compiled dirs in entitiesDirs, that should be there always, unless you use ts-node. 

For cloud functions, it would be probably best to deploy the cache as well. Maybe bundling via webpack (#196) could also help, once we do support it. I would prefer that instead of suggesting to deploy the cache. 

But again, if you have all decorators filled with type or entity attributes, the discovery should be really quick (no ts-morph involved), so that is why I was proposing a way to propagate those types automatically via cli. Still not 100% sure what would the best solution, will need to find some time to experiment myself, as my setup does not have such problems.

**Comment by jsprw** [comment]
>For cloud functions, it would be probably best to deploy the cache as well. Maybe bundling via webpack (#196) could also help, once we do support it. I would prefer that instead of suggesting to deploy the cache.

If needed I can write a section how to deploy with webpack while dynamically loading all entities from an entitiy directory (as alternative to support the entityDirs options in the webpacked/deployed version, see https://github.com/mikro-orm/mikro-orm/issues/194#issuecomment-540817440).

**Comment by B4nan** [comment]
Yeah that would be great. Working example of how to integrate with webpack build could be also good, but I would love to have this kind of information in the deployment section too.

**Comment by lookfirst** [comment]
I have full decorators on everything. I even kind of like how type-graphql pretty much won't work without full decorators (gives an error on things you'd think would just work magically).

I'm personally not excited about adding a build step (webpack, rollup, parcel). We're not sending this code to a browser, which is the problem these tools were built to solve. Especially not excited about one that transforms code even further than `tsc`. I really wish there was a version of node that straight up parsed typescript over javascript without even a transform step.

There is already enough moving parts in the JS ecosystem. Most recently stack traces have seemingly become pretty incoherent on the react web side of things due to a massive amount of recursive nesting, it isn't a good sign. Adding another transform step means fixing all the `.map` files...

If anything, make the cache into javascript so I can just 'import' it somehow.

**Comment by lookfirst** [comment]
It is taking about 5-15ms to just figure out to use the cache...

![image](https://user-images.githubusercontent.com/85355/66711434-e6e2d680-edb5-11e9-8cef-8654f4663b5c.png)

**Comment by lookfirst** [comment]
My largest entity... Rig...

![image](https://user-images.githubusercontent.com/85355/66711445-2dd0cc00-edb6-11e9-93f3-41c0821eb476.png)

**Comment by B4nan** [comment]
Well on my localhost, discovery with production build of my nest api (10+ entities, pretty complex relationships, total of 39 files in entities directory), when cache is present, it takes just **26ms** to do the full discovery process. 

Sounds like cloud functions are pretty slow. 

> If anything, make the cache into javascript so I can just 'import' it somehow.

It's JSON so you can just `require` it. But your slowness issue is not about caching, if the cache is hit for all entities.

**Comment by lookfirst** [comment]
> Sounds like cloud functions are pretty slow.

There is no guarantee on the start up time on them, that is the issue. But they scale infinitely (automatically) and I don't have to run a server or think about devops. It is the tradeoff right now.

**Comment by B4nan** [comment]
Added some basics here: https://github.com/mikro-orm/mikro-orm/blob/dev/docs/deployment.md

Feel free to suggest additional content.

**Comment by lookfirst** [comment]
This looks great, what I want now is a mode to give me the inverse... tell me which entities/properties don't have type information that causes things to have to hit the cache. This way, I can go and fill in the missing bits.

**Comment by B4nan** [comment]
Maybe we could add `StrictMetadataProvider` that would throw such errors? Also this sounds exactly like a use case for the new CLI command I suggested

> Recently I was thinking about this problem, and one idea I had is to introduce new CLI command, that would modify your existing entities, reading the TS types and filling the decorators for you. Just an early idea how to ease the deployment. Also tagging @lookfirst, WDYT?

**Comment by lookfirst** [comment]
I was thinking a CLI command for sure.

**Comment by lookfirst** [comment]
Something I can run from CI to make the build fail. =)
