### ISSUE TITLE
@beforeCreate

### ISSUE THREAD

**Issue by royalcala** [mikro-orm/mikro-orm#1681]
Im using  the structuring like the example with express  app.use((req, res, next) => RequestContext.create(db.orm.em, next));
but persist or flush doesnt do changes when I called them into a decorator @BeforeCreate(), doesnt trigger any query
```
  @BeforeCreate()
    versionInsert() {
        console.log('beforeCreate')
        let version: Version
        if (asyncLocalStorage.getStore()?.has('token')) {
            const token: Token = asyncLocalStorage.getStore().get('token')
            version = new Version({ id_document: this._id, user: token.id_user })
        }
        else
            version = new Version({ id_document: this._id, user: null })
        db.orm.em.persist(version)        
    }
```

**Comment by B4nan** [comment]
You need to use `onFlush` event for this, using EM inside hooks won't work because the change sets are already computed (you would need a second flush call to have an effect).

https://mikro-orm.io/docs/lifecycle-hooks/#limitations-of-lifecycle-hooks
https://mikro-orm.io/docs/lifecycle-hooks/#using-onflush-event

**Comment by royalcala** [comment]
thanks!

**Comment by arcticfly** [comment]
Thanks @B4nan!
Updated links are:

https://mikro-orm.io/docs/events#limitations-of-lifecycle-hooks
https://mikro-orm.io/docs/events#using-onflush-event

**Comment by B4nan** [comment]
Huh, there should be redirects for the old one, will check, thanks for the note
