### ISSUE TITLE
Searching for value of any field in MongoDB without explicitly naming it

### ISSUE THREAD

**Issue by Lishenga** [mikro-orm/mikro-orm#1690]
Does MikroORM have a feature of making a filter query to a mongodb collection and not specify the field for the filter or search to happen making MikroORM to filter on all the fields in that collection. When the filter is taking place, any document with the field that has a match of the specific filter search string should be returned. 
So, here is what I'm looking for. Assume I have a collection with elements like this:

```json
{
   "foo" : "bar",
   "test" : "test",
   "key" : "value",
}
```

What I'd like to achieve is find an element by searching in all (maybe except for finitely many ;-) ) fields. In other words: Given a query, I do NOT know in which field the query should be found.

In my thinking something like this

```js
db.things.find({_ANY_ : "bar"}) 
```

MongoDB documentation gives insight of how this can happen. You can check it out on this link [https://docs.mongodb.org/manual/tutorial/create-text-index-on-multiple-fields/](url) and also this link [https://docs.mongodb.org/manual/reference/operator/query/text/](url).

The two links propose the use of indexes by creating an index and searching using the index on the specific collection. Is this possible in MikroORM?

**Comment by B4nan** [comment]
Nope, no plans to do this, sounds quite out of space and even kinda dangerous (not just performance-wise). If you want, you can build the query yourself via metadata. 

```ts
const value = 'bar';
const propertyNames = em.getMetadata().get('Book').props.map(p => p.name);
const cond = { $or: [] };
propertyNames.forEach(prop => cond.$or.push({ [prop]: value });
```

You could put this into custom repository.

But I would strongly suggest to rather whitelist the properties instead of blindly searching in everything (why would you search objectids for a string? It would only have weird side effects.)
