### ISSUE TITLE
Working with collections and arrays

### ISSUE THREAD

**Issue by jasonwilson** [mikro-orm/mikro-orm#1717]
**Is your feature request related to a problem? Please describe.**

After reviewing the docs it doesn't seem like there's a clear way to convert and or merge a json array off the wire into a collection. Is this supported? If so, some more examples could be helpful.

Tried using wrap(entity).assign(data, { ... merge params ... }) but the data isn't present in the entity.

**Describe the solution you'd like**

Some means to merge a json array with a collection or just use native arrays.

**Comment by evantrimboli** [comment]
What do you mean by merge? Can you elaborate?

**Comment by B4nan** [comment]
I don't fully understand what you want, but at the same time I don't see a need for any additional API. If you want to propose a feature, do it properly and show us (in code and examples) what you would like to change and why. Let's not use pseudocode like you did, as you omit the most important part there.  

You can already use `assign` helper with collections, and indeed use an array of items there (objects if you want to create new entities, or PKs if you want to use existing ones). 

@evantrimboli there is already `Collection.set()` for this, you need to put entities there. No plans to add the `merge` method as you described, if you want to use DTOs, the correct way is the `assign` helper that already supports this too (although not that proposed "update something just because it shares the PK, this is something much more complicated than it sounds, especially because such entities might not be loaded, so we can't tell whether to use insert or update query, as we can't verify it either as we are in sync context). 

> Some means to merge a json array with a collection or just use native arrays.

You can work with native (scalar) arrays already (if the driver supports it, e.g. mongo or pg, or with emulated if not - there is `ArrayType` that is used automatically if we see array property). For arrays of objects, you need to use JSON, and that is indeed supported too. Merging a JSON array to a collection is out of scope, there won't be any method just for this. If you show some code maybe we can help, as this should be easily possible too with the `assign` helper or with `Collection.add()` combined with `em.create()` or `em.merge()`. 

There are some tests for assigning to collections [here](https://github.com/mikro-orm/mikro-orm/blob/master/tests/EntityAssigner.mysql.test.ts#L53). But it can't be used for "merging", it will never add to existing collection, only replace items (and to use existing items, you need to pass their PKs, not whole objects). 

So if you are up to moving contents of JSON array full of objects, you first need to build the entities from that, and rather use `Collection.add()`. Should be streigtforward:

```ts
const arr = [{ name: 'a' }, { name: 'b' }, { name: 'c' }]; // the JSON array with DTOs
const users = arr.map(item => em.create(User, item)); // depends on what you want, this will create new entities
// const users = arr.map(item => em.getReference(User, item.id)); // if you have PKs there instead, use `em.getReference()`
someEntity.users.add(...users); // append to existing collection, or use `set` to replace existing items with the new ones
```

Will close this, as this should be enough for you, but again, will be happy to hear more if you still see a room for improvement. But don't expect "too smart APIs" as things often needs to be be explicit (e.g. you need to pass the right EM here and there otherwise it will not work).

**Comment by jasonwilson** [comment]
Here's an example with the behavior we're observing. In this case calling update on the nested entity doesn't assign the new data. Is this expected?

```
import { Collection, Entity, ManyToOne, MikroORM, OneToMany, wrap } from "@mikro-orm/core";
import { PrimaryKey, Property } from '@mikro-orm/core'
export abstract class BaseEntity {
  @PrimaryKey({ columnType: 'uuid', defaultRaw: `gen_random_uuid()` })
  id!: string
  @Property()
  createdAt: Date = new Date()
  @Property({ onUpdate: () => new Date() })
  updatedAt: Date = new Date()
}
@Entity()
export class Receipe extends BaseEntity {
  @Property({ nullable: true })
  someproperty?: string
  @OneToMany({ entity: () => Ingredient, mappedBy: (ingredient) => ingredient.receipe })
  ingredients = new Collection<Ingredient>(this)
}
@Entity()
export class Ingredient extends BaseEntity {
  constructor(partial: Partial<Ingredient>) {
    super()
    wrap(this).assign(partial)
  }
  @ManyToOne({
    entity: () => Receipe,
    nullable: false,
  })
  receipe: Receipe
  @Property({ nullable: true })
  name?: string
}
(async () => {
  const orm = await MikroORM.init(
    {
      entities: [Ingredient, Receipe],
      dbName: '-----',
      type: '-----',
      password: '-----',
      host: 'localhost'
    }
  );

  const recipe = {
    someProperty: "lasagna",
    ingredients: [
      {
        name: "cheese"
      },
      {
        name: "noodles"
      }
    ]
  }
  const r = orm.em.create(Receipe, recipe)
  await orm.em.persistAndFlush(r)
  const loaded = await orm.em.findOneOrFail(Receipe, { id: r.id }, ['ingredients'])
  console.log(loaded)
  /**
   * Receipe {
  createdAt: 2021-04-26T19:59:41.799Z,
  updatedAt: 2021-04-26T19:59:41.799Z,
  ingredients: Collection {
    '0': Ingredient {
      createdAt: 2021-04-26T19:59:41.800Z,
      updatedAt: 2021-04-26T19:59:41.800Z,
      name: 'cheese',
      receipe: [Receipe],
      id: '5ce433c4-e1f8-4dd6-b5ac-9f2c229c2f5b'
    },
    '1': Ingredient {
      createdAt: 2021-04-26T19:59:41.801Z,
      updatedAt: 2021-04-26T19:59:41.801Z,
      name: 'noodles',
      receipe: [Receipe],
      id: 'bfa9e0d4-d209-4571-9350-0712b70e229a'
    },
    initialized: true,
    dirty: false
  },
  id: '1830f689-7852-4f6a-814a-61a616b3b882'
}
   */
  const updated = JSON.parse(JSON.stringify(loaded))
  updated.ingredients[0].name = 'updated name'
  wrap(loaded).assign(updated, { updateNestedEntities: true })
  console.log(loaded)
  /**
   * Receipe {
  createdAt: 2021-04-26T19:59:41.799Z,
  updatedAt: 2021-04-26T19:59:41.799Z,
  ingredients: Collection {
    '0': Ingredient {
      createdAt: 2021-04-26T19:59:41.800Z,
      updatedAt: 2021-04-26T19:59:41.800Z,
      name: 'cheese',
      receipe: [Receipe],
      id: '5ce433c4-e1f8-4dd6-b5ac-9f2c229c2f5b'
    },
    '1': Ingredient {
      createdAt: 2021-04-26T19:59:41.801Z,
      updatedAt: 2021-04-26T19:59:41.801Z,
      name: 'noodles',
      receipe: [Receipe],
      id: 'bfa9e0d4-d209-4571-9350-0712b70e229a'
    },
    initialized: true,
    dirty: true
  },
  id: '1830f689-7852-4f6a-814a-61a616b3b882'
}
   */
})()
```

**Comment by B4nan** [comment]
I see, looking at the code, apparently `updateNestedEntities` flag is implemented only for M:1 and 1:1 relations.

**Comment by jasonwilson** [comment]
Thanks for the quick fix @B4nan! Any idea when this will be published?

**Comment by B4nan** [comment]
Use `4.5.5-dev.1` for now.
