### ISSUE TITLE
Is it possible to connect via an UNIX domain socket

### ISSUE THREAD

**Issue by service-paradis** [mikro-orm/mikro-orm#1787]
**Is your feature request related to a problem? Please describe.**

I'm using Google Cloud SQL for my databases I'm using Firebase Functions for my API using Nest. I want to use MikroORM.
I need to connect to the database (in production) via UNIX domain socket, but I cannot find any documentation about this in the current documentation.

It is possible to do so using [Knex](https://knexjs.org/):
```javascript
const knex = require('knex')({
  client: 'mysql',
  connection: {
    socketPath : '/path/to/socket.sock',
    user : 'your_database_user',
    password : 'your_database_password',
    database : 'myapp_test'
  }
});
```

It is also possible using [TypeORM](https://stackoverflow.com/a/50298350/2774496):
```json
{
  "type": "mysql",
  "extra": {
    "socketPath": "/cloudsql/<project>:<region>:<database>"
  },
  "port": 3306,
  "username": "myuser",
  "password": "secret",
  "database": "mydb"
}
```

**Describe the solution you'd like**

I really want to use MikroORM, but I'm not sure if I can connect to my database using UNIX domain Socket. If it is possible, it would be a great addition to the documentation. If it is not possible, it would be a great addition to the package!

**Describe alternatives you've considered**

I considered TypeORM.

**Additional context**

Cloud SQL connection reference: https://cloud.google.com/sql/docs/mysql/connect-functions#node.js
Knex reference: https://knexjs.org/#Installation-client
How to use it in TypeORM: https://stackoverflow.com/a/50298350/2774496

**Comment by javiercani** [comment]
@service-paradis could you implement your socketConnection only by adding the driverOptions property?

**Comment by mareksuscak** [comment]
There's some room for improvement here. I've struggled with this for a long while because the documentation doesn't explain some of the important details and the implementation is not super straightforward either. 

This is what I have in my config file and it worked for us in both local development and in Cloud Run (using Cloud Proxy, not Serverless Connector which is more straightforward as it uses TCP, not Unix Sockets):

```ts
const config = defineConfig({
  driverOptions: {
    connection: {
      connectionString: process.env.DATABASE_URL,
    },
  },

  // This is a dummy value that is overriden in driver options. This is because MikroORM's connection string
  // parser doesn't fully support unix socket connection strings whereas Knex and the underlying pg package
  // supports the socket protocol out of the box:
  // Refs:
  // - https://www.npmjs.com/package/pg-connection-string
  // - https://knexjs.org/guide/#configuration-options
  // - https://mikro-orm.io/docs/configuration/#driver
  clientUrl: 'postgresql://postgres@127.0.0.1:5432/db',

  // …
})
```

Then `DATABASE_URL` can be any of the following:

- `socket://user:password@/cloudsql/project:region:instance?db=dbname` in Cloud Run
- `postgresql://user:password@host:port/dbname` in local dev env

I've been trying to use a PG-specific connection string as described in the documentation for [pg-connection-string](https://www.npmjs.com/package/pg-connection-string) npm package used as an internal connection string parser by the the `pg` driver. There are a few issues:

1. It is not clear that MikroORM doesn't delegate parsing on to the underlying driver and tries to parse the connection string itself using a custom parser that doesn't support certain features (such as the `socket:` protocol).
2. It is not clear that `driverOptions` expect a knex config object rather than the underlying driver config
3. Even though I can override the settings, I still need to provide either a dummy `dbName` or `clientUrl`, otherwise the MikroORM refuses to start because it still attempts to parse the connection string
4. The config above is the only way I was able to get Cloud SQL Unix Socket connection to work as expected using a connection string rather than separate properties for host, username, password and db name. The connection string unifies the db connection approach across different environments (local, dev, production). However, MikroORM then logs the wrong connection string on stdout - the dummy value instead of the actual connection string.
