### ISSUE TITLE
Provide the way to store DATETIME in specific timezone

### ISSUE THREAD

**Issue by vimmerru** [mikro-orm/mikro-orm#181]
**Is your feature request related to a problem? Please describe.**
Now when converting Date to sql type local timezone is used. It would be nice to have a settings to force specific timezone like UTC. 

Without this settings i will get different results if BE in another timezone.

**Comment by B4nan** [comment]
Datetime with TZ is always stored in UTC, or not? I thought the whole point of timezones is that you normalize for saving and apply timezone when reading.

**Comment by vimmerru** [comment]
> Datetime with TZ is always stored in UTC, or not?

Javascript Date type always has timezone information, but sql Datetime no. MySQL retrieves and displays DATETIME values in 'YYYY-MM-DD hh:mm:ss' format without timezone information. 

MikroORM now converts Date to  'YYYY-MM-DD hh:mm:ss' representation using NodeJS timezone. It isn't bug, but the most of people will prefer to see UTC in database despite the fact of NodeJS environment settings.

**Comment by vimmerru** [comment]
TypeORM has settings to force timezone that will be used to covert 'YYYY-MM-DD hh:mm:ss' values to js Date.

**Comment by vimmerru** [comment]
For TIMESTAMP type handling is more complex. MySQL as i know always stores it in UTC, but communication is performed in some tz specific for connection.

**Comment by B4nan** [comment]
I would expect this to be solved simply by providing the timezone you want to be saved in driver options. Looks like mysql2 has support for that (https://github.com/sidorares/node-mysql2/pull/996), I would expect other drivers to have similar configuration. Will take a look into this later.

**Comment by vimmerru** [comment]
@B4nan 

Is it possible now to override some driver-level settings?

**Comment by B4nan** [comment]
Currently not.

**Comment by lookfirst** [comment]
You should always store day/time in a database in UTC. Let the client convert it to the local timezone when displaying it to an end user.

**Comment by B4nan** [comment]
Another note for discussion. JS dates are always UTC timestamps (represented based on current user's timezone), so it should be also stored in UTC by default in the database. 

I think what's missing in the ORM is support for setting current timezone, not for writing, but for reading. That is what I was doing when working with other ORMs (mainly doctrine), simple `SET time_zone = 'Europe/Prague'` (for mysql) when initializing the connection.

**Comment by lookfirst** [comment]
How do you know what TZ is correct though? That would assume all the 'users' are in that TZ and want to view things under that TZ. Again, far better to make the TZ a client preference. If you don't have anyone viewing the TZ, then just keep it at UTC... this also avoids pesky daylight savings issues. Convert to local TZ at the very last step.

I worked with a system a long time ago that was built around the concept of cron jobs running at a certain time in the clients timezone, based on a database entry. The guy who designed it thought he was smart to offer this 'feature' to the customers... until they grew in size and it blew up and took down the entire system. It was a nightmare because every time the hour changed for daylight savings, cron jobs would either run twice or not run at all.

Wrote this 9 years ago... http://lookfirst.com/2010/05/how-to-solve-daylight-savings-time.html

**Comment by B4nan** [comment]
> How do you know what TZ is correct though?

Right, that wouldn't solve much when you expect users from different timezones. What we can agree on is that datetimes should be stored in UTC. 

@vimmerru If I understand it correctly, mysql will save the datetime in current timezone instead? So that mysql2 option I was mentioning would fix this at least? 

@lookfirst What would be your suggestion here? I understand that in the end, if you wanna have different timezones based on user's TZ, you will need to handle this manually. But still, the database value needs to be in UTC. 

Will need to try things myself to wrap my head around this...

**Comment by vimmerru** [comment]
> @vimmerru If I understand it correctly, mysql will save the datetime in current timezone instead? So that mysql2 option I was mentioning would fix this at least?

Yes, mysql2 option should help

**Comment by lookfirst** [comment]
My suggestion is to store everything UTC and set the database/OS to UTC. If you need local time, convert it at the client where it is used. Don't build anything that depends on the server returning a time in a TZ.

**Comment by vimmerru** [comment]
Thanks! I will try this soon. For now we are forcing node to UTC timezone through environment, but it doesn't work for Windows platform.

**Comment by localnet** [comment]
I haven't test, but MariaDB driver seems use a similar approach to MySQL2 driver:

https://github.com/MariaDB/mariadb-connector-nodejs/blob/master/documentation/promise-api.md#timezone-consideration

**Comment by lookfirst** [comment]
"It's not recommended"

**Comment by B4nan** [comment]
In `3.0.0-rc.2` there is now `forceUtcTimezone` option to force the datetimes to be saved in UTC in datetime columns without timezone. It works for mysql (datetime type) and postgres (timestamp type). Sqlite does this by default. 

The mariadb driver is unfortunately buggy there, it throws and error when the `timezone` config option is provided (at runtime, the value passes their internal validation).
