### ISSUE TITLE
em.create(Entity, dto) does not create expected entity

### ISSUE THREAD

**Issue by Langstra** [mikro-orm/mikro-orm#1831]
**Describe the bug**
In NestJS (and probably other frameworks), you use DTO's (Data Transfer Objects) to transfer data between controller, service, repository. The DTO can also be used to validate the request data. A DTO is a JavaScript object.

It'd use the DTO to create entities directly. `em.create(Project, projectDto)` and this worked until v4.5.3 (I think, but at least 4.4.2 which is what I upgraded from). Now on v4.5.5 it does not correctly create the entity. 

Relations of the entity look like this: 
```
Project {
      filters: Collection {
        '0': Ref<Filter> { id: [FilterDto], project: [Reference] },
        initialized: true,
        dirty: true
      },
      name: 'Project name'
    }
```

So the id of the relation entity is set to the entire object.

**To Reproduce**
1. Checkout PR #1830
2. Run the test case `GH1831.test.ts`
3. 

**Expected behavior**
It should create the entities relations correctly. A workaround it to do `JSON.parse(JSON.stringify(projectDto))`, but this should not be necesary.

**Additional context**

**Versions**
Running on up to date master branch

**Comment by B4nan** [comment]
You can't use classes for DTOs, it has to be POJO (no prototype, just `{}`).

**Comment by B4nan** [comment]
What I can offer, and I already said this somewhere else too, is that we could have either a special symbol that you would add as a property to your DTOs, or a DTO class you could extend, so the ORM would consider those as POJOs. Btw the very same problem is with `FilterQuery` and all its children - objects has to be POJOs otherwise we consider those as leaf values. This way we can handle things like `Knex.Raw` or custom type object values properly. 

The check is in `Utils.isPlainObject()`, feel free to send a PR, I am fine with both ways (and I'd probably like to support both if something).
