### ISSUE TITLE
Assign method does not work in custom base entity for nested entities

### ISSUE THREAD

**Issue by driescroons** [mikro-orm/mikro-orm#1838]
**Describe the bug**
I have a custom base entity of which all of my entities extend from. This entity base has an assign method which I'd like to use for both my constructor and when merging entities.

![image](https://user-images.githubusercontent.com/27679518/118888515-0e881200-b8fc-11eb-8418-28c613a986df.png)

When using the assign method in the constructor of the base entity, my nested objects don't get perstisted. However, when I move this assign method to the constructors of the Entities itself, the assign works as expected.

I'd like to use this assign for my base entity constructor (so I don't have to call it all entities) and also use it to merge entities after they've been created. This makes it so I can pass DTOs (that have been validated), in order to create (using the constructor) and update entities (using the assign method that is called in the constructor).

## Entities 

Base entity:

- abstract class that extends the BaseEntity from MikroOrm
- Used for shared variables

Question entity:

- extends Base entity
- has a 1:M to Option

Option entity

- extends Base Entity
- has a M:1 to Question

# Tests

I've setup 4 tests to show the issue in 2 test files.

## in-base.test.ts

I assign the body of my DTO in the custom entity base constructor.

### Should create nested entities with assign in base

This test `fails` because it expects options to be persisted to the database. For some reason, using assign in the custom base entity constructor, does not persist the options.

### should update nested entities with assign in base

This test `succeeds` because I used the create method first, instead of the constructor, and update the object, using the same assign method.

## not-in-base.test.ts

I assign the body of my DTO in each specific entity constructor.

I've also tested leaving out the assign in the option constructor, but that does not seem to make a difference.

### should create nested entities with assign not in base

This test `succeeds` because it expects options to be persisted to the database. Which is the case, if the assign is not in the constructor of the custom base entity.

### should update nested entities with assign not in base

This test `succeeds`. I did not have to use the .create method, but just used the constructor. (because I've tested `should create nested entities with assign not in base` mentioned above)

**To Reproduce**
I've setup a reproduction repo with a couple of tests:
https://github.com/driescroons/mikro-orm-constructor-assign-issue

To run

```
yarn
```

```
docker-compose up -d
```

``` 
yarn test
```

**Versions**

| Dependency | Version |
| - | - |
| node | 14.15.4 |
| typescript | 4.2.4 |
| mikro-orm | 4.5.5 |
| your-driver | postgresql |

**Comment by driescroons** [comment]
I had seen this [comment](https://github.com/mikro-orm/mikro-orm/commit/db77e8b9b9e7b3c29120333142f517b98b915755#diff-d45c7ace8b3cc698ca27b9b1848bc434e091866cc6d8bf5408d4b9a47b20f810R224) from this [issue](https://github.com/mikro-orm/mikro-orm/issues/1717) and wanted to check if I could just pass (validated) DTOs (with nested entities) without having to do any transformations to the objects.

**Comment by B4nan** [comment]
I said this many times, `assign` was designed for updating existing entities, so using it from inside ctor seems quite weird. Also seeing that you are feeding the `em` parameter via `RequestContext` helper sounds weird too, but as long as you managed to run everything inside the handler, it should be fine'ish - still not perfect, you need to pass the right EM instance there, and there can be multiple for a single request (e.g. nested explicit transactions). Doing `assign(new Entity, {...})` is literally the opposite of what the API was designed for, we have `em.create` for that (and the behaviour is not the same, especially when it comes to nested entities and collections). But as long as you are aware of what you are doing, it should work somehow 🤷 

Worth noting, that the `updateNestedEntities` parameter will change behaviour, I would not use that as the (in your case unchangable) default, unless you understand what it does, especially for collections. See #1811. 

FYI this kind of reproductions are not very good for me, if you want to make this nicer, one single file test case with 4 methods would be 100x better - e.g. just the one file so I can copy&paste into the repo directly, right now there are way too many files and moving parts in general, also it's nice to provide test case, but if you use different testing/assertion FW than the ORM, it just adds more work to me). 

Anyway, I managed to port it to jest and plug it into the ORM codebase, and the problem here is that you are calling `assign` too early - before the collections gets instanced. As you are doing it inside the base entity, it is executed earlier than the leaf entity ctor, which effectively means that the property intializers of its properties are not yet executed. **In other words, you are trying to assign to a collection that is not there, so it gets ignored.** 

> I had seen this comment from this issue and wanted to check if I could just pass (validated) DTOs (with nested entities) without having to do any transformations to the objects.

This is just about the new `EntityDTO` type that is new in v5.

**Comment by driescroons** [comment]
Thanks for the quick reply. I'll use the `.create` method when initializing new entities. 

I used two test files because of the changes in the entities. I figured it was going to be too complex if I just put everything into 1 test file. Makes sense though. As for mocha + chai, my bad. I should've looked at the tests in the repository.

**Comment by B4nan** [comment]
Best way for me is to add a test to `tests/issues` folder (either make a PR, or just copy the test code into issue). 

Btw I'd call this a won't fix, even if we handle the "collection instance is not yet there" problem in `assign`, the leaf entity constructor would be called right after the assign from base entity, and it would override the (just updated) collection instance with `new Collection()`.

- `Base.constructor` is called, after `Base` entity property intializers, but before child entity ones
- `Base.constructor` calls `assign`, we still not have the initializers of child entity (e.g. `Question.options` is undefined)
- let's say we create the instance automatically and pass the values, `Base.options` will be now the updated collection
- `Question.constructor` is called, executing `Question` initializers first, so overriding the `Question.options` with `new Collection()`
