### ISSUE TITLE
[Question] Firebase driver feasible?

### ISSUE THREAD

**Issue by endel** [mikro-orm/mikro-orm#1845]
Would it be feasible to implement a Firebase driver for MikroORM?

(This is not a feature request, I'm just curious if that'd be possible/feasible!)

Thanks! Cheers! 🤗

**Comment by B4nan** [comment]
As long as you can store arrays of PKs, it should be just fine. It would probably work like the mongo driver, which is somehow limited (no joins, so no nested filtering).

**Comment by B4nan** [comment]
Closing as you said this is not really a feature request. 

I'd envision additional drivers to first exist as 3rd party modules, that can be integrated once tested in the wild - mainly because having them in the repo would mean more things to maintain for me (as a matter of fact, most of the contributions are not maintained in the long run by their authors). 

Will be happy to assist (and if needed, we can adjust the internals for sure).
