### ISSUE TITLE
SqlHighlighter and MongoHighlighter should honor NO_COLOR env var

### ISSUE THREAD

**Issue by mercuriete** [mikro-orm/mikro-orm#1909]
https://no-color.org/

**Is your feature request related to a problem? Please describe.**
Problem: As a devops deploying on AWS I want to log without colors

**Describe the solution you'd like**
All highlighters should honor to the NO_COLOR environmental variable and make the output consistent to other libraries

**Actual Behaviour**
when using mikroorm inside nestjs framework, nestjs output is honoring NO_COLOR env var but mikro-orm is not.
It would be nice to support this feature.

** Proposal **
switch to NullHighlighter automatically when env var is present

thanks.

**Comment by B4nan** [comment]
Coloring is handled via `ansi-colors`, maybe it would be better to address it there? You can already disable coloring via `FORCE_COLOR=0`.

Because this is not just about highlighters, as those are only for the actual queries, but the coloring also happens in other places (we log more than just queries).

**Comment by mercuriete** [comment]
I just saw that there is already an issue on ansi-colors

https://github.com/doowb/ansi-colors/issues/46

that project is not updated lately so not sure if that is abandoned or not.

**Comment by Langstra** [comment]
Perhaps a good idea to add this to the documentation of MikroORM. I looked through the documentation of ansi-colors and could only find it in code (took a quick look).
