### ISSUE TITLE
cant set null

### ISSUE THREAD

**Issue by stephen-dahl** [mikro-orm/mikro-orm#1931]
**Describe the bug**
```
setting null does not persist if that field was not loaded. setting truthy values do persist on unloaded fields.
```

**To Reproduce**
```
const em = getMysqlEntityManager();
const row = await em.findOne(
	Table,
	{ id: 52726 },
	{ fields: ["id"] }
);
if (!row) throw new Error('not found');
wrap(row).assign({title: undefined}) // or null;
// AS WELL AS 
// row.title = undefined
await em.flush();
return row;
```
we are working around this by adding all update keys to our fields list

**Expected behavior**
title to persist

**Versions**

| Dependency | Version |
| - | - |
| node | 16.1.0 |
| typescript | 4.2.4 |
| mikro-orm | 4.5.5 |
| mysql | 4.5.5 |

**Comment by B4nan** [comment]
This can't work, because you are selecting just the `id` field. There is no difference so change set tracking cannot be triggered. Either select that field you want to change, or use `nativeUpdate()` (or a QB):

```ts
const row = await em.findOne(
	Table,
	{ id: 52726 },
	{ fields: ["id", "title"] }
);
if (!row) throw new Error('not found');
wrap(row).assign({title: undefined})
await em.flush();
```

This should work just fine with null too, as well as when assigning directly to the property.
