### ISSUE TITLE
`null` values in unmanaged columns break relation propagation

### ISSUE THREAD

**Issue by oliversalzburg** [mikro-orm/mikro-orm#1955]
**Describe the bug**
Consider a 1:1 relationship `Author` → `Post` where the FK is stored in the `Author` entity (column `post` pointing to the post) and the `Post` entity has the inverse relation modelled on it for easy access. If, for whatever reason, the `post` table contains an `author` column, Mikro will interpret this during loading of the entity, even though the FK *must* come from the `author` table.

Due to the change introduced to fix #1872, this has the result that the entire 1:1 relationship is lost on load if the `author` column in the `post` table is `null`.

**To Reproduce**
I found no easy way to build a test that showcases this, as it relies on columns that aren't created through MikroORM.

**Expected behavior**
Either Mikro selects only known columns from the underlying table or filters out foreign columns after the `SELECT *` operation. Although the former seems to make more sense from a performance perspective.

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | 14.17.0 |
| typescript | 4.3.4 |
| mikro-orm | 4.5.6 |
| your-driver | postgresql |

**Comment by B4nan** [comment]
This is the problem you mentioned on slack, right? Hard to call this a bug, for me this is wrong entity definition. If you want to have the FK on both ends, you should use 2 owninig properties and handle the values yourself instead of using the propagation of bidirectional relations.

Anyway, this feels really not actionable, as you did not provide any code snippet. Without a test case, there is no bug 🤷 

So if you want to change something, provide a test case please. If you can't build a test case, you should not create an issue :] But this really does not feel that "impossible to test".

> Either Mikro selects only known columns from the underlying table or filters out foreign columns after the SELECT * operation. Although the former seems to make more sense from a performance perspective.

You should define all the properties, otherwise schema generator will try to drop the extra columns.

Btw why don't you define the (other) property as lazy? That might probably do exactly what you want (omit it from the select clause).

**Comment by oliversalzburg** [comment]
Yes, this is what I mentioned on Slack. I assumed GH would be a better place to discuss it.

Of course, you're right. This can be tested. I just spent a couple of hours troubleshooting this issue and trying to create a test with the existing test setups in the MikroORM code base that I'm familiar with, only to realize that the problem is a column that isn't known to MikroORM and I didn't see how to progress further at that point.

Before I argue one way or the other, I should really evaluate your suggestions. Thank you very much for the prompt reply.

I just want to note that we do not make use of MikroORM's schema generator or migrations at all. We model and maintain the database schema through another solution, as we have to facilitate other applications that do not use MikroORM.

**Comment by oliversalzburg** [comment]
You're right. There's really no cause for action here. This must be fixed in our code. Sorry for the noise.
