### ISSUE TITLE
CLI: Use `ts-node` on demand based on file extension

### ISSUE THREAD

**Issue by jahudka** [mikro-orm/mikro-orm#1957]
If I set `useTsNode` to `true` in `package.json`, then MikroORM will attempt to register `ts-node` before consulting the list of config file paths. This means that I can either enable `ts-node` and then I'll need to have `ts-node` available on the production server in order to be able to run migrations, or I need to disable `ts-node` and always build my application in development prior to running the MikroORM CLI so that the `.js` version of the config file is available.

I don't know if this is possible, but I think it'd be great if I could just omit the `useTsNode` option and have the CLI decide whether `ts-node` should be used or not based on the extension of the first config file from the list which exists.

**Comment by B4nan** [comment]
> I don't know if this is possible, but I think it'd be great if I could just omit the useTsNode option and have the CLI decide whether ts-node should be used or not based on the extension of the first config file from the list which exists.

The list of files is defined in package.json just like `useTsNode` flag, so how would that be different? 

It already works like this, the first file from the list is taken, without `useTsNode` enabled the TS files are ignored from that list. If you deploy only JS files to production, the JS config will be used (as the TS won't be there) so there is no need for `ts-node`. Maybe we could just wrap the `registerTsNode` method in try/catch block and print a warning instead of hard failure.

Or we could allow overriding of `useTsNode` via the config itself (`tsNode: boolean`), to disable this behaviour for the CLI too, so you would just add `tsNode: false` to the production config.

**Comment by jahudka** [comment]
Unless I'm mistaken, this is how it works currently:

- `useTsNode: true` → `ts-node` is always registered, all files in `configPaths` are tried
- `useTsNode: false` or not specified → `ts-node` is never registered, only `*.js` files in `configPaths` are tried

So: in development, I want to set `useTsNode` to `true` and have my source `.ts` file first in the list. That works as expected. But then I make a production build on the CI server, run `npx mikro-orm cache:generate` to get entity metadata cached and then `npm prune --production` to get rid of dev dependencies, which include `ts-node`. Now the Mikro ORM CLI stops working, because it's attempting to register `ts-node`, which isn't available anymore. When I change the config in `package.json` to not enable `ts-node`, the CLI works as expected in that environment, but without `useTsNode: true` it doesn't work in my local development environment where the `.js` file isn't built and the `.ts` file is ignored without `ts-node`.

This means I need to either:
 - have a different `package.json` in different environments, or
 - ditch the built-in MikroORM CLI and write my own wrapper

Neither of these options sounds very attractive to me, which is why I propose that when `useTsNode` isn't specified at all the MikroORM CLI could default to `true` if the first available config file from the list is a `.ts` file and `false` otherwise. My config in `package.json` would then look like this:

```json
"mikro-orm": {
  "configPaths": [
    "src/orm-config.ts",
    "build/orm-config.js"
  ]
}
```

In development the first file is available, so the CLI would try to register `ts-node` and succeed, because in development `ts-node` is available. In production the first file would not be available, but the second one is, and so the CLI would use that, but it wouldn't even try to register `ts-node`, because the config file is a `.js` file.

**Comment by jahudka** [comment]
> Or we could allow overriding of useTsNode via the config itself (`tsNode: boolean`), to disable this behaviour for the CLI too, so you would just add `tsNode: false` to the production config.

That wouldn't work because the config file is only loaded _after_ `ts-node` is already registered I [think](https://github.com/mikro-orm/mikro-orm/blob/c0a1c7602f66762f4516abb3787883c9b71cf0d5/packages/cli/src/CLIConfigurator.ts#L24)..

**Comment by B4nan** [comment]
> Unless I'm mistaken, this is how it works currently:

Yes, that's what I am talking about. And as I said, if we wrap the `registerTsNode` method in try/catch block and just print a warning when ts-node is not available, we should be just fine, as things will fail only if there is a TS file and no ts-node. 

> That wouldn't work because the config file is only loaded after ts-node is already registered I think..

Yeah, right, chicken and egg. The problem is that we might also need ts-node for entity definitions, or migrations. It's not just about config file. Also the rest of the app does not have the information whether we are running from CLI or not. 

Using the `try/catch` seems like the easiest solution.
