### ISSUE TITLE
em.create() initializes all entity properties with explicit `undefined` values

### ISSUE THREAD

**Issue by calvinwyoung** [mikro-orm/mikro-orm#1984]
**Describe the bug**
Suppose I have a model that looks like this:

```typescript
class Foo {
  @Property({ columnType: 'text' })
  name: string;

  @Property({ defaultRaw: 'now()', nullable: false })
  createdAt: Date;
}
```

In previous versions of mikro-orm (around 4.2.3), using `em.create(Foo, { name: 'foo' })` would create the following entity:

```
{
  name: 'foo'
}
```

I recently upgraded to v4.5.6, and now the behavior seems to have changed such that this entity is created instead:

```
{
  name: 'foo'
  createdAt: undefined
}
```

Was this change intentional? I can't quite seem to find when or why this changed. The reason this is significant is that the current behavior will attempt to persist a `NULL` value to the `createdAt` column, which could trigger a not-null constraint exception in the case where the user expects the database to provide a default value (i.e., via `@Property({ defaultRaw: 'now()', nullable: false })`).

**Expected behavior**
I would expect `em.create` to **not** explicitly populate entity properties that weren't specified.

**Versions**

| Dependency | Version |
| - | - |
| node | 15.12 |
| typescript | 4.3.4 |
| mikro-orm | 4.5.6 |
| your-driver | @mikro-orm/postgres@4.5.6 |

**Comment by B4nan** [comment]
Definitely nothing intentional, but I can't reproduce it, neither on 4.5.6, nor on master.

**Comment by calvinwyoung** [comment]
@B4nan Thanks for the very quick response. So to be clear, your master branch would still produce `{ name: 'foo' }` (i.e., without the explicit `undefined` values)?

**Comment by B4nan** [comment]
Not just master branch, 4.5.6 too. Tried it with the realworld example app after upgrading to 4.5.6. Ideally provide a failing test case or executable repro, might be some other detail or something configuration specific.

**Comment by calvinwyoung** [comment]
Ah yes you're right, it definitely has something to do with my specific configuration. When I downgrade from typescript 4.3.4 -> 3.9.7, this issue goes away. I'll close this issue for now, and can follow up if / when I figure out the root cause for this issue.

**Comment by volo-maslow** [comment]
Looks like the issue still exist, I've faced with it too, and not sure if it's related to environment (will also check at another laptop).

In my case I had a default value in SQL, and non-nullable column.

Guess it's not an issue for MySQL because it can handle nulls at inserts, however, Postgres isn't so flexible in this question (https://www.postgresql.org/docs/current/sql-insert.html#id-1.9.3.152.9).

I've also checked with reflect-metadata and the issue is still there.

Repo: [https://github.com/volo-maslow/mikro-orm-1984](https://github.com/volo-maslow/mikro-orm-1984)

Temporarily fixed it by adding an extra check to the `@mikro-orm/knex->QueryBuilderHelper.ts@processData` replacing all undefined variables with postgres 'default' statement.

<details>
<summary>JS file dirty fix</summary>

```JavaScript
if (data[k] === undefined && (prop.nullable === false || prop.nullable === undefined) && (prop.default !== undefined || prop.defaultRaw !== undefined)) {
                data[k] = this.platform.usesDefaultKeyword() ? this.knex.raw('default') : undefined;
            }
```
</details>

**Comment by B4nan** [comment]
This is not really about pg vs mysql, when I was trying to reproduce this, the `em.create()` did not produce the `undefined` props at all. I still cannot reproduce it in the ORM tests, but I am with the repository you provided.

After looking a bit deeper, I see the problem with your repo is that you target `ESNext`, and due to this, when you create new instance of a class, all the properties gets initialized to `undefined` even tho you are not defining any intializers for them. 

```ts
console.log(new OrganizationEntity());

// prints with ESNext
OrganizationEntity {
  organizationId: undefined,
  name: undefined,
  description: undefined,
  isDeleted: undefined,
  createdAt: undefined
}

// prints with ES2021
OrganizationEntity {}
```

Don't ask me why ¯\_(ツ)_/¯

**Comment by volo-maslow** [comment]
Thank you, @B4nan. This is definately configuration-related issue, caused by `useDefineForClassFields` TypeScript compiled option. 

Initially TS team built it before the spec was done, and now they changed the behaviour, spec says that undefined values are initial behaviour Ref: [(TS Docs)](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#the-usedefineforclassfields-flag-and-the-declare-property-modifier)

Looks like ESNext has this set to true by default. The fix is just do disable it in tsconfig.json:
```Json
{
  "compilerOptions": {
    "useDefineForClassFields": false,
  }
}
```

I guess it could find it's place somewhere in MikroORM docs.

**Comment by B4nan** [comment]
> I guess it could find its place somewhere in MikroORM docs.

PR welcome, at least a note in the FAQ page would be good. 

We could also fix this internally, if this will become the next default in a year, we will need to anyway.

**Comment by calvinwyoung** [comment]
Per your request, I just opened a PR to address this in the FAQ (#2441). Hopefully this helps future developers!
