### ISSUE TITLE
Stale / Not up to date data coming from entity manager find with cache globally disabled.

### ISSUE THREAD

**Issue by woltob** [mikro-orm/mikro-orm#2020]
**Describe the bug**

We have the following function that pulls data from the database (example here, was observed in other functions as well).

```
async findAllActive(): Promise<Availability[]> {
    const availabilities = await this.em.find(
      Availability,
      {
        startTime: {
          $lte: new Date(),
        },
        $or: [
          {
            endTime: null,
          },
          {
            endTime: { $gte: new Date() },
          },
        ],
      },
      { populate: ['user'], refresh: true, cache: false },
    );
    return availabilities;
  }
```

Without the refresh: true, cache: false setting it would randomly return stale data (not changed, although the database was changed), even in production. Caching is disabled in the configuration (  ...,  cache: { enabled: false } ).

What causes this behavior? We spent hours on looking for bugs until we noticed that the data from the API is not up to date, even though the database has new values.

**Stack trace**
```
...
```

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Additional context**

**Versions**

| Dependency | Version |
"@mikro-orm/cli": "^4.5.6",
"@mikro-orm/core": "^4.5.6",
"@mikro-orm/nestjs": "^4.2.0",
"@mikro-orm/postgresql": "^4.5.6",
"@mikro-orm/reflection": "^4.5.6",

Running NestJS on Node

{
  'priojet-backend': '0.6.0',
  npm: '6.14.11',
  ares: '1.16.1',
  brotli: '1.0.9',
  cldr: '37.0',
  icu: '67.1',
  llhttp: '2.1.3',
  modules: '83',
  napi: '7',
  nghttp2: '1.41.0',
  node: '14.15.5',
  openssl: '1.1.1i',
  tz: '2020a',
  unicode: '13.0',
  uv: '1.40.0',
  v8: '8.4.371.19-node.18',
  zlib: '1.2.11'
}

**Comment by B4nan** [comment]
You need to use fresh fork for each request. This is not cache, this is identity map. Result cache is disabled by default. 

https://mikro-orm.io/docs/identity-map#request-context

https://mikro-orm.io/docs/installation#request-context

**Comment by woltob** [comment]
Okay thanks. 

We still haven't figured out how getting a fresh Entity Manager per request context is possible using NestJS and Apollo GraphQL.

What I do before every request now is:

const em = this.em.fork(true);

and then setting cache to false and refresh to true.

There is no way around it. Can I disable Identity Map globally? I see no benefit for this in a fast-paced express (NestJS is based on express by default) application.

To be very honest here, it was just causing us tremendous headaches and questioning about using Mikro-ORM in production (going live soon). It would be pretty awesome if everything would be managed "magically" in in the background so that we can even go back to using EntityRepository etc. 

Any hints on that one?

Thanks you so much.

**Comment by B4nan** [comment]
I can see how it can cause headaches if you dont have the request contexts properly set up. If you need to pass `refresh: true`, it is definitely not done properly. If you use some kind of DI container or global instance, it is mandatory to use the `RequestContext` helper via middlewares or `AsyncLocalStorage` equivalent. Otherwise you can also fork manually. There are example repositories for that, I already pointed to those in the other issue you created (#1835). 

> There is no way around it. 

This is simply not true. Maybe if you provide actual repro, I could help you, even tho I am not using GQL myself, so I believe people in the other issue would be better target. 

> It would be pretty awesome if everything would be managed "magically" in in the background so that we can even go back to using EntityRepository etc.

That is exactly what `RequestContext` helper is for. You create the context via middleware, and it will be automatically used behind the scenes while you will work with the global instances of EM or repositories. Note that I already pointed out it the other issue to [one specific requirement with Apollo](https://github.com/mikro-orm/nestjs/issues/22).

**Comment by B4nan** [comment]
Forgot to mention it is actually possible to disable identity map, but it makes sense only for read purposes:

https://mikro-orm.io/docs/entity-manager/#disabling-identity-map-and-change-set-tracking

It will basically create the fork for each call, use it to load the entities, clear it and return it back to you. The entities will be still connected properly (Author.books will have references to Book.author and vice versa, identity map will work for those loaded in one query).

But you should prefer to setup the request context, otherwise you will keep fighting the ORM.
