### ISSUE TITLE
"MetadataError: Metadata for entity X not found"

### ISSUE THREAD

**Issue by intmainvoid** [mikro-orm/mikro-orm#2067]
**Describe the bug**
When running an embedded transaction from databaseTwo inside the transaction from databaseOne, Mikro ORM throws a `MetadataError: Metadata for entity X not found` error.

```
    ...
    await orm1.em.clear();
    await orm2.em.clear();

    await orm1.em.transactional(async () => {
      await orm2.em.transactional(async () => {
        const a2 = orm1.em.create(A, { id: '1', name: 'Z' });
      });
    });
    ...
```

**Stack trace**
```
    MetadataError: Metadata for entity A not found

      202 |
      203 |   static missingMetadata(entity: string): MetadataError {
    > 204 |     return new MetadataError(`Metadata for entity ${entity} not found`);
          |            ^
      205 |   }
      206 |
      207 |   static conflictingPropertyName(className: string, name: string, embeddedName: string): MetadataError {

      at Function.missingMetadata (packages/core/src/errors.ts:204:12)
      at MetadataStorage.get (packages/core/src/metadata/MetadataStorage.ts:77:27)
      at EntityFactory.create (packages/core/src/entity/EntityFactory.ts:35:32)
      at SqlEntityManager.create (packages/core/src/EntityManager.ts:558:36)
      at tests/issues/GH2067.test.ts:57:28
      at packages/core/src/EntityManager.ts:400:27
      at SqliteConnection.transactional (packages/knex/src/AbstractSqlConnection.ts:47:25)
      at tests/issues/GH2067.test.ts:56:7
      at packages/core/src/EntityManager.ts:400:21
      at SqliteConnection.transactional (packages/knex/src/AbstractSqlConnection.ts:47:19)
      at Object.<anonymous> (tests/issues/GH2067.test.ts:55:5)
```

**To Reproduce**
Test case found to reproduce the issue can be found in [this PR](https://github.com/mikro-orm/mikro-orm/pull/2123).

**Expected behavior**
Both transactions - the embedded one and the enclosing one - should succeed without throwing an exception.

**Additional context**
-

**Versions**
This test passes in MikroORM v4.0.7 and fails in v4.5.7 and the current master branch commit hash (`a73c4e092138d95fe85cebc5b6c87e94746286ca`)

| Dependency | Version |
| - | - |
| node | v14.17.3 |
| typescript | 4.3.5 |
| mikro-orm | 4.5.7 & latest master |
| your-driver | N/A |

**Comment by intmainvoid** [comment]
Actually, although this doesn't work in 4.5.7, it appears to be working in the current `master` branch `0b9e6a22f10`.

**Comment by intmainvoid** [comment]
Reopening as was able to reproduce in master

**Comment by B4nan** [comment]
This does not make any sense to me, why would you have two instances of the ORM? Inside explicit transaction you are bound to the EM that started it via the `TransactionContext` class, so you can use repositories from DI container, but still work with the right EM fork.

If you don't want this behaviour, you need to use `em.begin/rollback/commit` instead of `em.transactional`.

Btw in your test, you are awaiting `em.clear()` (sync method), but not `orm.close()` (async method).

**Comment by intmainvoid** [comment]
> This does not make any sense to me, why would you have two instances of the ORM?

Because the application connects to multiple databases at the same time. The current solution uses one ORM instance for each database it connects to. Is this not the correct approach?

The goal is to write to both databases in turn and commit to both at the end. This reduces the chance of the data in both databases getting out of sync.

**Comment by B4nan** [comment]
Sorry, I guess it is the right approach if you need two or more databases. Anyway, as mentioned, the behaviour is expected due to the tx context I mentioned. If you use `em.begin/commit/rollback` explicitly, you can get around it, the tx context is established only with `em.transactional`.

```ts
await orm1.em.begin();
await orm2.em.begin();
const a2 = orm1.em.create(A, { id: '1', name: 'Z' });
orm1.em.persist(a2);

try {
  await orm1.em.commit();
  await orm2.em.commit();
} catch (e) {
  await orm1.em.rollback();
  await orm2.em.rollback();
}
```

Btw the reason why there is this tx context is exactly so you can write the code as you did - without the explicit usage of inner EM. Inside the transactional callback, you get an EM fork to work with in the parameter, you should not use the outer one. 

This is the PR that introduced it https://github.com/mikro-orm/mikro-orm/pull/959

Before this PR you would have to use the inner EM:

```ts
await orm.em.transactional(async (innerEM) => {
  // we can't use `orm.em.getRepository(Author)` here, as it does not hold current tx context
  const a = await innerEM.getRepository(Author).findOneOrFail(god1);
  a.name = 'abc';
});
```

**Comment by intmainvoid** [comment]
> If you use em.begin/commit/rollback explicitly, you can get around it

Using this technique, how would select and update within the context of a single transaction? The following test fails as the rollback doesn't have any effect (no doubt because the mutation was not part of the transaction).

```Javascript
const a2 = orm.em.create(A, { id: '1', name: 'Z' });
await orm.em.persist(a2).flush();
...
orm.em.clear();

// Start the transaction
await orm.em.begin();
const inside = await orm.em.getRepository(A).findOne('1'); // select the record
inside!.name = 'Y'; // update the record

// Attempt to rollback the transaction
await orm.em.rollback();

// Retrieve the existing record again from the DB outside the context of the transaction
const outside = await orm.em.getRepository(A).findOne('1');

// Expect throws an error as outside!.name === 'Y' (not 'Z') demonstrating that the above rollback did not have the desired effect.
expect(outside!.name).toBe('Z');
```

Here's a test that closer portrays what the solution does in practice:

```Javascript
test('GH issue 2067', async () => {

  const a1 = orm1.em.create(A, { id: '1', name: 'A' });
  const a2 = orm2.em.create(B, { id: '9', name: 'B' });
  await orm1.em.persist(a1!).flush();
  await orm2.em.persist(a2!).flush();

  await orm1.em.transactional(async (em1) => {
    await orm2.em.transactional(async (em2) => {
      const b1 = await em1.getRepository(A).findOne('1');
      const b2 = await em2.getRepository(B).findOne('9');
      b1!.name = 'AAA';
      b2!.name = 'BBB';

      /**
      * Once all the updates to both databases have been successfully completed, persist and flush
      * Otherwise, we'd throw an error and effectively abort the transaction(s).
      */
      await em1.persist(b1!).flush();
      await em2.persist(b2!).flush();
    });
  });
  const a3 = await orm1.em.getRepository(A).findOne('1');
  const b3 = await orm2.em.getRepository(B).findOne('9');
  expect(a3!.name).toBe('AAA');
  expect(b3!.name).toBe('BBB');
});
```

The above test passes on v4.0.7 and fails on master. Having the relative entity managers bound to their individual transaction contexts works well for this use case.

Thanks for linking the PR. I notice that [TransactionContext.ts](https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/utils/TransactionContext.ts) uses a static `AsyncLocalStorage` instance. Could we perhaps key the transaction context off of the id of the em? Something like this?:

`TransactionContext.ts`

```Javascript
...
/**
 * Creates new TransactionContext instance and runs the code inside its domain.
 */
static async createAsync<T>(em: EntityManager, next: (...args: any[]) => Promise<T>): Promise<T> {
  // const context = new TransactionContext(em);
  const context = { [em.id]: new TransactionContext(em) };

  return new Promise((resolve, reject) => {
    this.storage.run(context, () => next().then(resolve).catch(reject));
  });
}
...
```

Would this allow us to have multiple transaction contexts (one for each em instance at least)?

**Comment by B4nan** [comment]
Nope, that would not help, the problem is not in storing the EM in context, but rather in picking the right one back via `em.getContext()`. The whole point of the tx context is to bare the closest EM instance, and you do not want that. Only way around this is to not use it, which we could do conditionally - but keep in mind that would require you to use the forked EM instance from the parameter anyway - and it looks like that way things work fine. 

Or maybe if you would name your ORM instances, we could use that, just like we do with the `RequestContext` helper that does support multiple ORM instances. See this test: 

https://github.com/mikro-orm/mikro-orm/blob/master/tests/RequestContext.test.ts#L64

Although I am really not sure if it could work, it's just an idea.

> // Expect throws an error as outside!.name === 'Y' (not 'Z') demonstrating that the above rollback did not have the desired effect.

In master that test is passing, nothing is thrown. I know there was a bug in how the `RequestContext` or `Transaction ontext` worked in v4, I believe the fix is backported to v4, so it sounds weird it would behave differently. Either way if we do something about this, it will land in v5 only.

Also note that you don't have to persist managed entities (those retrieved from the database). And with `em.transactional()` there is no need to flush explicitly, as it will be always done at the end of the callback.

**Comment by intmainvoid** [comment]
> In master that test is passing, nothing is thrown

Yes, apologies, that code comment was left there in error. I've edited and removed it from the above test.

> and it looks like that way things work fine

Indeed. I've refactored the existing code away from using `.transactional` that is provided with MikroORM to use `begin()/commit()/rollback()`. I fact, I've built a `.transactional(...)` wrapper function on my DB object so only my DB class needs to change. The rest of the application stays largely the same. It all seems to work fine. It would be nice to see that supported natively in MikroORM at some point in the future though.

Thanks for your help.
