### ISSUE TITLE
Convert enum to varchar does not work with Postgresql

### ISSUE THREAD

**Issue by othierry-asi** [mikro-orm/mikro-orm#2077]
**Describe the bug**

String enums are converted to `text` SQL type in Postgresql while I want them to be converted to `varchar`. I tried to use `columnType` in `@Enum` decorator to force the SQL column type but it does not work.

My enum :

```
export enum ContentType {
  EXERCISE = 'EXERCISE',
  TRAINING = 'TRAINING',
  POLL = 'POLL',
}
```

My entity property :

```
  @Enum({
    columnType: 'varchar',
    length: 10,
    items: () => ContentType,
  })
  public contentType: ContentType;
```

And an extract of the generated schema using `npx mikro-orm schema:create --dump` :

```
, "content_type" text check ("content_type" in ('EXERCISE', 'TRAINING', 'POLL')) not null, 
```

I expected it to be :

```
, "content_type" varchar(10) check ("content_type" in ('EXERCISE', 'TRAINING', 'POLL')) not null, 
```

In my `package.json` :

```
    "@mikro-orm/cli": "^4.5.7",
    "@mikro-orm/core": "^4.5.7",
    "@mikro-orm/postgresql": "^4.5.7",
    "@mikro-orm/reflection": "^4.5.7",
```

Is this a bug ? Is there a way to workaround it ?

Thanks for any help !

**Comment by B4nan** [comment]
You could call this is a limitation of knex, as that is where the enum definition is built and where `text` type is hardcoded. In v5 we could get around it quite easily, but I don't see a need for it, `text` type should be preferred. 

https://stackoverflow.com/questions/4848964/difference-between-text-and-varchar-character-varying

Also note that with `columnType` you need to put the length in there, there is no postprocessing and `columnType` is always used as is, so it should be `columnType: 'varchar(10)` if something.

**Comment by B4nan** [comment]
Unfortunately the easy fix I had in my mind is far away from being easy. 

No plans to work on this, especially because there is no real benefit in it. See the StackOverflow post above for more information, in short both `varchar(10)` and `text` types are stored in the very same underlying database type. Thanks to the check constraint, it is impossible to put anything else that the enum values inside, so there is even no need for the max length, as that is inferred based on the enum items.
