### ISSUE TITLE
Improve docs re MikroORM.init

### ISSUE THREAD

**Issue by xshkut** [mikro-orm/mikro-orm#2118]
**Is your feature request related to a problem? Please describe.**
When I instantiate MikroORM, I cannot get `.em.createQueryBuilder`:
```
  const orm = await MikroORM.init({
    entities: entitiesList,
    type: 'postgresql',
  })

  orm.em.createQueryBuilder // Type Error: Property 'createQueryBuilder' does not exist on type 'EntityManager<IDatabaseDriver<Connection>>'
```

UNLESS I explicitly specify the `IDatabaseDriver` generic type argument:
```
  const orm = await MikroORM.init<PostgreSqlDriver>({
    entities: entitiesList,
    type: 'postgresql',
  })

  orm.em.createQueryBuilder // OK
```

There was no help to me both in the [DOCS](https://mikro-orm.io/docs/installation) and [README](https://mikro-orm.io/docs/installation)
 I have spent some time until found the solution [HERE](https://github.com/mikro-orm/mikro-orm/issues/1065#issuecomment-724707428)

**Describe the solution you'd like**
Would be good to have this aspect mentioned in the docs.

**Additional context**
BTW thanx for the ORM. It's simple and great!

**Comment by B4nan** [comment]
> There was no help to me both in the DOCS and README

Could be mentioned in other places too, but it indeed is in the docs.

https://mikro-orm.io/docs/faq#entitymanager-does-not-have-createquerybuilder-method
https://mikro-orm.io/docs/upgrading-v3-to-v4/#sqlentitymanager-and-mongoentitymanager

**Comment by xshkut** [comment]
https://mikro-orm.io/docs/faq#entitymanager-does-not-have-createquerybuilder-method
Am I supposed to use this?
```
import { EntityManager } from '@mikro-orm/mysql'; // or any other SQL driver package
const em: EntityManager;
const qb = await em.createQueryBuilder(...);
```
That `em` is not even instantiated. And the instantiation requires some arguments.

As an option, I could do a trick:
```
const qb = await (orm.em as unknown as EntityManager).createQueryBuilder(...);
```
But that definitely sucks

**Comment by B4nan** [comment]
> That em is not even instantiated. And the instantiation requires some arguments.

You are missing the point of that example. The whole "problem" is just in typings, the actual EM instance will always be correct and will have the right methods. You just need to be explicit about this so TS will understand it.

**Comment by xshkut** [comment]
> You are missing the point of that example. The whole "problem" is just in typings, the actual EM instance will always be correct and will have the right methods. You just need to be explicit about this so TS will understand it.

Exactly, everything will be ok in runtime, but not when compiling. The only right place to provide the type explicitly is `MikroORM.init<PostgreSqlDriver>` and that should be stated in the docs. The example from there is just confusing. It makes us inspect `.d.ts` files and create workarounds for type assertion.

**Comment by B4nan** [comment]
> The only right place to provide the type explicitly is MikroORM.init<PostgreSqlDriver> 

Not really, you are too concerned with the basic examples, in real world apps you should use a dependency injection container instead, or access the EM from a request context object, and work with the EM only. The places where you work with the EM and where you initialize the ORM are simply elsewhere, and you don't need to care about this when you initialize the ORM - you need to care about what type is the EM property you will be using. 

> The example from there is just confusing. It makes us inspect .d.ts files and create workarounds for type assertion.

Might be confusing to you, but you are the very first person complaining about the `init` call, so not that confusing in general I guess.

> It makes us inspect .d.ts files and create workarounds for type assertion.

How come?

**Comment by xshkut** [comment]
>The places where you work with the EM and where you initialize the ORM are simply elsewhere, and you don't need to care about this when you initialize the ORM - you need to care about what type is the EM property you will be using

I get your point. But this is rather DI frameworks' fault that they cannot directly bind the type of an `injecatable` source to the value being injected, so we should provide its type explicitly.

> you are the very first person complaining

Who opens an issue after having found the solution? :) I just wanted the docs to be consistent with the source code to help others to use the framework.

> How come?

What else am I supposed to do when having type errors on my code copied exactly from the docs?

Anyway, if you are not about to spend your time on this issue, I could do a PR if you wish

**Comment by B4nan** [comment]
> What else am I supposed to do when having type errors on my code copied exactly from the docs?

Pretty much no code in the docs is meant to be copy pasted and expected to run fine. The docs are not a tutorial, they show examples, often incomplete, highlighting just the specific part they talk about. Of course they should still make some sense.

Feel free to PR the docs, any help with that is highly appreciated. This problem is definitely not described well enough. One place that should definitely have this covered is https://mikro-orm.io/docs/usage-with-sql/

Don't forget to update both the [next version](https://github.com/mikro-orm/mikro-orm/tree/master/docs/docs) and [current one](https://github.com/mikro-orm/mikro-orm/tree/master/docs/versioned_docs/version-4.5).

**Comment by mwaeckerlin** [comment]
Having the same problem.

What is now the official solution for this issue?

The final solution is unclear to me, when following your conversation; and there is no explicit hint on this issue in the docs, just a sample as is, but without explicitly describing the pitfall, and how it is solved and why that way.

### Question

So let me formulate an explicit clear question, hoping for an explicit and clear answer, including sample code:

Do I have to explicitly import from a specific database-package, which taints the otherwise database type agnostic approach, or is there any better solution?

### Problem

So this fails (both, from `orm.em` and from `em`):
```
import {Injectable} from '@nestjs/common'
import {EntityManager, MikroORM} from '@mikro-orm/core'
import {Order} from '../orders/order.entity'

@Injectable()
export class ReportsService {
  constructor(
    private readonly em: EntityManager,
    private readonly orm: MikroORM,
  ) {}

  tradingReport(range: DateRange) {
    this.em.createQueryBuilder(Order) // Property 'createQueryBuilder' does not exist on type 'EntityManager<IDatabaseDriver<Connection>>'.ts(2339)

    this.orm.em.createQueryBuilder(Order)  // Property 'createQueryBuilder' does not exist on type 'EntityManager<IDatabaseDriver<Connection>>'.ts(2339)
  }
}
```

### Potential (but ugly) Solution

This works, but is very ugly, IMHO:
```typescrypt
import {Injectable} from '@nestjs/common'
import {EntityManager, MikroORM} from '@mikro-orm/postgresql'
import {Order} from '../orders/order.entity'

@Injectable()
export class ReportsService {
  constructor(
    private readonly em: EntityManager,
    private readonly orm: MikroORM,
  ) {}

  tradingReport(range: DateRange) {
    this.em.createQueryBuilder(Order) // works
    this.orm.em.createQueryBuilder(Order) // works
  }
}
```

Is there any better solution?

**Comment by B4nan** [comment]
I don't understand why you call this ugly, this is the correct solution. You won't get the driver-specific methods (like the QB factory) in any other way than importing from the driver package - because it does not exist in the core package.

**Comment by mwaeckerlin** [comment]
Ok, thank you for the clear and fast answer, that helps.

Ugly, because in our whole project, dependency to Postgres is reduced to the file `mikro-orm.config.ts` (and the `docker-compose.yaml` of course), but everything else is db-agnostic.

I like the concept of removing dependencies to specific tools from the code as much as possible, to have the flexibility to exchange them, when necessary. So this solution here just contradicts that paradigm. That's why it's at least ugly to my understanding.

**Comment by B4nan** [comment]
> but everything else is db-agnostic.

That's not entirely true, you want to use QB, and that's not something the core package knows, this on its own is an SQL-specific thing.

**Comment by B4nan** [comment]
It's funny how you call this ugly, to me it's a very elegant solution without any boilerplate or explicit passing of generics. Note that you can technically import from `@mikro-orm/knex` package as a common base of SQL drivers. It also reexports everything from the `core` package and contains the `SqlEntityManager` reexport (under `EntityManager` alias) like the driver packages. It does not contain the SQL-specific `MikroORM` reexport, that one is exclusive to the actual drivers.

**Comment by mwaeckerlin** [comment]
Yes, not completely, SQL based only, not MongoDB, etc.

We're trying to avoid  DB-specific approaches as much as possible, but yes, we limit to SQL. My personal concern towards NoSQL is: Missing standard; in general, I try to rather depend on standards (as SQL), not on specific implementations (as MariaDB, PostgreSQL, etc.)

I see, yes, `knex` is in fact a ore generic solution for my use case. Cool idea! Thank you.
