### ISSUE TITLE
Static checking of population

### ISSUE THREAD

**Issue by vimmerru** [mikro-orm/mikro-orm#214]
**Is your feature request related to a problem? Please describe.**

For the moment ```em::find(...)``` and ```em::find(..., { populate: ['something'] })``` return exactly the same entity types and compiler don't know was references populated or not.

We have the solution to explicitly define references https://github.com/mikro-orm/mikro-orm/blob/dev/docs/entity-references.md#better-type-safety-with-referencet-wrapper but this solution is partial as you don't know were the references populated or not. You can await all populated references that will not perform database querying, but if you just remember population you may release the code that will produce a lot of unexpected queries to production. Also it causes significant boilerplate.

It would be nice if ``em::find(..., { populate: ['something'] })``` will return mapped type with all populated fields de-referenced.

**Describe the solution you'd like**

Here is a very rough idea how to define types:

```typescript
class Reference<T> {
    unwrap<T>(): T {
        // implementation isn't important
        return undefined as any;
    }
}

type UnwrappedReference<T> = T extends Reference<infer U> ? U : T;

type PopulatedEntity<E, R extends keyof E> = {
    [k in keyof E]: k extends R ? UnwrappedReference<E[k]> : E[k] 
}

class Credentials {
}

class Organization {
}

class User {
    name!: string;
    credentials!: Reference<Credentials>;
    organization!: Reference<Organization>;
}

function populate<E, R extends keyof E>(entities: E[], ...fields: R[]): PopulatedEntity<E, R>[] {
    // implementation isn't important
    return undefined as any;
}

const users = [new User()];

const populated1 = populate(users, 'credentials');
const credentials1: Credentials = populated1[0].credentials;
const organization: Reference<Organization> = populated1[0].organization;

const populated2 = populate(users, 'credentials', 'organization');
const credentials2: Credentials = populated2[0].credentials;
const organization2: Organization = populated2[0].organization;
```

**Additional context**

Types i provided allows to populate only one level of references. There is no generic ts solution to populate at any level, but if we limit deepness of population to some meaningful value like 3-5 correct typing is possible.

**Comment by vimmerru** [comment]
> how to design the populate api to support nesting and maintain type safety?

I would prefer some monad-style population builder

```
const populated =await  new PopulateHelper([new Employee()])
    .populate('company', 'alliance')
    .populate('university')
    .exec();
```

> how will the solution for 3 levels depth look like?

Here is a proof-of-concept PopulateHelper typings for 2-levels. Any additional level is just one, but long line of code

```typescript
class Reference<T> {
    unwrap<T>(): T {
        // implementation isn't important
        return undefined as any;
    }
}

type UnwrappedReference<T> = T extends Reference<infer U> ? U : T;

type PopulatedEntity<E, R extends keyof E> = {
    [k in keyof E]: k extends R ? UnwrappedReference<E[k]> : E[k]
}

type PopulatedEntity2<E, R1 extends keyof E, R2 extends keyof UnwrappedReference<E[R1]>> = {
    [k in keyof E]: k extends R1 ? PopulatedEntity<UnwrappedReference<E[k]>, R2> : E[k]
}

class PopulateHelper<E> {
    constructor(entities: E[]) {
        /* doesn't matter */
    }

    public populate
        <R1 extends keyof E>
        (field1: R1): PopulateHelper<PopulatedEntity<E, R1>>;

    public populate
        <R1 extends keyof E, R2 extends keyof UnwrappedReference<E[R1]>>
        (field1: R1, field2: R2): PopulateHelper<PopulatedEntity2<E, R1, R2>>;

    public populate(field1: any, field2?: any): any {
        return undefined as any; // doesn't matter
    }

    public exec(): E[] {
        /* doesn't matter for typing */
        return undefined as any; // doesn't matter
    }
}

class Alliance {
}

class Company {
    alliance!: Reference<Alliance>;
}

class University {
}

class Employee {
    company!: Reference<Company>;
    university!: Reference<University>;
}

const employees = [new Employee()];

const populated = new PopulateHelper([new Employee()])
    .populate('company', 'alliance')
    .populate('university')
    .exec();

const alliance: Alliance = populated[0].company.alliance;
const university: University = populated[0].university;
```

> will this work with self-referencing?

It should work. There can be problem with populating inside collections, but i don't know is it possible in mikro-orm already or not.

**Comment by B4nan** [comment]
> There can be problem with populating inside collections, but i don't know is it possible in mikro-orm already or not.

Not sure what you mean? When you populate 1:m or m:n property, the whole collection will be populated (via one query per entity). You can also (with a little hack) load only the collection elements (for m:n), without populating them.

**Comment by vimmerru** [comment]
Not sure what you mean?

```typescript

class Picture {
}

class Book {
   picture: Collection<Pictures>
}

class Author {
   books: Collection<Book>
}
```

Can i now get an author with all books and their pictures loaded? Anyway it isn't problem from typings point of view, just one additional type case where collection will be converted into array.

**Comment by B4nan** [comment]
Sure, `em.find(Author, {}, ['books.pictures'])` will do it. It will fire 3 queries, one for authors, one for books, one for pictures.

**Comment by stephenh** [comment]
Fwiw/just my $0.02, but I don't personally consider this "type-awareness of loaded state based on `findXxx` parameters" to be that important.

The primary reason is that, in a large enough codebase, the "loading code" of "hey load objects x/y/z" (i.e. at the start of a request/endpoint) and the "processing code" of "okay, apply business logic and validation rules to objects x/y/z" are sufficiently decoupled (spread across different files / concerns / etc) that it shouldn't matter how the objects were loaded.

I.e. I worked in a very large Rails codebase, which used preload-style hints (i.e. `findOne(Author, ["books.pictures"])`, and it was a _nightmare_ of N+1s b/c the processing code was constantly triggering new/dynamic fetches (as requirements changed/etc.) that the "loading code" had no idea it was going to need.

Such that, IMO, these sort of loading hints are just best avoided all together. They give a false sense of security, and kind of work well-enough in the small, but invariably just don't scale.

A secondary reason is that if the TypeScript types are "upgraded" to exactly match the "loading hint", I wonder if that's really that useful, b/c only the code that is immediately coupled to this specific "loading hint" will work on it; i.e. if I have some generic business logic that works on `Author`, whether `Author` was loaded from endpoint1 or endpoint2 or endpoint3, I need that code to be `doSomething(author: Author)` and not `doSomething(author: AuthorWithEndpointOnesHints | AuthorWithEndpointTwosHints | AuthorWithEndPointThreesHints)`. I.e. code reuse gets much harder, out side of the immediate "this loading code and this processing code are directly coupled together", which I'm in general asserting is not that common in larger systems. (Although if it was `author: { name: string }` that is actually not that bad, thanks to TS's structurally typing.)

Instead, I think ORMs need to double-down on avoiding N+1s by doing either dataloader-style or optimistic-style fetching (i.e. don't use preload hints and wait until I do `await author.book`/`await book.publisher` but still do batched loads), i.e. lean on the framework/ORM to fundamentally solve the problem, instead of relying on the programmer to get their loading hints right.

(All that said, I'll readily admit there is a usability win for getting back `author.books[0].pictures[0]` all synchronously typed w/o promises, and if we still had to use callbacks, this would probably be a must have; but given we have promises now, and everyone is generally used to them, I assert it'd be more important for Mikro/an ORM to focus on framework-driven safe loading vs. programmer-driven safe loading, and the programmers should just be okay with promises b/c they're not that bad.)

And, granted, everyone has different opinions, so this might be considered a "must have", and if so that's definitely cool, Mikro supporting it doesn't mean I have to use it :-), but just thought I'd do a braindump given the comment in #145 about potentially coupling a v3 release to implementing this.

**Comment by B4nan** [comment]
> A secondary reason is that if the TypeScript types are "upgraded" to exactly match the "loading hint", I wonder if that's really that useful, b/c only the code that is immediately coupled to this specific "loading hint" will work on it; i.e. if I have some generic business logic that works on Author, whether Author was loaded from endpoint1 or endpoint2 or endpoint3, I need that code to be doSomething(author: Author) and not doSomething(author: AuthorWithEndpointOnesHints | AuthorWithEndpointTwosHints | AuthorWithEndPointThreesHints). I.e. code reuse gets much harder, out side of the immediate "this loading code and this processing code are directly coupled together", which I'm in general asserting is not that common in larger systems. (Although if it was author: { name: string } that is actually not that bad, thanks to TS's structurally typing.)

Very valid point. 

> All that said, I'll readily admit there is a usability win for getting back author.books[0].pictures[0] all synchronously typed w/o promises

This is still possible, you can use the `unwrap` method which is synchronous. It is kinda similar to type casting to `any` in typescript, as you are then responsible for the objects being loaded. 

> And, granted, everyone has different opinions, so this might be considered a "must have", and if so that's definitely cool, Mikro supporting it doesn't mean I have to use it :-), but just thought I'd do a braindump given the comment in #145 about potentially coupling a v3 release to implementing this.

I might have expressed it badly - I am not planning to postpone v3 release for this, but I would like to solve it during one of its feature releases (or possibly in v4 as part of bigger refactoring together with making `Reference` wrapped being the default way).

**Comment by darkbasic** [comment]
> A secondary reason is that if the TypeScript types are "upgraded" to exactly match the "loading hint", I wonder if that's really that useful, b/c only the code that is immediately coupled to this specific "loading hint" will work on it; i.e. if I have some generic business logic that works on Author, whether Author was loaded from endpoint1 or endpoint2 or endpoint3, I need that code to be doSomething(author: Author) and not doSomething(author: AuthorWithEndpointOnesHints | AuthorWithEndpointTwosHints | AuthorWithEndPointThreesHints)

That is easily fixable: it's just a matter of extending a base type with more specific types depending on how you populated your entity.

```ts
const match = await em.findOneOrFail(Match, {});
```

that would return type `Match` which extends type `AnyEntity`.

```ts
const match = await em.findOneOrFail(Match, {}, ['site']);
```

that would return type `Match & SiteProp` which extends type `AnyEntity`.

```ts
const match = await em.findOneOrFail(Match, {}, ['site, creator']);
```

that would return type `Match & SiteProp & CreatorProp` which extends type `AnyEntity`.

If you have some generic business logic that accepts a `Match` type you will also be able to pass a `Match & SiteProp` or a `Match & SiteProp & CreatorProp` types because `Match` is a subtype of those.

The point is: **how should the "generic" `Match` entity look like**?
The first thing which comes to my mind is treating OneToOne and ManyToOne props as the union type `AnyEntity | Reference`. That would work great, but will have the annoyance that you will have to narrow the `site` and `creator` props down like this:

```ts
if (isRef(match.site)) {
  // Reference
} else {
  // Entity
}
```

Another -probably better- idea is to make Entities extend the Reference API: that way if you have a reference you can use the Reference API and if you have an Entity you can **also** use the reference API. If, for example, you will call the async `load` method on an already populated prop it will simply return itself but with a different type attached, no query needed. The advantage would be that you won't need to narrow the type down with `if (isRef(prop))`: it will be a Reference and you can treat it as a reference, but you will still be able to pass `Match & SiteProp` without the need for further changes.
On the contrary, if you want to make less generic code and take advantage of already generated props simply require the `Entity & PropName` as argument and you won't need to use the Reference API.

I think that would be the best of both worlds and in theory should be easy to implement, unless https://github.com/microsoft/TypeScript/issues/13995 ruins the party.

**Comment by stephenh** [comment]
> `const match = await em.findOneOrFail(Match, {}, ['site, creator']);`
> that would return type Match & SiteProp & CreatorProp which extends type AnyEntity.

It's funny/coincidental that you say that: I have (~two months later) changed my prior-stated opinion on "meh just always code against the `async`/`await` `.load()` API and accept it as 'good enough' b/c it's always n+1 safe", because yeah, you guys are right, that gets tedious.

So I'm now doing basically exactly what you have here, with some slight variations (i.e. not literally `Match & SiteProp & CreatorProp`, but the idea is the same).

My "past-proof-of-concept-but-not-yet-in-production" approach is to have (using your `Match` example entity) `Match.site` be a `Reference<Site>` (i.e. not a `Site` directly) that only has a `.load(): Promise<Site>` API on it (so "default/generic Match" behavior is "you have to ask for `.site`/any collection/references to be loaded with an `await`), but if you use `em.populate(match, ...some hint...)` with a hint of `'site'` or `['site', 'creator'], or `{ site: "matches" }` populate hints, then the `Match.site` property you get back is type-intersected with a `LoadedReference<Site>` that extends `Reference<Site>` but adds a synchronous `.get` method.

So then you can pass this around, i.e. to `someBusinessLogic(matchWithSite: Loaded<Match, "site">)`, as a type to your various internal impl methods that can now (with the static guarantee that it's actually loaded) call `match.site.get` without the annoyance of `await`'ing every time it touches `match.site.get`.

See this test:

https://github.com/stephenh/joist-ts/blob/master/packages/integration-tests/src/EntityManager.populate.test.ts#L20

Here's a test doing multiple levels of load hints:

https://github.com/stephenh/joist-ts/blob/master/packages/integration-tests/src/EntityManager.populate.test.ts#L33

The mapped types that do this magic are here:

https://github.com/stephenh/joist-ts/blob/master/packages/orm/src/EntityManager.ts#L74

(Addressing my own original concerns from before: these loaded types, i.e. `Loaded<Match, "site">` are still considered a sub-type of the original `Match` type as far as TS is concerned, so methods that take the vanilla `Match` will still accept a `Loaded<Match, "site">` (but not the other way around, passing a vanilla `Match` into a method that wants a `Loaded<Match, "site">` will be a compile error). Also, in terms of my original performance/N+1 concerns from my bad experience with a large Rails app, all of the `populate` calls are themselves dataloader/batch-loaded so should be N+1-safe even if they happen "several layers down" in the business logic.)

**Comment by B4nan** [comment]
Started looking into this recently, sorry it took so long. 

Currently thinking about having `$` property added to the `Reference` interface dynamically that would serve as a getter for the real entity. 

Here is updated example from @vimmerru:

```typescript
class Reference<T> {
    constructor(private entity: T) {
	  // or we could have it as a getter and throw when not initialized
      Object.defineProperty(this, '$', { value: entity });
    }
}

type LoadedReference<T> = Reference<T> & { $: T };
type UnwrappedReference<T, K> = T extends Reference<infer U> ? LoadedReference<U> : T;

type Loaded<T, R extends keyof T> = {
    [K in keyof T]: K extends R ? UnwrappedReference<T[K], K> : T[K] 
}

const users = [new User()];
const populated1 = populate(users, 'credentials');
const credentials1: LoadedReference<Credentials> = populated1[0].credentials;
const organization: Reference<Organization> = populated1[0].organization;

console.log(credentials1.$.email);
console.log(organization.$.name); // fails as not populated, so `$` is not there

const populated2 = populate(users, 'credentials', 'organization');
const credentials2: LoadedReference<Credentials> = populated2[0].credentials;
const organization2: LoadedReference<Organization> = populated2[0].organization;

console.log(credentials2.$.email);
console.log(organization2.$.name);
```

We already have a way to strictly type check the `populate` param (even nested) when provided as an object in v4:

```typescript
const author = await orm.em.findOne(Author, 1, { populate: {
  books: { publisher: { tests: true } },
} });
```

So the last bit is to do the magic and infer the right types in right places. Which is basically what @stephenh already did in the `joist-ts` - and it looks amazing! Hope you don't mind if I try to take some inspirations from there :] Btw the "lens" way for populate is also interesting.

**Comment by lookfirst** [comment]
I really dislike programming by symbols, but I do like that it can be effectively 'defined'.

**Comment by B4nan** [comment]
I was originally thinking about using the `get` method (its functionality could be implemented in `load` method) for this and having the dollar as alias, but that would be another breaking change and I must say I kinda like the dollar way (so I will most probably add it there anyway, the question is if we also have `get` method doing the same). 

But we are targeting v4, so we can definitely afford to make that BC :]

**Comment by darkbasic** [comment]
`get` looks more like a method than a getter to me: if we have to choose a non-symbol getter I think `unwrapped` sounds better.

**Comment by B4nan** [comment]
`get` would be a method for sure.

**Comment by stephenh** [comment]
> Hope you don't mind if I try to take some inspirations from there :]

Yep, np! I definitely got a big head start on joist-ts by liberally using mikro's ideas, `EntityManager`/`find` APIs, etc., so it's only fair for inspiration to be a two-way street. :-)

**Comment by B4nan** [comment]
Spent the whole weekend trying to implement this. I kinda succeeded, but the solution is eating CPU madly (constantly eating 1 core when I open the test case, and it never goes down) and some validation is now broken (populate param is no longer properly type checked). Even when I simplify pretty much everything (e.g. keeping only 1 out of 4 ways to define `populate`, not even trying nesting).

Starting to feel like this is not really doable without codegen :/ Will give it one more try during next week, but I am already behind schedule and don't want to postpone v4 for god knows how long because of this. 

It feels like the code itself is not the problem, but the inference is. TS goes mad without specifying the entity type explicitly. I guess it could work for repositories, where we already know the entity type...

**Comment by vimmerru** [comment]
@B4nan FYI on our projects we noticed that types inference for regular queries eats a lot of CPU already. Seems it is generic problem in typescript language server. For example, bug in Jetbrains https://youtrack.jetbrains.com/issue/WEB-43982

**Comment by vimmerru** [comment]
https://github.com/microsoft/TypeScript/issues/31248

**Comment by B4nan** [comment]
Looks like this was indeed an error of mine. Found a typo on the populate type that was causing the circular reference (in the nesting support that I was not even testing yet), weird that it failed to report it. Now it does perform much better (still a bit heavy initially, but no 100% cpu usage, its more like ~20% for a brief moment, then it goes down to ~3%).

**Comment by B4nan** [comment]
Just a brief update, this will require breaking changes in the entity definition, but the benefit should be much faster and more precise type inference. Namely I will need to require users to define a special property on every entity, pointing to its primary key:

```typescript
@Entity()
export class FooBar {

  @PrimaryKey()
  id!: number;

  // ...

  [PrimaryKeyProp]: 'id';

}
```

This would allow to simplify a lot of the typings so I believe it will result in faster inference (both for the "is this T an entity" and for "what is the PK of this entity T" problems). It will also replace the `PrimaryKeyType` symbol required for composite keys. Another benefit is that it will allow to get rid of the `PK` type argument in `IdentifiedReference` and `AnyEntity` (and in general be 100% precise when it comes to inference of the PK type).

**Comment by darkbasic** [comment]
As an end-user I feel this is a bit annoying, because you can easily end up forgetting about the symbols.
As a developer I also don't like the fact that you're somehow "denormalizing" things (you already know which one is the primary key from the @PrimaryKey decorator).

**But** on the other end we already have to declare symbols for composite keys, so at least we end up with a more consistent API.
I also experienced the issues about primary keys inference first hand when developing the Mikro-ORM Dataloader, so if it makes things easier that's a good plus.

Regarding collections I think they should be type safe as well, meaning we should know in advance if they're already loaded or not (if that's what you were asking),

**Comment by B4nan** [comment]
> As an end-user I feel this is a bit annoying, because you can easily end up forgetting about the symbols.

You cant forget, as TS will complain about the entity not being valid without the key. 

> As a developer I also don't like the fact that you're somehow "denormalizing" things (you already know which one is the primary key from the @PrimaryKey decorator).

That is not really true, as there is no way to infer those keys based on decorators unfortunately (none that I am aware of).

> Regarding collections I think they should be type safe as well, meaning we should know in advance if they're already loaded or not (if that's what you were asking),

The question was how to apply this type safety on collections. E.g. Should we remove the getItems() method and have it only on loaded collections? But that for me sounds like too bug breaking change...

**Comment by darkbasic** [comment]
I personally never used `getItems` because it doesn't enforce type safety, so I'm for dropping it on unloaded collections. Do you feel like there are any reasons to keep it? v3 had to have it because it completely lacked type safety, but getting rid of it personally sounds more like a feature rather than a breaking change.

**Comment by B4nan** [comment]
> Seems it is generic problem in typescript language server. For example, bug in Jetbrains youtrack.jetbrains.com/issue/WEB-43982

So it was again burning my cpu, tried to use vscode instead of webstorm to verify if it's about the type complexity or about webstorm itself. And it was blazing fast in vscode :D Updated to latest webstorm and it looks like now it's quite fast there as well...

**Comment by lookfirst** [comment]
@B4nan You might want to apply for the OSS license for Mikro and get the full IDEA Ultimate (free). I run the EAP versions (and use their [Toolbox](https://www.jetbrains.com/toolbox-app/) to manage things), so I'm always at the latest version. If you can't tell, I'm a huge fan of IDEA. =)

**Comment by B4nan** [comment]
I do have that license already, and I use the toolbox :] Do you think it's worth using full idea ultimate instead of webstorm for TS only projects? 

Btw it's still quite cpu intense in webstorm, tried EAP as well, looks even worse :D I guess I will need to simplify something. Tried using vscode for 5 minutes but that would be really hard downgrading :D Maybe it will be ok in normal projects, I am testing it on the EM tests that are >2kloc full of type inference...

**Comment by lookfirst** [comment]
Awesome... just wanted to make sure you're up to speed on the IDEA stuff.

Sorry about the speed stuff. =(

**Comment by darkbasic** [comment]
> Tried using vscode for 5 minutes but that would be really hard downgrading

It was the same for me, it took years but I'm glad I did. Bad type inference was one of the biggest reasons why I wanted to switch (the other one was ram consumption).

Is it slow with the simplified codebase with `PrimaryKeyProp` or with the more complex one?

**Comment by B4nan** [comment]
It's slow even after that change. I feel like the biggest problem here is still the `FilterQuery`. While it's great to have that kind of type safety it offers, it's simply too complex. 

It handles all the possibilities, like for a m:1 property, you can pass:
- the target entity instance
- primary key of that instance
  - this now checks also composite keys as well as PK from FK (shared PK)
  - for string keys it also allows to use regexp
  - it also allows to pass strings instead of object id in mongo
- array of primary keys
- hash with known operators

Then you can have the m:1 as a `Reference`, same with collection items (another level of nesting). And this all happens recursively. 

I see similar problem with the populate itself, as we allow multiple ways to define it:
1. `em.find(E, ..., ['a'])`
2. `em.find(E, ..., [{ field: 'a' }])`
3. `em.find(E, ..., { populate: ['a'] })`
4. `em.find(E, ..., { populate: { a: true } })`
5. `em.find(E, ..., { populate: { a: LoadStrategy.JOINED } })`
6. `em.find(E, ..., { populate: [LoadStrategy.JOINED, { a: true }] })`
7. `em.find(E, ..., { populate: [{ field: 'a' }] )`

Thinking about getting rid of 1., 2., 6. and 7. Getting rid of the `populate` vs `FindOptions` could help a lot with the inference of `T`, and it will be more readable anyway. It will also allow to remove lots of method overloads in EM and repository API. It will be quite huge BC, especially for me as I am using the "naked populate" param quite often :D But at leasts it will be all reported by TS compiler. 

I guess I will give that a shot first to see if it helps, as I don't want to make such BC if there would be no real impact on the performance.

**Comment by darkbasic** [comment]
Wow, did you really plan to maintain 7 different syntaxes? Why do we need so many in the first place? I'm all in for breaking changes if they help to get a cleaner, simpler API.

**Comment by B4nan** [comment]
There were only 2 ways up until now (v3) - 1. and 3., this all emerged from the joined strategy support and type safe populate param in general (as array of strings is not enough for nesting). It definitely needs cleanup :]

**Comment by B4nan** [comment]
Currently revising the `FilterQuery` type, I managed to "simplify" it and improve the autocomplete there, but it appears to be totally unusable in webstorm. Opened an issue so let's see if they can do something about it. 

https://youtrack.jetbrains.com/issue/WEB-46029

Current progress on this can be found in https://github.com/mikro-orm/mikro-orm/tree/type-safe-refs

It works quite well when it comes to the functionality and autocomplete, but as said, this is totally unusable in webstorm... Without the last commit (`FilterQuery` redesign) it was relatively usable, but the inference and intellisense on the `Loaded` type is still very CPU intense. 

I was kinda postponing this mainly because I knew how slow it was when I originally introduced the `FilterQuery` type and I saw this coming... On the other hand, I though this is caused by TS, not by webstorm (which apparently wasn't true).

**Comment by darkbasic** [comment]
How is it going? Did you hit any new roadblocker?

**Comment by B4nan** [comment]
Well, its slow and performance heavy, I feel like the additional breaking changes did not really help, so I would rather not do them (mainly the one with `FindOptions` everywhere). I also don't really like that `[PrimaryKeyProp]` thing... 

I am currently postponing this, wan't to finalize few other things first, as this was so far really a time eater (already spent around 2 weeks on this one). Also waiting for more stable webstorm eap builds, the latest one was still not very good experience (tried to use it for some time even not just in this project to verify).

Maybe I will try to make things a bit less precise, maybe we don't really need infinite levels of nesting correctly typed and having fixed level implementation would be sufficient (personally I do population for 2-3 levels max, usually it's just one). 

I also feel like the issue here might be the redesigned `Primary<T>` type, that is now really precise in what can be a primary key of given `T`, but that type itself was quite performance heavy. 

It's really hard to measure here, I am not aware of any tools for performance debugging of complex TS types, but when I just watched the history of CPU activity, it was easily visible that with the EAP it was much worse (even without those changes, browsing thru the dev branch), and the latest stable has that inference bug.

Will first try to spend some time working on filters/scopes, as that is the last big feature I would like to have in v4.

**Comment by B4nan** [comment]
I am currently more inclined to not merging it, it's still really slow, sometimes (quite often) the inference takes too long and TS just resolves to `any`. Working with the typed result is extremely slow, you basically don't get any intellisense so it kinda beats the purpose (yes, we still have strong type checking). Yes, its mainly about webstorm, but without this change it performs quite well. 

To have this working, I believe we really need something like `PrimaryKeyProp` - or we would have to drop the support for `IdentifiedReference` (its purpose is to be able to do `ref.id`, instead of `ref.get('id')` - the type knowns about the primary key name and type). joist does not need to handle this as the PK there is restricted to be under key `id` and composite keys are not even supported, which simplifies the problem a lot. (not talking about joist using codegen to get around some TS limitations.)

I will maybe try to do a version without `PrimaryKeyProp` and `IdentifiedReference`, requiring users to do `ref.get('id')` to access the PK. 

This is literally the last thing that holds me from merging #527 and shipping RC.

**Comment by B4nan** [comment]
Got an idea how to simplify this, allowing at least the first level population - handling the nesting appears to be the problematic/performance heavy bit, so I commented that out. Also instead doing the `PrimaryKeyProp` thing and precise inference of the actual PK type, I just return `Reference` instead of `IdentifiedReference` from the `Loaded` type - it turns out we don't really need to handle the PK properties as the `LoadedReference` type is merged with the actual type, that is correctly defined as `IdentifiedReference`.

For simplicity I will keep it working only on single level with the array syntax for now, rest will be ignored. Better to have this simplified version than nothing. 

This way there are no breaking changes (only the `Reference.get()` method that will now be available only on loaded references, like `$`) and it looks like it's fast enough to be merged. Will ship `alpha.10` hopefully later today so we can try it in the real world, I still hope that the actual performance in real life files (that are usually smaller than the ORM test files) will be much better.

**Comment by B4nan** [comment]
I did few more simplifications and also moved the testing code to its own file. It feels quite fast now, even with the nesting support enabled, so will ship that too. Let's see how it works, we can simplify later.

**Comment by B4nan** [comment]
Let's test it, `4.0.0-alpha.10` is out.

**Comment by CyriacBr** [comment]
@B4nan 

> We would still have to have something like $/get() even with codegen. Maybe you did not fully understand how it works - those are added on the runtime via TS, we need something like that to allow sync type safe path to the wrapped entity. Codegen would help only with preparing some types where we could easily infer what can be populated and what not - but that is working fine already without codegen (at least for Reference and Collection - we don't need it elsewhere).

Yeah maybe it's not clear for me. Isn't the issue here mostly about type checking? Making TS aware of the populated relationships, and mark everything else as `never` ?
Did the need evolve to support runtime checking as well? Because for a purely type checking solution there's no need to change what's actually returned by `findOne` and the likes.

**Comment by B4nan** [comment]
It is about being able to tell whether a `Reference` or `Collection` is loaded, at the TS level. 

```typescript
// here publisher is a (nullable) `Reference` and tags are `Collection`
const book1 = await orm.em.findOneOrFail(Book, 1, { populate: ['publisher', 'tags'] });
expect(book1.publisher!.$.name).toBe('Publisher 123'); // the `$` is available only on loaded references - if you do not have the `publisher` in populate param, it won't be there
expect(book1.tags.$[0].name).toBe('t1'); // same applies to collections, if we did not have `tags` in the populate hint, this would not type check
```

> Can you elaborate on that? Does that mean this could still work?

Yes, it still works the same, it's just about having the `$`/`get()` available on loaded references/collections. Nothing from the public API of collection changed, it's just about making TS aware of this information - whether its loaded or not - so you can write it typesafe (with the `$`). And if you do not use `Reference` wrapper, again, nothing changes, as this is only about `Reference`s and `Collection`s.

The thing is that with `Loaded` type, you can make sure other parts of your application also make sure that things are loaded where they should be. It's not really about the call site, where you clearly see the populate param. So in a service, you can define method that expects more than just `a: Author`, but a `Loaded<Author, 'books'>` - that way TS will warn when you try to pass an author without books populated.

**Comment by CyriacBr** [comment]
Alright it's fine by me then, thanks for clarifying.

**Comment by CyriacBr** [comment]
@B4nan 
However would like to clarify a bit about the codegen proposal. I see you're open to it as long as it's optional, but just to make sure we're talking about the same thing:

During entity discovery, the engine would generate typings from entities relationships, it's dead easy thanks to the metadata. This could generate all the possible populate outcomes. (As well as queries, if that's needed).
In my playground it gives something along those lines:

```ts
interface AuthorPopulateReturnType {
  books: {
    books: Collection<ScalarsOf<Book>>;
  } & ScalarsOf<Author>;
  address: {
    address: ScalarsOf<Address>;
  } & ScalarsOf<Author>;
  'books.tags': {
    books: Collection<
      ScalarsOf<Book> & {
        tags: Collection<ScalarsOf<BookTag>>;
      }
    >;
  } & ScalarsOf<Author>;
}
```

The generated `d.ts` would then override the methods of `EntityRepository` to return a `PopulateReturnType<Entity>` based of the generated outcomes:
![](https://i.imgur.com/lw0YT3P.png)

I think processing those types would be significantly faster for TS, especially if we generate queries types as well.

**Comment by B4nan** [comment]
In that example/screenshot - if `address` is m:1 relation, this way you would require it to be populated just to access the PK of that address - instead of disallowing the access totally, we should have something like `IdentifiedReference` there (so a type where you can access just the PK(s), as that is known without the full entity).

I am also not really bought on the dot syntax in populate - this could exponentially explode if you want to generate all the combinations, even if we set the limit to 3 levels, it could be really lots of code (it still might be ok, just something to test properly in a realworld app with let's say 10-20 entities). 

Also in that example you are using `AuthorPopulateReturnType` in the method definition, we need something generic (but that should be easy to achieve I guess).

In general, I would like to see this as a 3rd party thing, at least for the initial implementation. 

> I think processing those types would be significantly faster for TS, especially if we generate queries types as well.

Yeah most probably it would be faster as well as more precise, for sure. But you would have the overhead of generating the `d.ts` file on the fly, which for large codebase could be quite heavy itself - but again, something to test, it might work fine. 

In fact the current metadata caching mechanism is pretty similar to the codegen approach, the only unknown for me is how to use this generated file, as I really don't like to let users use hard imports to generated files - prisma uses a meta package for this, where the types are stored, this could be also doable I guess.

**Comment by CyriacBr** [comment]
Alright. It's a WIP on my `mikro-resources` package so for now yeah it'd be available as a 3rd party package. I will let you know once it's properly testable, although it's not really high on my priority list right now.
For sure the cached metadata was a genius move and there's a lot we can do with that.

**Comment by lookfirst** [comment]
Not sure if this helps you here, but TS4 seems to have some advances that might help...

https://devblogs.microsoft.com/typescript/announcing-typescript-4-0-beta/

**Comment by CyriacBr** [comment]
https://github.com/microsoft/TypeScript/pull/40336
This may help to type relation paths.
