### ISSUE TITLE
Schema generator creates json column type for int enums

### ISSUE THREAD

**Issue by vimmerru** [mikro-orm/mikro-orm#215]
Hi,

I use enums with int values a lot in my model and want to start use migration:create to simplify diffs creation. The problem is it always generates json type for such columns that i would expect to see as tinyint. As a result i always see big diffs in near-any table.

Is there any way to force the sql type for column?

**Comment by vimmerru** [comment]
Solved with @Property({ columnType: 'tinyint' }), but anyway it looks like a bug in schema generator.

**Comment by B4nan** [comment]
Missing feature, yeah, columnType is the corrent way to solve it now. Let’s keep this open as a feature request, I was planning to add native support for enums anyway.

**Comment by B4nan** [comment]
Fixed in `3.0.0-alpha.35`. Now when you define the enum via `@Enum` decorator, it will automatically read the enum values and decide the type, numeric enums being the default (so as long as you have numeric enums, you do not have to care about type discovery). 

https://github.com/mikro-orm/mikro-orm/blob/dev/docs/defining-entities.md#enums

If you have string enum and do not want to trigger the ts-morph discovery, you will need to provide `type` manually or pass `items` manually:

https://github.com/mikro-orm/mikro-orm/blob/dev/docs/deployment.md#fill-type-or-entity-attributes-everywhere
