### ISSUE TITLE
Executing `orm.em.flush` after `orm.em.removeAndFlush` restores the deleted entity

### ISSUE THREAD

**Issue by standup75** [mikro-orm/mikro-orm#2238]
**Describe the bug**
Executing `orm.em.flush` after `orm.em.removeAndFlush` restores the deleted entity

**Stack trace**
Set `debug:true`, here is the output
```
[query] begin
[query] delete from "reminder" where "id" in (79) [took 2 ms]
[query] commit
[query] begin
[query] insert into "reminder" ("body", "created_at", "date", "id", "subscriber_id", "updated_at") values ('test', '2021-09-28T15:51:42.000Z', '2021-09-28T13:30:00.000Z', 79, 7980, '2021-09-28T15:51:42.000Z') returning "id" [took 6 ms]
[query] commit
```

**To Reproduce**
```
  const reminders = await orm.em.find(Reminder, {});
  await orm.em.removeAndFlush(reminders);
  await orm.em.flush();
```

**Expected behavior**
The second flush should not do anything

**Versions**

| Dependency | Version |
| - | - |
| node |  16.4.2 |
| typescript | 4.2.0 |
| mikro-orm | 4.5.9 |
| your-driver | 4.5.9 |

**Comment by B4nan** [comment]
This is not enough to reproduce, at least provide the entity definitions, ideally a test case like in https://github.com/mikro-orm/mikro-orm/tree/master/tests/issues.

It is most likely because of some relation that still holds the reference to your just removed entity, it should be handled automatically if you have the relations set up correctly.

**Comment by standup75** [comment]
Here I created a test: https://github.com/mikro-orm/mikro-orm/pull/2253/files

**Comment by standup75** [comment]
I figured I was missing `orphanRemoval: true`

**Comment by B4nan** [comment]
Will be addressed in v5
