### ISSUE TITLE
Move TypeScript to devDependencies

### ISSUE THREAD

**Issue by Nekonyx** [mikro-orm/mikro-orm#231]
**Is your feature request related to a problem? Please describe.**
Judging by https://bundlephobia.com/result?p=mikro-orm, TypeScript weighs 78% (2.20 MB) of the entire package for no apparent reason, and that's a terrible thing to be honest. I checked the module myself by putting TypeScript into devDependencies and it worked without any problems. 

**Describe the solution you'd like**
Transfer TypeScript to devDependencies because it is only used during build.

**Comment by B4nan** [comment]
> for no apparent reason

The reason is ts-morph and its reflection. It is used for metadata discovery (aka when you call `MikroORM.init`) as well as in some CLI commands. 

> I checked the module myself by putting TypeScript into devDependencies and it worked without any problems.

I am pretty sure you did the test wrong - either you already had the cache generated, or you did install dev dependencies too (which is the default when you install deps on the package level afaik). Also, if you just moved typescript to dev deps, it won't help with anything, as ts-morph has direct dependency on it, so it will still be part of (normal) dependencies.

Personally I don't care much about this, as its backend package. In future, I can imagine ts-morph being optional (especially because you don't need it when you use vanilla JS only), but for that I'd like to convert this to monorepo and introduce multiple packages when one could simply omit (let's say) @mikro-orm/ts-reflection package which would depend on ts-morph. And that is really a store of future, there are more important things I want to work on now.
