### ISSUE TITLE
Use reflect-metadata instead of entity source files analyzing

### ISSUE THREAD

**Issue by ArtemDerevnjuk** [mikro-orm/mikro-orm#235]
`emitDecoratorMetadata` emits object type, param type, and return type, when `reflect-metadata` is loaded. The end-user just need to explicitly specify type. I don't see necessary to use `cache` and `ts-morph`. Please, correct me, if I missed something.

**Comment by B4nan** [comment]
Problem with `reflect-metadata` is that is does not work for all types correctly. You can get scalar types, but it won't work for anything more complex. All objects are listed just as `Object`. 

With `ts-morph`, I read all types, including object types, enums, even interfaces. Look at this entity:

```typescript
@Entity()
export class User implements IdEntity<User> {

  @PrimaryKey()
  id!: number;

  @Property()
  name!: string;

  @OneToOne()
  address?: Address;

  @ManyToMany()
  cars = new Collection<Car>(this);

  constructor(name: string) {
    this.name = name;
  }

}
```

Thanks to `ts-morph`, I am table to read type of `address` and `cars` properties.

**Comment by B4nan** [comment]
Hmm looking at it now, I see it works for user defined classes too. But the problem with native objects is still there (`Object` instead of `Date`). I know I had the same problem with reading type of `ObjectId` in mongo. 

Another problem is that you need to explicitly specify the type.

**Comment by B4nan** [comment]
Spent some time with this, I must say I am really confused as it actually works pretty good, including for `Date` and `ObjectId` types. I misread the compiled code tho, as it does not work with array items, all I get is `Array` as type, but that is still enough to infer the `json` column type.

The problem with `ObjectId` if I remember correctly was that you need to include the typings in your project - that was one of the reasons why I removed the `reflect-metadata` integration (it was there originally before I discovered `ts-morph`). 

Currently the only thing I cannot accomplish with it is to get the information about property being optional/nullable, plus the fact that one needs to explicitly specify the type even when you use the default value from which it can be easily inferred. 

I am thinking about wrapping this into new metadata provider implementation. One could choose from `ts-morph` and `reflect-metadata` implementations this way.

- `TsMorphMetadataProvider` that can read everything including the nullability, but has high impact on build time performance (and therefore needs caching)
- `ReflectMetadataProvider` that would require users to explicitly provide the type (either via TS, or via decorator attribute). This one would throw if not enough information was inferred. 

I am not sure which one to pick as a default, as v3 is ahead of us, we can afford to make breaking change like this. Also the `null`ability check was added in v3, so it would not be a BC to not have it in the final release. Still personally I like the `ts-morph` implementation as it allows to have simpler entity definition, and I don't care that much about the performance hit (it's there only during build time so it does not affect the app performance). 

To summarize, here is what `ts-morph` provider does allow on top of what `reflect-metadata` can do:

- reading types without having the typings included (`ObjectId` vs `Object`)
- reading property nullability/optionality (`prop?: string`)
- reading the inferred type when using the default assignment
  - this one allows to read the type from `created = new Date()`
  - it is also used for collections where you can define `col = new Collection<Ent>(this)` and I am able to read the `Ent` type
  - same applies to `IdentifiedReference<Ent>` type

I am leaning towards having `TsMorphMetadataProvider` as default, mainly because using the `ReflectMetadataProvider` will require users to explicitly provide additional information for the cases above when defining the entity - and all of that could be clearly documented in the docs about metadata providers (and linked from the installation page). I like the `ts-morph` way because you do not have to thing about any of this, it just works. On the other hand I do understand it can be a pain to set it up in the beginning when you do not fully understand how things work under the hood. 

There is also one problem with `reflect-metadata` - it introduces recursion issues when you define multiple entities (with circular dependencies between each other) in single file. Not a big deal, but another thing that should be clearly documented when one uses the `ReflectMetadataProvider`, so another reason for having `ts-morph` one as default.

WDYT @lookfirst @vimmerru @pepakriz?

Also linking the other issue about this: #227

**Comment by vimmerru** [comment]
@B4nan

In my opinion reflect-metadata limitations are small in comparison with complication that ts-morph adds. Main problem here is that ts-morph is 'foreign' technology for javascript ecosystem. Developer just don't know how it works, limitations and problems.

**Comment by lookfirst** [comment]
Just my humble opinion, nothing is set in stone. Happy with whatever happens.

* Definitely have both options.
* Default to TsMorph.
* Can release 3.0 without ReflectMetadata and can add that in later.
* Great docs for both.


@vimmerru I don't understand that comment at all. It is just code. There isn't any magic here.

**Comment by vimmerru** [comment]
@lookfirst 

> It is just code.

ts-morph is typescript compiler wrapped to library that performs analysis of typescript code AST on level and metadata generation for us. It isn't magic, but adds a lot of side effects:

- Slows down compilation
- Requires very strange caching that causes issues 
- If you just build and run dist it will fail with very strange error
- Adds strange limitations to files naming and structuring
- If don't use cache you will see high memory usage on program startup

They can be solved, but requires to much attention to documentation details.

**Comment by B4nan** [comment]
> Requires very strange caching that causes issues

Can you elaborate? Caching is now invalidated based on actual file contents, so in 99% I don't see how it could cause an issue (the 1% is for where you update mikro-orm as there might be some breaking change in what is cached and how).

Also I don't understand what is very strange about that. 

> If you just build and run dist it will fail with very strange error

Not really, as long as you have TS source files and `tsconfig.json` file next to the dist. Its just about misconfiguration if it does not work for you. 

> Adds strange limitations to files naming and structuring 

Also not really, you can name your entity as you wish, just use `entities` array instead of the directory based discovery.

> Requires to have typescript as runtime dependency that causes big bundle size and security issues

What security issues? 

> In case of modularization adds issues related to keeping typing with modules

What that this mean?

**Comment by vimmerru** [comment]
As i said all problems can be solved in some way, but people don't expect this problems as they are very unusual for typescript/javascript world.

> Can you elaborate? Caching is now invalidated based on actual file contents, so in 99% I don't see how it could cause an issue

For example, if i run code in dist it expects cache files to be named as entity.js, but in development runs entity.ts and i can't re-use cache.

> Not really, as long as you have TS source files and tsconfig.json file next to the dist. Its just about misconfiguration if it does not work for you.

I don't have any other js/ts library that requires such experience. I just don't expect this without internal knowledge. I don't see any information about this in https://github.com/mikro-orm/mikro-orm/blob/dev/docs/deployment.md. It just says use pre-build cache.

> Also not really, you can name your entity as you wish, just use entities array instead of the directory based discovery.

Also I need to know internals and limitations to make right decision. 

> What security issues?

It just bad practice to have any development or meta-programming tools as part of your production deployment. The same is so-so idea of usage globby based files searchers especially to load program parts.

**Comment by B4nan** [comment]
> For example, if i run code in dist it expects cache files to be named as entity.js, but in development runs entity.ts and i can't re-use cache.

Not true, you can generate production cache via CLI upfront if you want. `ts-node` cache is different from production one, that is by design. Also the cache would be normally generated as usually, as long as you have the TS files there as I already mentioned. 

> I don't see any information about this in https://github.com/mikro-orm/mikro-orm/blob/dev/docs/deployment.md. It just says use pre-built cache.

Try reading the whole page again, the first section says "This has some consequences for deployment of your application. **Sometimes you will want to deploy only your compiled output, without TS source files at all. In that case, discovery process will probably fail. You have several options:**". 

Also, it lists multiple possibilities, deploying pre-build cache is only one of them. One of those sections says **Deploy your entity source files**. Obviously the docs could be improved, but the main information is there. Docs about settings things up (e.g. `entitiesDirsTs`) are in installation section, that is not connected to deployment. 

> It just bad practice to have any development or meta-programming tools as part of your production deployment. The same is so-so idea of usage globby based files searchers especially to load program parts.

So first you say there are security issues and suddenly it becomes your personal opinion about something being best practice. I just do not agree with this. I can understand that you do not want to deploy TS files, but do not call that a security issue.

**Comment by lookfirst** [comment]
I currently use firebase cloud functions... only JS is deployed and i'm still waiting for the tool to tell me which properties i'm missing (apologies if i've missed it... i've been busy with other work), but the point is... javascript only deployments work just fine. 

Let's leave bike shedding out of the conversation and stick to facts please.

**Comment by vimmerru** [comment]
> Not true,

I am sorry ) I really don't want to make you angry As i said it doesn't mean that it is impossible. We have system in production for multiple month, but ts-morph **significantly** complicates deployment. This complication is really serious until you don't understand internals.

In general the difference between reflect-metadata and ts-morph is the following:

1. First way uses reflection provided by language itself. It is fast and don't need any intermediate files to store it. The only problem is some lack of language features that requires you to sometimes define additional meta information through decorators.
2. Second way uses 3d party reflection tool to generate missed data. It is slow and consumes a lot of memry for big models. As a result it requires cache to reduce memory consumption and lunch time. 

As i said the problem with approach 2 is problems with expectations and development/deployment experience especially for new developers. I expect that popularity of mikro-orm will grow a lot next month and it may cause a lot of headache for you.

I already see multiple tickets about ts-morph replacement or question why typescript is in deplpyment section. 

> So first you say there are security issues and suddenly it becomes your personal opinion about something being best practice. 

There is no out-of-box exploit and you can't call it 'issue', but It obviously opens new ways for attacks.

**Comment by vimmerru** [comment]
In general i just want to suggest approach 3:

1. Use reflect-metadata as the only way to collect model metadata
2. Add cli command based on ts-morph that will statically check and auto-fix model.

I believe it will provide the best user experience.

**Comment by B4nan** [comment]
Let's see how it works. Published `3.0.0-alpha.39` with the `ReflectMetadataProvider`. 

docs: https://github.com/mikro-orm/mikro-orm/blob/717e46328244ba60dec0e800f0e999d1e2ce37b1/docs/metadata-providers.md

Will be happy to hear concrete suggestions about the docs (what's unclear, what's missing and where). 

> i'm still waiting for the tool to tell me which properties i'm missing

Not yet there, but now you could use the new `ReflectMetadataProvider` instead, as it should throw when something is missing and we are not able to get the type via `reflect-metadata`. To be honest now I am not 100% sure if we need such thing. The purpose of that command was to not fall into `ts-morph` discovery. But that is the exact purpose of `ReflectMetadataProvider`, so using that instead will warn you during the actual discovery (which you can fire from the CLI e.g. via `mikro-orm cache:generate` command). 

On the other hand the auto-fix variant could be still useful, but if you would use `ReflectMetadataProvider` instead of the `ts-morph` provider, we do not have to explicitly write all those types when we know they can be read via `reflect-metadata`. Another thing the command does is to fill the `nullable` attribute based on property being optional, so I guess it still has its purpose...

**Comment by vimmerru** [comment]
@B4nan Just migrated to ReflectMetadataProvider and it works fine at least for our use cases. Thanks! It would be nice to have ts-morph as an optional dependency.

**Comment by B4nan** [comment]
Currently there are few more places like entity generator and migration generator where `ts-morph` is used so it is runtime dependency of the CLI (although that could be rewritten to be dependency free). I can see this happening in future when this is converted to monorepo and the repo split into multiple projects. It might come with v4, but can't promise, not a big priority although it's something I would love to do.

**Comment by vimmerru** [comment]
> Currently there are few more places like entity generator and migration generator where ts-morph is used so it is runtime dependency of the CL

Can it be just put to dev dependencies section? For users of TsMorphMetadataProvider optional dependency can be referenced.

**Comment by B4nan** [comment]
That is the problem, if I put it into dev deps, it won't be installed automatically so entity and migration generators won't work unless you install it manually. It's not just about the `TsMorphMetadataProvider`.

**Comment by vimmerru** [comment]
In my understanding npm installs dev dependencies automatically until you explicitly add --production flag. 

From https://docs.npmjs.com/cli/install

```
Install the dependencies in the local node_modules folder.

In global mode (ie, with -g or --global appended to the command), it installs the current package context (ie, the current working directory) as a global package.

By default, npm install will install all modules listed as dependencies in package.json.

With the --production flag (or when the NODE_ENV environment variable is set to production), npm will not install modules listed in devDependencies.

NOTE: The --production flag has no particular meaning when adding a dependency to a project.
```

As a result ts-morph will be automatically installed for all developers and only skipped for production packaging.

**Comment by B4nan** [comment]
That is about your project dependencies, not about 3rd party dependencies.

**Comment by vimmerru** [comment]
Understand, the only option is put cli to dedicated package that can be added as dev dependency. I believe it can be made after v3 release.

**Comment by olivierlacan** [comment]
@B4nan I'm curious if nowadays there's one metadata provider your recommend over another these days? 

https://mikro-orm.io/docs/entity-references/ offers examples for all three providers and https://mikro-orm.io/docs/metadata-providers/ doesn't seem to point to any advantages of either. We're using reflect-metadata but I'm curious if there are still similar drawbacks.

**Comment by B4nan** [comment]
- ts-morph has few drawbacks, mainly costly discovery and therefore requires caching, it used to have other limitations but those are mostly gone these days (e.g. we can have multiple entities in one file, the names do not have to be aligned with file name, and discovery in production works on .d.ts files instead of .ts source files). for some the biggest no-go was that it requires full TS as a runtime dependency, so technically you need to install it in production too - also not 100% true nowadays, as you can generate production cache via CLI as a build step, and when there is valid cache present, no ts-morph will be executed
- limitations of reflect-metadata are described in the docs: https://mikro-orm.io/docs/metadata-providers/#limitations-and-requirements
- entity schema is basically "write everything yourself", so you don't get any benefits from existing TS types (but the definition is typesafe based on those)

They are still all very valid (no plans to remove any of those), and personally I am still preferring ts-morph as I don't mind the (relatively small) performance hit when changing something in entity definitions. 

It's funny how for some the ts-morph one is weird, but at the same time the very same people can complain about how reflect-metadata works in JS (not related to this thread, but there was this guy on HN, very convinced that its the ORMs fault that it does not infer `prop: string | null` automatically 🤷 that is exactly what ts-morph can do).

**Comment by AndysonDK** [comment]
Hey @B4nan
>as I don't mind the (relatively small) performance hit when changing something in entity definitions

Is this only happening in development, could you elaborate on this? I would like to know the performance difference of using TsMorphMetadataProvider and ReflectMetadataProvider in production. I don't care about performance in development.

btw awesome ORM!

**Comment by B4nan** [comment]
Only difference is on the initial app start, and you can get around it by generating the production metadata cache via CLI before you start the app (so as a build step).

```
mikro-orm cache:generate
```

https://mikro-orm.io/docs/next/metadata-providers

**Comment by AndysonDK** [comment]
Alright I'll go with TsMorphMetadataProvider then, thanks for the very quick response!
