### ISSUE TITLE
Embedded initialization doesn't happen for existing objects

### ISSUE THREAD

**Issue by parisholley** [mikro-orm/mikro-orm#2366]
```typescript
@Embeddable()
export default class MyEmbed {
  @Property()
  one?: string;

  @Property()
  two?: string;
}

@Entity()
export default class MyModel {
  @Embedded(() => MyEmbed)
  pricing = new MyEmbed();
}

const model = em.findOne(MyModel, 1);
model.pricing.one = 'foobar'; // undefined error

```

While presumably the ORM isn't generating the sub-object until it encounters `one` or `two`, from an object model perspective, even though `one`/`two` can be null, I shouldn't have to add initialization code anytime I want to read/write

**Additional context**

```
    "@mikro-orm/cli": "^4.5.9",
    "@mikro-orm/core": "^4.5.9",
    "@mikro-orm/migrations": "^4.5.9",
    "@mikro-orm/nestjs": "^4.3.1",
    "@mikro-orm/postgresql": "^4.5.9",
    "@mikro-orm/reflection": "^4.5.9",
```

**Comment by B4nan** [comment]
This is on purpose, as property initializers as part of constructors, and constructors are never executed for managed entities (and embeddables are technically entities too). If you want this behaviour, you can use [`forceEntityConstructors`](https://mikro-orm.io/docs/configuration#using-native-private-properties).

**Comment by parisholley** [comment]
presumably enabling that is effectively:

```typescript
const model = new Model();
Object.assign(model, queryResult);
```

If so, i'll make a issue to update the embedded documentation and include an example with a reference to that flag. is there a downside to enabling this, eg: reason it isn't used by default?

fyi, at some point, i will be contributing :) just recording issues as i go along

**Comment by B4nan** [comment]
Yes basically that. It still tries to extract the construct parameters and pass them if possible, see the implementation here:

https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/entity/EntityFactory.ts#L142-L152

> is there a downside to enabling this, eg: reason it isn't used by default?

Because this way users can actually use custom constructors with parameters. If the ORM would use such constructors internally to create instances for managed entities, it would always have to provide all the ctor parameters, or the instantiation could fail. Imagine you have object/entity parameter and you work with one of its properties - if such parameter is missing, you try to access property of undefined - given the example [here](https://mikro-orm.io/docs/entity-constructors/), imagine the ctor would also work with `author.name`.

**Comment by B4nan** [comment]
> fyi, at some point, i will be contributing :) just recording issues as i go along

Great to hear that, and thanks for your feedback and suggestions!
