### ISSUE TITLE
QueryBuilder breaks when where() comes before update()

### ISSUE THREAD

**Issue by parisholley** [mikro-orm/mikro-orm#2390]
**Describe the bug**
```sql
error: update "user" set "foobar" = '1' where "e0"."foobar" is null and "e0"."id" in ('1') - missing FROM-clause entry for table "e0"
```

broken
```typescript
await em
  .createQueryBuilder(User)
  .where({ foobar: null, id: { $in: userIds } })
  .update({ foobar: member.id })
  .execute();
```

works
```typescript
await em
  .createQueryBuilder(User)
  .update({ foobar: member.id })
  .where({ foobar: null, id: { $in: userIds } })
  .execute();
```
**Versions**

```
    "@mikro-orm/cli": "^4.5.9",
    "@mikro-orm/core": "^4.5.9",
    "@mikro-orm/migrations": "^4.5.9",
    "@mikro-orm/nestjs": "^4.3.1",
    "@mikro-orm/postgresql": "^4.5.9",
    "@mikro-orm/reflection": "^4.5.9",
```

**Comment by B4nan** [comment]
This particular case is working fine in master/v5, no plans to backport as it was fixed by a side effect, so I don't even know where to look for. Issues with this approach are there only when auto-joining comes to play - you can use deep conditions in update/delete and it will generate query with subselect to allow joining - but to do that we need to know the query type before applying the conditions, as that is where auto-joining happens.

Will at least add a validation for that case, as it is easy to validate (calling `update/delete` on a QB instance that already has some joins).
