### ISSUE TITLE
Cannot assign to JSON property when `mergeObjects` is enabled.

### ISSUE THREAD

**Issue by pawelsmolenski** [mikro-orm/mikro-orm#2492]
**Describe the bug**

When using `EntityAssigner` to assign data to an `Entity` it is impossible to set value of properties of object/mergeable type (i.e. `JsonType`) if `AssignOptions.mergeObjects` is enabled and property is nullable.

**Stack trace**

None

**To Reproduce**

1. Define entity with nullable JsonType property without default value, e.g.:
```javascript
@Entity()
export class Display {
    @Property({ length: 255, nullable: true })
    name?: string;
    
    @Property({ type: "json", nullable: true })
    geometry?: {
        top: number;
        left: number;
        width: number;
        height: number;
    };
}
```

2. Try to assign data to a fresh instance of that entity, e.g.:
```javascript
const entity = new Display();
const data = {
    name: "Toto",
    geometry: {
        top: 0,
        left: 0,
        width: 640,
        height: 480,
    }
};

wrap(entity)
    .assign(data, {});
```

...and `geometry` will be not assigned to the entity.

**Expected behavior**

Values of JsonType properties should be assigned to the entity.

**Additional context**

Temporary solution is to turn off `mergeObjects` option or set default value of such a property. 

I am sorry but my knowledge about underlying architecture is not good enough to propose any real solution.

**Versions**

| Dependency | Version |
| - | - |
| node | * |
| typescript | * |
| mikro-orm | 5.0.0-dev.500 |
| your-driver | postgresql |

**Comment by B4nan** [comment]
Thanks for testing v5! Next time please use the latest version before you file issues about it, things are moving every day :] Also saying your node and TS versions are `*` kinda beats the purpose of why that table is part of issue template. We need to know what exact versions are you on to be able to reproduce things the way you do.

Weird that it is behaving like this, I can confirm it happens on my end too with the latest v5, and it works the same regardless of the nullability (as expected, nullability is for schema generator, rest of the code mostly ignores it or uses it for added validation).

Btw if you actually need to do this on new entity instance, note that the right approach is using `em.create()` instead of creating istance and using `assign` on it. `assign` was meant to be used with managed entities, if you need to create new entity graph from a DTO. `em.create()` does not suffer from this issue (but obviously it won't help if you need to update managed entity).
