### ISSUE TITLE
Support the custom mapping of ts types to column types.

### ISSUE THREAD

**Issue by wesleyks** [mikro-orm/mikro-orm#2546]
**Is your feature request related to a problem? Please describe.**
For my project I want to default to using `varchar` (without the `(n)`) or `text` column types for storing string content. Right now it appears the default column type for strings is `varchar(255)`. I'd rather be able to configure a mapping of ts types to column types instead of having to go back and annotate all the string properties of my entities to use `@Property({ columnType: 'varchar' })`.

**Describe the solution you'd like**
A new setting that lets me override the default column type mappings.

**Describe alternatives you've considered**

**Additional context**
The usage of `varchar` or `text` columns is preferred per the [Postgres wiki](https://wiki.postgresql.org/wiki/Don't_Do_This#Don.27t_use_varchar.28n.29_by_default), unless we specifically want string lengths to be enforced by the db instead of the application.

**Comment by B4nan** [comment]
No plans to make the configuration more cluttered for such reason. If you care about this so hard (harder than doing quite simple find/replace in your IDE), implement your own driver (by extending the existing one) and override the methods in platform - that already is an extension point.

The reason behind this is to have drivers behave similarly.

**Comment by bengotow** [comment]
Hey folks! Just wanted to chime in on this, I think all the defaults are fine and do not need to be configurable, but the `varchar(255)` type is a poor default for string properties. I find I have to specify `@Property({ type: TextType })` all over the place because 255 is not sufficient for a lot of our data (URLs, freeform user-provided text etc). Postgres doesn't really require the max length and I'd expect it to be something I'd add explicitly per-property if I knew the data was of a finite length.

Just a nit though!

**Comment by B4nan** [comment]
Once we resolve #3066 you will be able to adjust the default type mapping, in other words you will be able to make all string properties default to the `TextType` (or any other type, e.g. a varchar with different length).

As said in that issue, its already possible but you need to extend the driver or patch the platform method.
