### ISSUE TITLE
docs: getKnex() not on Connection

### ISSUE THREAD

**Issue by emrosenf** [mikro-orm/mikro-orm#255]
`Connection` does not have `getKnex()` as documented in the docs. You need to do:

```typescript
const knex = (em.getConnection('read') as AbstractSqlConnection).getKnex()
```

Are issues like this helpful? Is it better if I just make PRs for docs issues like this?

**Comment by B4nan** [comment]
I guess it makes sense to first discuss what/why/how in form of issue, but of course if it's something obvious, feel free to send PR directly.

About this issue - while you can typecast the connection instance as you noted, the correct way is to provide generic type parameter in `MikroORM.init<D>()`:

```typescript
const orm = await MikroORM.init<MySqlDriver>();
orm.em.getConnection() // instance of MySqlConnection (child of AbstractSqlConnection)
```

or in `EntityManager<D>`:

```typescript
const em: EntityManager<MySqlDriver> = ...;
em.getConnection() // instance of MySqlConnection (child of AbstractSqlConnection)
```

Which is usually the thing you would do when injecting EM from a DI container:

```typescript
constructor(@Inject() private readonly em: EntityManager<MySqlDriver>) { }

this.em.getConnection() // instance of MySqlConnection (child of AbstractSqlConnection)
```

**Comment by emrosenf** [comment]
I didn't see an exported `MySqlDriver` but it is working pretty well with `EntityManager<AbstractSqlDriver>`.

Thanks. Feel free to close or we can update the example in the docs

**Comment by B4nan** [comment]
It is not exported directly because that would require users to download all the driver dependencies. You can still import it from `mikro-orm/dist`.

This is one of the reasons why I am planning to split the ORM into multiple packages (each driver having one dedicated package with all its dependencies, like the underlying db connector).

I will update the docs first before closing this.
