### ISSUE TITLE
QueryBuilder left join the same table twice bug

### ISSUE THREAD

**Issue by deemaagog** [mikro-orm/mikro-orm#2602]
Hi! thanks a bunch for this awesome ORM!
**Describe the bug**
 I'm trying to join the same table twice (this is a simplified example)
```
const qb = await this.patternRepository
      .createQueryBuilder('patterns')
      .select(['patterns.id', 'user.id', 'user2.id'])
      .leftJoin('patterns.user', 'user')
      .leftJoin('patterns.user', 'user2')
      .getResultList();
```

 and getting an error
`invalid reference to FROM-clause entry for table "user"`

this is the resulted sql query, seems like one left join is missing 

`select "patterns"."id", "user"."id", "user2"."id" from "pattern" as "patterns" left join "user" as "user2" on "patterns"."userId" = "user2"."id"`

**Expected behavior**
No error

**Versions**

| Dependency | Version |
| - | - |
| node | 14 |
| typescript | 4.1.3 |
| mikro-orm | 5 |
| your-driver | postgresql |

**Comment by vincentwinkel** [comment]
I don't know if it's relted, but I get an issue because of a table joined twice.
Basically, I have this structure (pseudo language, simplified for the example):
```js
entity SeekerProfile {
  // ...
  mobilities: Collection(SeekerProfileMobility)
}

entity SeekerProfileMobility {
  // ...
  address: SeekerProfileAddress
  radius: int
}

entity SeekerProfileAddress {
  // ...
  lat: float
  lng: float
}
```
I would like to find all seeker profiles matching the location (the given coords should be inside their radius).
I'm trying something like:
```js
// wrapper to .find({ filters }, [populate]) 
await this.seekerProfileService.load(
  {
    mobilities: {
      [expr(
        `(point(lng, lat) <@> point(${coords.lng}, ${coords.lat})) * 1.609344`,
      )]: {
        $gte: em.raw('seeker_profile_mobility.radius_internal'), // error here
      },
    },
  },
['mobilities.address'], // populate
);
```
This is the error I get, after running the SQL generated. How can I target my table `seeker_profile_mobility` without hard-code its generated alias?

<img width="614" alt="Screenshot 2022-10-17 at 19 41 19" src="https://user-images.githubusercontent.com/1402505/196245890-b0853bc4-190c-4175-8e4f-20349c9df1cf.png">
