### ISSUE TITLE
Turning off filter does not bypass identity map

### ISSUE THREAD

**Issue by koyedele** [mikro-orm/mikro-orm#2603]
**Describe the bug**

First, thank you for all your hard work on MikroORM!

Suppose you have `Company` and `Employee` with a `OneToMany` relationship between them. Suppose `Employee`s can be `active` or `inactive` and you have a default filter on `Employee` to select only `active` records. Load a `Company` and populate the `Employee`s. With the default load strategy (`LoadStrategy .SELECT_IN`), the filter on `Employee` will be applied and you'll get only active records, as expected. Now re-run the same query (using the same EM), and turn off all filters (using `filters: false`). You'll notice that only the active `Employee`s are still returned.

To be fair, adding `refresh: true` in addition to `filters: false` to the find options yields the expected behavior i.e. both active and inactive `Employee`s are returned. But if there's a filter and the filter is turned off, shouldn't that cause the identity map to be bypassed? This might just be a misunderstanding of how the library works on my part.

**To Reproduce**

Reproduction in test form here: https://github.com/koyedele/mikro-orm/blob/ko/filter-bug/tests/issues/GH2603.test.ts

**Expected behavior**

Applying just `filter: false` should make the EM re-run the query and by-pass the identity map

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | v14.17.0 |

**Comment by B4nan** [comment]
Thanks for the repro. The problem here is that the collection is already initialized, so the second population will ignore it without the explicit `refresh: true`. It is not really about bypassing identity map, but rather about the collection state. With `refresh: true`, it will get overridden so the second time population will do something (and the filters won't be applied).

It seems like correct behavior, as population always ignores things that are already loaded. And given that there is only one instance of your entity - both `loadedCompany` and `reloadedCompany` are the exact same object (`loadedCompany === reloadedCompany`) - you are basically trying to populate already loaded collection unless you use `refresh: true` and explicitly ask for ignoring the previous state. Without the `refresh: true`, if we would automatically reload the collection here, it would have effect on both `loadedCompany` and `reloadedCompany`, that is why it does not work this way by default.

**Comment by koyedele** [comment]
Thanks for the quick response! Your points actually make sense that the correct use case is to use `refresh: true`.
