### ISSUE TITLE
Extraneous migrations created for date types

### ISSUE THREAD

**Issue by evantrimboli** [mikro-orm/mikro-orm#2655]
**Describe the bug**
For `timestamptz` column types, it appears as though the columns are being treated as changed when they are not

**Stack trace**
N/A

**To Reproduce**
1. Clone the `date-migrations` branch here: https://github.com/evantrimboli/mikro-orm-test-cases/tree/date-migrations
2. Run `npm install`
3. Run `npx mikro-orm migration:create --initial`
4. Run `npx mikro-orm migration:up`
5. Run `npx mikro-orm migration:create`

The first migration created is correct:

```typescript
export class Migration20220120072521 extends Migration {
  async up(): Promise<void> {
    this.addSql('create table "user" ("id" serial primary key, "created" timestamptz not null default now());');
  }
}

```

The second migration is redundant:

```typescript
export class Migration20220120072532 extends Migration {
  async up(): Promise<void> {
    this.addSql('alter table "user" drop constraint if exists "user_created_check";');
    this.addSql('alter table "user" alter column "created" type timestamptz using ("created"::timestamptz);');
  }

  async down(): Promise<void> {
    this.addSql('alter table "user" drop constraint if exists "user_created_check";');
    this.addSql('alter table "user" alter column "created" type timestamptz using ("created"::timestamptz);');
  }
}
```

**Expected behavior**
Running step 5 should do nothing and indicate that there are no changes.

**Additional context**
Happy to look into this, if you have any obvious places to start looking that would be useful.

**Versions**

| Dependency | Version |
| - | - |
| node | 16.13 |
| typescript | 4.5.4 |
| mikro-orm | 5.0.0-dev645 |
| your-driver | postgres |

**Comment by B4nan** [comment]
As mentioned on slack, this is caused by mismatch in lengths. Postgres defaults to 6, while we use 0 in the ORM codebase (this is to align with how other drivers behave). And given that you use `columnType` which is never postprocessed - you say you want length 6, but the ORM does not see that from the metadata. 

```ts
// if you really want length 6
@Property({ columnType: 'timestamptz(6)', defaultRaw: 'now()' })
created!: Date;

// no need to use columnType at all, as it can be inferred from reflect-metadata
@Property({ length: 6, defaultRaw: 'now()' })
created!: Date;
```

Note that microseconds won't fit into JS Date object, I believe that can break UoW diffing, so be careful with that. 

I can see how this is confusing, maybe we should make the driver aware of what the default datetime column length is instead of normalizing to 0 all the time. Right now we dont see the length when inferring mapped type, hence it will default to 0 here: 

https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/types/DateTimeType.ts#L8
