### ISSUE TITLE
migration:fresh command does not bring up the migration after pulling it down

### ISSUE THREAD

**Issue by 9r1nc3w1ll** [mikro-orm/mikro-orm#2698]
**Describe the bug**

When I run `npx mikro-orm migration:fresh`, I expect the behaviour to be for mikro-orm to run a migration:down to 0 and a migration:up (correct me if I am wrong).

That doesn't happen, what happens is the migration goes down but doesn't go come back up and no error is thrown.
The independent migration up and down commands work though.
The only way to get the migrations to come up after running `migration:fresh` is to do a `schema:fresh --run` or `schema:update --run`

**Stack trace**
```
...
```

**To Reproduce**
1. Generate a migration (not initial as initial cannot be rolled back) `npx mikro-orm migration:create`.
2. Run `npx mikro-orm migration:up` - This would work.
3. Run `npx mikro-orm migration:fresh` This would run, take down the migration but fail to recreate them.
4. Running `npx mikro-orm schema:fresh --run` Recreates the migration.

**Expected behavior**
I expect migration:fresh to clear and rebuild the migrations.

**Additional context**
- I might be wrong about the expectations from the migration:fresh command.
- How do the migration commands differ from the schema commands?

**Versions**

| Dependency | Version |
| - | - |
| node | 16.13.2 |
| typescript | 4.5.2 |
| mikro-orm | 5.0.0-dev.532 |
| Postgres | 5.0.0-dev.532 |

**Comment by B4nan** [comment]
First of all, please always upgrade to latest version before filing issues, especially when using unreleased dev version. `dev.532` is quite old, there are almost 200 new commits since then.

`fresh` should not run all migrations down and up, it drops the whole schema and builds it again using only up migrations - that is what the descritption says - 'Clear the database and rerun all migrations'. Down migrations are optional, we cant expect them to be there, and we can't expect them to actually be able to tear down the whole database schema.

But you are right there is a bug, as it does not reset the migrations table, so running `migration:up` can't do anything - the state in the table says all is already executed.

Can you please try to change [this line](https://github.com/mikro-orm/mikro-orm/blob/master/packages/cli/src/commands/MigrationCommandFactory.ts#L172) to `await generator.dropSchema({ dropMigrationsTable: true });`?

> How do the migration commands differ from the schema commands?

Schema commands do changes on schema, migration commands work with migrations. Migrations are using schema generator to get the diffs.

**Comment by 9r1nc3w1ll** [comment]
Thanks @B4nan. I'll make the change, verify and do a PR.
