### ISSUE TITLE
Unable to provide name for PK through naming strategy

### ISSUE THREAD

**Issue by oliversalzburg** [mikro-orm/mikro-orm#2762]
**Describe the bug**

It is not actually possible to control the name of primary keys through a naming strategy, even in database drivers where it should be supported (postgres).

**To Reproduce**
1. Provide alternative naming for the `"primary"` index type in the naming strategy.

**Expected behavior**

Names of primary keys can be controlled when this should be supported by the database driver.

**Additional context**

The current naming behavior seems to be hardcoded at: https://github.com/mikro-orm/mikro-orm/blob/05990328ccad8b0e8a37b0eb323a89d1df876976/packages/knex/src/schema/SchemaGenerator.ts#L484

I wasn't able to understand where the naming strategy would be referenced here.

**Versions**

| Dependency | Version |
| - | - |
| node | 16 |
| typescript | 4.4 |
| mikro-orm | 5.0.1 |
| postgresql | 5.0.1  |

**Comment by B4nan** [comment]
That like you mentioned is using `undefined` unless you have explicit schema name, not really a hardcoded name (not sure if the first branch is even used, seeing the coverage ignore comment). 

The reason here is that we don't usually need to name a PK, and doing so would require additional query. PKs are not compared by name when diffing. 

So I would rather keep this as is, will check it later today to be sure, but I would rather not have this configurable and save one query for each table. The first branch could use the naming strategy, but as said, I am not sure if it's even valid, might be a dead code.

**Comment by oliversalzburg** [comment]
Hmm okay, I can see it's more complex than what I thought. I might just rename the PKs in our existing data model then to reach some alignment. I'll give a moment, until your final call.

**Comment by B4nan** [comment]
Looks like the actual reason for this was mysql and sqlite, where the PK key name is forced to be `PRIMARY`, and I didn't want to have that in the generated SQL. Will try to find a way how to make this work for postgres.
