### ISSUE TITLE
Why does M:N have owning side?

### ISSUE THREAD

**Issue by emrosenf** [mikro-orm/mikro-orm#288]
I'm used to modeling m:n relationships bidirectionally, where the convention may be that two foreign keys are in alphabetical order.

MikroORM seems to have a limitation that only the "owning" side collection changes can be picked up by the ORM. [See code from ChangeSetComputer below.](https://github.com/mikro-orm/mikro-orm/blob/master/lib/unit-of-work/ChangeSetComputer.ts#L50)

```typescript
  private processReference<T extends AnyEntity<T>>(changeSet: ChangeSet<T>, prop: EntityProperty<T>): void {
    const isToOneOwner = prop.reference === ReferenceType.MANY_TO_ONE || (prop.reference === ReferenceType.ONE_TO_ONE && prop.owner);
    // why do we have prop.owner?
    if (prop.reference === ReferenceType.MANY_TO_MANY && prop.owner) {
      this.processManyToMany(changeSet, prop, changeSet.entity[prop.name as keyof T] as unknown as Collection<T>);
    } else if (isToOneOwner && changeSet.entity[prop.name as keyof T]) {
      this.processManyToOne(prop, changeSet);
    }
```

As a result, if you have `Book` and `BookTag` models in a m:n relationship with `Book` as the owner, you could add do:

```typescript
book.tags.add(myTag)
em.flush()
```

But this would not work as expected:

```typescript
myTag.books.add(book)
em.flush()
```

What was the reason for this limitation?

**Comment by B4nan** [comment]
Sorry for the late response. I will try to think about this more later, but generally:

- when using mongo driver, owning side is the one that stores array of inversed PKs (no pivot tables are involved there)
- while only the owning side is really persisted (the code snippet you highlighted), persisting from inverse sides is also supported as long as you have both collections initialized (see https://mikro-orm.io/docs/collections/#propagation-of-collections-add-and-remove-operations)

**Comment by B4nan** [comment]
Spent few hours trying to get this working, the main issue here is that when you have both sides initialized, they are automatically synchronized. If I remove those conditions to allow persisting m:n inverse side, it would first persist the owning side, and then all inverse sides as well. The result would be pretty much the same, but we would have unnecessary sql queries fired (2*n, as you would have 1 delete and 1 insert query for each item in the collection - all of it unnecessary). 

Here is also some reasoning from the doctrine docs about this: https://www.doctrine-project.org/projects/doctrine-orm/en/2.7/reference/unitofwork-associations.html#important-concepts

I am going to close this, correct way to handle this is to either work with the owning side, or have both sides initialized and let propagation do its job, then you can work with either side and the owning side will be always in sync.

```typescript
await book.tags.init();
myTag.books.add(book); // when book.tags are initialized, the add operation is propagated to the owning side
myTag.books.add(new Book(...)); // new entities have intialized collections, so this will work out of the box
await em.flush();
```

**Comment by stephenh** [comment]
> or have both sides initialized

Am I reading this correctly, that if I mutate the non-owning side, without remembering to explicit `.init()` the owning side, my changes will be ignored/dropped?

That seems pretty surprising & bad; can that at least be turned into a runtime error? Or did I misunderstand?

**Comment by B4nan** [comment]
Well, as I said, you should always prefer to work with the owning side when writing to the db. 

Afaik this is how all JPA like ORMs are working. The whole inverse-owning side thing is about this.

**Comment by stephenh** [comment]
Hm...it's been 10 years since I used Hibernate/JPA but I don't remember it doing that...

My point is primarily that silent failures about the worst kind of failure possible. Users of Mikro are going to think that this works, i.e. see it work in a codepath/test that happens to `init` both collections before calling `foo.inverseSide.add(bar)`, but then in production are going to have some different codepath that forgets to `init` the `bar.owningSide` owning-side collection, and now they have a bug that's going to be hard to find ("...wtf, why was `bar` not added?").

I.e. in our own usage of Mikro, I'm now wondering if bidirectional syncing is just inherently unsafe, and we should not use it, and force client code to always use the owning side anyway (i.e. not even codegen the inverse side...or make it immutable if we do...), to avoid bugs where the inverse side "sometimes works/sometimes doesn't".

That seems like the most robust option, AFAIU?

Is there a way to proactively fail the `foo.inverseSide.add(bar)` call if the `bar.owningSide` is not `init`'d? That seems like the simplest thing to at least tell Mikro users what is happening.

(...somewhat musing, but I wonder, when `bar.owningSide` is not init'd, could the `inverseSide.add(bar)` call essentially be buffered/kept in memory until either a) the owning side is later init'd, or b) the UoW is flushed, at which both the owning collection would be loaded + then the buffered operations applied. I did something similar in a prior JVM ORM I hacked on for a few years: https://github.com/stephenh/joist/blob/master/domain/src/main/java/joist/domain/orm/ForeignKeyListHolder.java#L90)

**Comment by B4nan** [comment]
> Is there a way to proactively fail the foo.inverseSide.add(bar) call if the bar.owningSide is not init'd? That seems like the simplest thing to at least tell Mikro users what is happening.

That should be quite easy. I will try harder to come up with a way to get around this, but agreed with adding at least the validation.

**Comment by stephenh** [comment]
> agreed with adding at least the validation.

Great, thanks!

**Comment by lookfirst** [comment]
> My point is primarily that silent failures about the worst kind of failure possible. Users of Mikro are going to think that this works, i.e. see it work in a codepath/test that happens to `init` both collections before calling `foo.inverseSide.add(bar)`, but then in production are going to have some different codepath that forgets to `init` the `bar.owningSide` owning-side collection, and now they have a bug that's going to be hard to find ("...wtf, why was `bar` not added?").

I get that and agree with you that yes there should be some sort of validation, but the thought that tests deviate from production seems really wrong.

**Comment by stephenh** [comment]
> the thought that tests deviate from production seems really wrong

Well, pedantically yes, but I think reality is more nuanced than that. Even things like validation rules running in a different order (because we tested each one in isolation but in production the code loads a slightly different set of entities, in a different order, or from a different loader method) can matter and just realistically are not exhaustively tested.

To a certain extent, any time we make an abstraction (say a validation rule or even some business logic), the goal is to be able to re-use that abstraction in N places. However, we don't re-test that abstraction in all N places it's used; that's part of the point of the abstraction, to provide "guaranteed to work" functionality.

However, that means the contract between the caller-of-the-abstraction and the abstraction itself needs to be well defined, which is generally what we rely on static typing to do, but "side effect-y" things can throw this off, of which this constraint of "collections must be init'd" is a great example (i.e. "I had unit tested validation rule x/y/z really well, but in the 3rd of 6 places that load this entity, you forgot to pass me the domain object with all of its collections init'd").

...anyway, sorry for the overly-long/freshly-caffeinated reply. :-)

**Comment by stephenh** [comment]
Nice, thanks @B4nan !

**Comment by lookfirst** [comment]
@B4nan ... @stephenh and I worked together on Apache Jakarta projects back in the day... probably virtually known each other for 20 years now. ;-)
