### ISSUE TITLE
Cascade.REMOVE makes the foreign key nullable in db

### ISSUE THREAD

**Issue by AlexandrosMelissas** [mikro-orm/mikro-orm#2893]
**Describe the bug**
Whenever i set ``` cascade: [Cascade.REMOVE] ``` in a m-1 relation, foreign key in migration and as a result, in db, becomes nullable. 

**To Reproduce**
1. Make a parent entity 
2. Make a child entity
3. Make a m-1 relation of a child entity in parent entity and put cascade remove

**Expected behavior**
The foreign key should not be nullable

**Versions**

| Dependency | Version |
| - | - |
| node | 14.15.0 |
| typescript | 4.3.5 |
| mikro-orm | 5.0.5 |
| your-driver | mysql |

**Comment by B4nan** [comment]
Yes, it becomes nullable, because it needs to be nullable if you want to cascade remove. M:1 means you can have the same FK in multiple entities. If you make it cascade remove, it means that if you remove owning entity, it will remove the relation. But that means that you can remove the target entity which might be referenced in other owning entities.
