### ISSUE TITLE
Using an enum with snapshots disabled results in an infinite migration loop

### ISSUE THREAD

**Issue by SpencerKaiser** [mikro-orm/mikro-orm#2938]
**Describe the bug**
If an entity includes an enum as part of it's structure and snapshots are disabled in the `orm.config.ts`, `mikro-orm migration:create` will _**ALWAYS**_ create a new migration

**Stack trace**
N/A

**To Reproduce**
1. Clone [this repro repo](https://github.com/SpencerKaiser/Mikro-Orm-Enum-Repro)
2. `yarn` to install dependencies
3. Create a Postgres db called `repro`
4. Run `yarn mikro-orm migration:up`
6. Run `yarn mikro-orm migration:create`
7. Observe the new migration which tries to recreate existing changes (NOTE: this migration will also not run; it tries to drop a new constraint that doesn't exist yet)

**Expected behavior**
After running a migration, running `migration:create` will **NOT** generate a new migration

**Additional context**
Once snapshots are re-enabled, subsequent `migration:create` commands do not generate new migrations

**Versions**

| Dependency | Version |
| - | - |
| node | v16.13.0 |
| typescript | 4.4.3 |
| mikro-orm | 5.1.1 |
| your-driver | `@mikro-orm/postgresql` |

**Comment by B4nan** [comment]
> NOTE: this migration will also not run; it tries to drop a new constraint that doesn't exist yet

That's not really true, the query is there for every column type change detected because we dont know if it was an enum or not, and uses `if exists` so it runs just fine even if the constraint is not there. The purpose is to ensure the constraint is not there, its not about removing it too early, its about ensuring its not there without knowing it upfront.

Btw if you want to do the extra step, next time please use a single file reproduction (ideally a test case), and instead of migrations, use schema generator directly, as migrations always just work with it, there are usually no bugs in migrations, its always about schema diffing that lives one level deeper. In the end it should be much faster for you as well, as you would produce a fraction of the code you had.

Lastly, reproductions should be minimal, we are talking about enum issue, hence, there is no need for 2 entities and relations, use just one entity with one PK and one enum, everything else is just adding clutter.

I can confirm it works fine without the overridden naming strategy, the problem is in the enum check constraint name.

**Comment by B4nan** [comment]
Use the dev version, each commit is published to npm.
