### ISSUE TITLE
Enable Migrations Support for MongoDB

### ISSUE THREAD

**Issue by pharophy** [mikro-orm/mikro-orm#295]
**Is your feature request related to a problem? Please describe.**
Enable migrations to support the Mongo driver

**Describe the solution you'd like**
Ability to use migration, schema, and other cli tools for Mongo driver

**Describe alternatives you've considered**
Building a custom script to handle it and run via ts-node

**Additional context**
n/a

**Comment by B4nan** [comment]
As promised on slack, here are few notes about how to implement this:

- `Migrator` and its migration related dependencies now depend on `AbstractSqlDriver`, easiest approach would be probably to introduce `MongoMigrator` that would be used instead
- currently migrations are about registering SQL commands via `addSql()`, this is obviously not usable for mongo, we might need some additional helper command in the `MongoMigration` class, maybe `getCollection(entity)`?
- another piece of code that will be needed is `MongoMigrationStorage`, we could also use mongo storage provided by umzug, but that would probably create new connection which is unnecessary
- last thing will be to adjust `MikroORM` wrapper class so it does return the appropriate migrator class based on the current platform

> Ability to use migration, schema, and other cli tools for Mongo driver

We discussed migration on slack, obviously supporting schema related things in mongo is totally different story. As there is no schema present, there is not much we can do here. I can imagine entity generator to work based on the first record in given collection, but I do not see a way how we could have mongo flavoured schema generator.

**Comment by B4nan** [comment]
I would like to look into this soon, but I just realised that you asked for more than just migrations. 

How do you think schema generator could work for mongo? We can check for existing/missing collections, we could also check for defined properties based on the first document, but how would the schema update work? I am not sure if it makes sense to run something like find and update queries to change a type of a column or rename it - that sounds like really performance heavy thing.

**Comment by cyrilchapon** [comment]
Indexing in Mongo (for production uses) has to be done through migrations. Apart from "schema", that single use-case justifies mongo-aware migrations IMHO

**Comment by chrisbward** [comment]
Apparently, according to the closed issue above (#1002), Mongo does not support migrations - and dumps an Knex error on the user.

Ideally there could be a better warning? Just throwing it out there - who knows...

**Comment by andrey-hohlov** [comment]
@B4nan 

We started to use Mikro-ORM instead of mongoose and love it more and more.
Seeds just works, without additional library, with the same configuration file. Amazing.

Now it's time to implement migrations.
_It's just a fact - sometimes we need to change something in the database. Even in MongoDB._

Solutions exist. For example https://github.com/seppevs/migrate-mongo

I cannot imagine different flow for migration with MongoDB. 
Just two functions - ```up``` and ```down``` where you can do what you want.
And migration state persists in the database.

So, I want to leave my feedback here. And I like to know your thoughts and plans regarding this feature.

**Comment by B4nan** [comment]
I will go with the easy way and create new `@mikro-orm/migrations-mongodb` package, as the current one depends on knex, and I definitely dont want to make it depend on mongo too (might be worth cleaning up in v6, let's see). Otherwise the CLI interface should be the same, only available migration type will be a blank one, it will have a driver instance available, plus a `getCollection(entityName)` shortcut.

**Comment by cyrilchapon** [comment]
@B4nan , for what it's worth, mongodb has transactions[transactions](https://www.mongodb.com/docs/upcoming/core/transactions/)  for a while now.

it supports "DDL" operations like collection and index manipulations : https://www.mongodb.com/docs/upcoming/core/transactions/#std-label-transactions-create-collections-indexes

**Comment by B4nan** [comment]
Mongo transactions are supported for quite some time, since v4 iirc.

**Comment by cyrilchapon** [comment]
> Mongo transactions are supported for quite some time, since v4 iirc.

I meant auto-transactional migrations would be a must for mongo driver migrations; as since 4.2 it supports "DDL-like" operations.

But you already did it, so sweet ☺️
