### ISSUE TITLE
Consider simplifying the annotations

### ISSUE THREAD

**Issue by stephenh** [mikro-orm/mikro-orm#297]
Currently the annotations seem to support at least two ways of defining options, i.e. either:

```@Annotation(() => Param1, param2)```

And an options hash:

```@Annotation({ entity: () => Param1, foo: param2 })```

Granted, there is a trade-off between letting people use the style they want, but the downside is more complicated docs / tutorials / codebases as some docs use style1 / some use style2, and same thing in codebases, someone writes entity1 with style1, someone else writes entity2 with style2 / etc.

(I.e. anytime I navigate into the typedefs to look up an option I'm looking for, I get a little thrown off by, oh right, which part of this type union am I really using...)

Feel free to keep things as is if you're too worried about breaking backwards compatibility, but given in your in the RC stages (which granted might be a little too late), now might be a good time to just pick one and move everyone to just the single way (which I presume would be the hash approach b/c it's more extensible once you have multiple optional attributes).

**Comment by B4nan** [comment]
Originally there was only the option object approach available. Then FR came for the other style, but mainly because of missing type support. Currently both ways are strictly typed, as long as you provide the `entity` option with a reference callback (`@OneToOne({ entity: () => FooBar, mappedBy: bar => bar.baz })` will be strictly type checked for the `mappedBy` option validity).

I understand that it adds complexity, but I kinda like supporting both ways. The typing always works the same way, you can use either first or last parameter for options. Also, for obvious reasons, dropping the first options parameter approach is a no go (with ts-morph metadata provider, usually the entity parameter is optional). On the other hand, when using reflect metadata provider, the approach with multiple parameters works better I think. 

I will keep this open for some time to see what others think, but personally I lean towards keeping it as is.

**Comment by stephenh** [comment]
@B4nan cool, I'll go ahead and close this out. Just wanted to mention it, if you've already had FR for both, that makes sense...
