### ISSUE TITLE
Sharing Entity type definitions with frontend applications

### ISSUE THREAD

**Issue by marcandrews** [mikro-orm/mikro-orm#300]
Can Entity type definitions be shared with frontend applications without anything related to NodeJS being imported?

**Comment by B4nan** [comment]
Only way I can imagine is to create interfaces that describe your entities, make your entities implement those and reuse just those interfaces. But you would be sharing only the properties and their types, not instance method.

```typescript
export interface IBook {
  id: number;
  title: string;
  author: IAuthor;
}

export class Book implemenets IdEntity<Book>, IBook { ... }
```

But you would still have to maintain both entities and their interfaces, which is probably not what you are looking for. 

Keep in mind that frontend type won't be always the same (e.g. collection instances in the ORM get translated to simple arrays). On the other hand, I can imagine a frontend counterpart to the ORM, that would read the serialized entity and create its frontend version with similar constraints (like the always present reference instead of plain ID, or the collection wrapper). 

To wrap up, this is not supported out of the box, closing this as answered, but I am open for a feature request if you can present a way how it could work.

**Comment by marcandrews** [comment]
Thanks for the quick response 👍

Yes, maintaining separate type definitions would dismiss one of the major benefits a library like this provides.

Alternative libraries do support this, with a few bugs here and there, and mainly accomplish this by leveraging the package.json [`browser` field](https://docs.npmjs.com/files/package.json#browser) to _shim_ anything that might break in the browser.

Anyway, I was inquiring to see if this was on the roadmap and do my best to help it along, but I unfortunately do not have the time right now to contribute to implement this from scratch. However, this library does looks great and you and the team have an amazing job. I will keep an eye on it and look forward to contributing to it in the future.

**Comment by ujwal-setlur** [comment]
This is how TypeORM attempts to do it:

https://github.com/typeorm/typeorm/blob/master/extra/typeorm-model-shim.js

**Comment by CWSpear** [comment]
@marcandrews I know it's been a looong time since you made this thread, but for you (or anyone else coming here), TypeScript has added (in v3.8) the `import type` syntax, that won't change the output (basically just ignores the import other than for type checking). It is great for preventing side-effects when you're just trying to import a type, and it will fail type checking if you try to use it as an actual value.

```ts
import type { Book } from '@entities/book`;

const book: Book = { title: 'Title', ... }; // this is ok
const book: Book = new Book(...); // this is an error
```
