### ISSUE TITLE
Any ways to provide custom properties mappings to entity.assign() ?

### ISSUE THREAD

**Issue by Frank-D** [mikro-orm/mikro-orm#3020]
Hi,

Is there any way to provide custom mappings/functions when using `entity.assign()` ([doc ref.](https://mikro-orm.io/docs/entity-helper#updating-entity-values-with-entityassign)) ?

In my case as an example, I have:
-  a DTO api input data/pojo `UserInputDTO` class having a `gender` field of enum type `UserGenderInput`.
-  a mikro-orm entity `UserEntity` class having the corresponding field `gender`, but with enum type `UserGender`.

When trying to leverage `entity.assign()` to update a `UserEntity` record as follow:
```
...

// First find existing user record (by uid)
const existingUserEntity = await this.findOne(uid);

// Update User
const updatedUserEntity: UserEntity = this.assign(
    existingUserEntity,
    userInputDTO,
);

...
```

Then I'm getting the below compilation error (using mikro-orm 5.1.2):

> Argument of type 'UserInputDTO' is not assignable to parameter of type 'EntityData\<UserEntity\>'.
>  Types of property 'gender' are incompatible.
>    Type 'UserGenderInput' is not assignable to type 'EntityDataItem\<UserGender\>'.

I would like to know if there's any existing mechanism to override default mapping by property name when using such `entity.assign()` function, so that I can provide a custom mapping for 2 properties having the same name, but having different types, like in my example above..? 

In my case, I would need to provide a custom enum function mapping to map from enum type 1 values to enum type 2 values, but my question should be more generic, and would apply to 'any' properties of 'any' types, so not only from an enum type to another, but it could be about mapping a property from string (dto) to int (entity), int to string, int to enum, etc.

If there's no existing mechanism, then I would suggest a feature request where it becomes possible to provide custom mapping overrides when calling `assign()` function, and target any properties with those custom mappings (and obviously keep all existing/automatic properties mappings by property name already offered by `assign()`, when those properties have no custom mappings/overrides provided.

Thanks

**Comment by B4nan** [comment]
> Argument of type 'UserInputDTO' is not assignable to parameter of type 'EntityData<UserEntity>'.
> Types of property 'gender' are incompatible.
> Type 'UserGenderInput' is not assignable to type 'EntityDataItem<UserGender>'.

This is a TS error, you can get around it via type casting. 

`assign` is using hydrator to map the values, and hydration is on its own a configurable layer, but I would rather discourage doing that unless you really know what you are doing, it would have much deeper effects than just on `assign`. 

Why don't you just remap your data _before_ you call `assign`? I don't really see a reason to integrate this into the ORM, especially because there is no way to make it work with strict typings (= you would still need type casting, you would still get the same TS error as you get now). Not sure what you use in your project, but this is exactly what you could achieve in nest with mapping DTOs via class-transformer. Note that you can't use class-transformer to build entity instances - but you can use it to process the DTO (or rather convert the input into a validated DTO in the right shape).

Btw note that `assign` won't give you "new updated entity instance", it gives you the exact same entity instance as you give it in the input. You never get the same entity instance twice in a single context. In your example `updatedUserEntity === existingUserEntity`.
