### ISSUE TITLE
Nullable embeddable's getting hydrated to `undefined`

### ISSUE THREAD

**Issue by BennoDev** [mikro-orm/mikro-orm#3063]
**Describe the bug**

A nullable object embeddable like this: 

```ts
@Embeddable()
export class Permissions {
    @Property()
    foo!: string;

    @Property()
    bar!: number;
}

// Used in
export class User2 {
    // Other properties...
    @Embedded(() => Permissions, { object: true, nullable: true })
    permissions: Permissions | null = null;
}
```
Will be returned from a repository find call with `permissions` being `undefined`.
Given the type constraint and the default to `null` this was unexpected behaviour that caused a bug for us.

**To Reproduce**
See above

**Expected behavior**
Expected it to be `null`.

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | 16.13.1 |
| typescript | ^4.5.5  |
| mikro-orm | ^5.0.5  |
| postgres  | ^5.0.5 |

**Comment by B4nan** [comment]
That's weird, for regular entity properties it should work this way, so indeed a bug. Note that it won't work for nested embeddables, only for properties that actually represent a database column (with nested embeddables you would have to have the `null` stored in the JSON, then it would be hydrated as `null`). Also note that the property initializer is not used for hydration of existing entities.

**Comment by ml1nk** [comment]
If object is false it creates the columns permissions_foo and permissions_bar which are both nullable. If one of them is null (or both like when permissions is set to null) i expected it to be hydrated to null but i found undefined. If permissions is explicitly set to null it fails on flush inside nativeInsertMany (AbstractSqlDriver).

~~~
        const props = [...set].map(name => meta.properties[name] ?? { name, fieldNames: [name] });
        const fields = core_1.Utils.flatten(props.map(prop => prop.fieldNames));
~~~

name is permissions (!= permissions_foo and permissions_bar) which leads to an undefined inside fields.

Is it forbidden to declare an embeddable nullable without also setting object to true?

~~~
@Embeddable()
export class Permissions {
    @Property()
    foo!: string;

    @Property()
    bar!: number;
}

// Used in
export class User2 {
    // Other properties...
    @Embedded(() => Permissions, { object: false, nullable: true })
    permissions: Permissions | null = null;
}
~~~

**Comment by B4nan** [comment]
> If object is false it creates the columns permissions_foo and permissions_bar which are both nullable

If your embedded property is nullable, all its properties are nullable at the schema level, nothing we can do about that in inline mode. And with nullable db column you always get it hydrated to `null`, that is how SQL drivers work.

**Comment by ml1nk** [comment]
It was not about the nullable columns but situations where it is undefined instead of null or setting it to null breaks flush. Hopefully the following test cases are helping. I ran it on the current master. 

~~~ts
import { Embeddable, Embedded, Entity, MikroORM, PrimaryKey, Property } from '@mikro-orm/core';
import type { PostgreSqlDriver } from '@mikro-orm/postgresql';

@Embeddable()
export class A {

  @Property()
  alpha!: number;

  @Property()
  beta!: number;

}

@Entity()
export class B {

  @PrimaryKey()
  id!: number;

  @Embedded({ entity: () => A, object: false, nullable: true })
  a!: A  | null;

  @Property()
  v!: boolean;

}

@Entity()
export class C {

  @PrimaryKey()
  id!: number;

  @Embedded({ entity: () => A, object: false, nullable: true })
  a: A  | null = null;

  @Property()
  v!: boolean;
}

describe('GH issue XXXX', () => {

  let orm: MikroORM<PostgreSqlDriver>;

  beforeAll(async () => {
    orm = await MikroORM.init({
      entities: [A, B, C],
      dbName: `mikro_orm_test_gh_xxxx`,
      type: 'postgresql',
    });
    await orm.getSchemaGenerator().ensureDatabase();
    await orm.getSchemaGenerator().dropSchema();
    await orm.getSchemaGenerator().createSchema();
  });

  afterAll(() => orm.close(true));

  test('B', async () => {
    let e = orm.em.create(B, { v: false });

    // eslint-disable-next-line no-console
    console.log(e.a); // undefined => expected null

    await orm.em.persistAndFlush(e);


    // eslint-disable-next-line no-console
    console.log(e.a); // undefined => expected null

    orm.em.clear();

    e = (await orm.em.find(B, { v: false }))[0];

    // eslint-disable-next-line no-console
    console.log(e.a); // undefined => expected null

    e.a = null;
    e.v = true;

    await orm.em.flush(); // runs smoothly


    orm.em.persist(orm.em.create(B, { v: false }));
    orm.em.persist(orm.em.create(B, { v: false }));

    await orm.em.flush(); // working, because a is not set

    orm.em.persist(orm.em.create(B, { v: false, a: null }));
    orm.em.persist(orm.em.create(B, { v: false, a: null }));

    await orm.em.flush(); // TypeError: Cannot read properties of undefined (reading 'replace')
  });


  test('C', async () => {
    let e = orm.em.create(C, { v: false });

    // eslint-disable-next-line no-console
    console.log(e.a); // null

    await orm.em.persistAndFlush(e);

    // eslint-disable-next-line no-console
    console.log(e.a); // null

    orm.em.clear();

    e = (await orm.em.find(C, { }))[0];

    // eslint-disable-next-line no-console
    console.log(e.a); // undefined => expected null

    e.a = null;
    e.v = true;

    await orm.em.flush(); // runs smoothly


    orm.em.persist(orm.em.create(C, { v: false }));
    orm.em.persist(orm.em.create(C, { v: false }));

    await orm.em.flush(); // TypeError: Cannot read properties of undefined (reading 'replace')
  });


});
~~~

**Comment by ml1nk** [comment]
@B4nan Just for clarification, it is now clear to you what i meant and you approve my expectations?

**Comment by B4nan** [comment]
Well, the first two "assertions" in the first test are wrong, `B.a` is supposed to be undefined, as the entity was just created/flushed, that is correct/expected behaviour. We dont fill `null` anywhere, it needs to come from you (constructor/property initializer) or from the database.

The fact that the flushing throws is a bug for sure. The third assertion that tests entity returned from database looks suspicious, but it might be an implementation edge case
