### ISSUE TITLE
Allow entity types to be pre-defined

### ISSUE THREAD

**Issue by carlosV2** [mikro-orm/mikro-orm#3066]
**Is your feature request related to a problem? Please describe.**
I'm building a new Custom Type but it is frustrating that it can only be instantiated from within the entity decorator. The Type I'm building has a dependency on a rather complex object. Put it simple, it wouldn't be feasable to construct such dependency on the decorator.

For example, given a Type like this:
```ts
import { Type } from '@mikro-orm/core';

export class MyCustomType extends Type<MyObject, string> {
   public constructor(manager: Manager) {
      // ...
   }

   // ...
}
```

It could happen that `Manager` has certain complexity to construct so, the following would simply be impractical:
```ts
import { Entity, Property } from '@mikro-orm/core';
import { v4 } from 'uuid';

@Entity()
export class MyEntity {
   @Property({ type: new MyCustomType(/* complex construction code */) })
   myObject: MyObject;
}
```

**Describe the solution you'd like**
I think adding a new key to the `MikroORM.init()` function to add custom types shouldn't be that difficult. Admitedly, I haven't taken a look at the code yet but seeing that the decorator also takes an string suggests to me that there might be some sort of resolution of types later on so, my proposal would be something like this:
```ts
const manager = /* complex construction code */;
const myCustomType = new MyCustomType(manager);

MikroORM.init({
   customTypes: {
      my_custom_type: myCustomType
   },
   // ...
});
```

With this code and given the beforementioned ability to resolve types on run time, the entity would then be like:
```ts
import { Entity, Property } from '@mikro-orm/core';
import { v4 } from 'uuid';

@Entity()
export class MyEntity {
   @Property({ type: 'my_custom_type' })
   myObject: MyObject;
}
```

**Describe alternatives you've considered**
The simplest solution to this problem would be to abstract the complex construction into a module and import it on any required file. However, this is not always posible as, in my case, I'm constructing the manager with a container.

**Additional context**
In addition to this problem, sometimes some data needs to be asynchronously retreived (for example, an object loaded from a different DB, API, etc). I've noticed that there isn't a single mention of Types returning promises. Is it possible? If not, I can raise another issue for this matter plus I don't think it would be that difficult to achieve since the core should run in an asynchronous context anyway.

**Comment by B4nan** [comment]
Generally speaking, types should be stateless and you should not instantiate them, rather pass the class as in `@Property({ type: MyCustomType })` which will then use a singleton instance. 

Anyway, you can already handle this via custom driver (extending the one that you want to use), there is this method that picks mapped type implementations based on the property metadata:

https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/platforms/Platform.ts#L224

You could also try to monkey patch it instead of extending the driver. We can try to expose this via configuration. 

>  I've noticed that there isn't a single mention of Types returning promises. Is it possible? If not, I can raise another issue for this matter plus I don't think it would be that difficult to achieve since the core should run in an asynchronous context anyway.

I don't plan to support async custom types, this would require making _many_ methods async, including things like `em.create/assign/map`, pretty much everything would need to be async. Huge breaking change, and probably also huge performance penalty (as we would need to await every single hydration of every single property - we use mapped types internally for all props). Mapped types need to be fast, this feels like you want to use a wrong tool for the problem you are trying to solve (which you haven't really described btw). If you need async, use hooks/event subscribers. Event subscribers can be even created via some DI containers and registered dynamically, if you need to work with some dependencies, that seems to be the right tool for the job.

**Comment by carlosV2** [comment]
@B4nan oh! thanks for the advice!

I've been playing with the Driver/Platform and it seems to work great.

The reason why I need all this is because I have an entity that stores an Stripe object with all the associated data. The thing is that every time I need to manipulate this entity, I need to load the Stripe object from the API so I though on making it more transparent by allowing it to "store" the object to the database by storing its id and seamingly retrieving it when the entity is loaded thus making the work with those entities more transparent.
This is also the reason why I need the custom Type to accept an instance created from the DIC.

I understand what you said about awaiting for the promises to complete, it makes sense. I still think there are some use cases for this but I guess they are a bit of an edge case if nobody else really needs it.
I'll definitely take a look at the subscribers but, otherwise, I'll see if I can work with Promises as parameter types.

Anyway, thanks for your help!
