### ISSUE TITLE
Utilizing multiple databases at the same time.

### ISSUE THREAD

**Issue by dougg0k** [mikro-orm/mikro-orm#314]
Hello,

I wanted to ask if it's possible to use multiple databases at the same time e.g., PostgreSQL and MongoDB, only by changing connection configuration?

Given the Entity implementing their respectives db Entity interface, it would automatically utilize the db connection, if specified.

**Comment by B4nan** [comment]
Not really supported, mongo entity needs to have `_id: ObjectId` PK, which is not valid for SQL drivers. You might be able to get around that by implementing custom type for the PK. Other than that it might work, but you will need to have 2 separate instances of the ORM.

What is the purpose/goal? Do you want to have some entities in SQL and some in mongo? If so, just use different directories for that (or use `entities` array instead of `entitiesDirs`). I do not see much sense in having the same entities/data in both SQL and mongo. (I could understand using pg for production and sqlite for testing - that is supported, entity definition for SQL drivers is compatible).

**Comment by dougg0k** [comment]
Yes, some in SQL and some in Mongo. When I asked I was thinking more in the same config file and entities folder. But separate entities folder & config file also works. Thanks.

**Comment by dimpdash** [comment]
Our team has two databases and large entities of the same type and so some of their content is stored inside an s3 bucket rather than normal database.
