### ISSUE TITLE
Use alternatives to ts-node

### ISSUE THREAD

**Issue by Gin-Quin** [mikro-orm/mikro-orm#3241]
**Is your feature request related to a problem? Please describe.**

`ts-node` is infamously slow and easily throws errors. In my case `ts-node` crashes whenever I try to import another .ts file, complaining: "cannot use require in an ESM module" (issue here: https://github.com/nodejs/node/issues/32103).

Nowadays there are far better tools to run arbitrary Typescript:

- [@digitak/esrun](https://www.npmjs.com/package/@digitak/esrun)
- [esno](https://www.npmjs.com/package/esno)

These new runners use Esbuild instead of tsc to run typescript and are much more resilient to the CJS - ESM compatibility issues. 99% of the time they work "out of the box" without a need for extra config, and they are much faster than ts-node.

**Describe the solution you'd like**
The possibility to use another Typescript runner than ts-node.

For example, add the following option in package.json:

```json
   "mikro-orm": {
      "useTypescriptRunner:" "esrun",
   }
```

**Comment by B4nan** [comment]
ts-node is not slow, you just need to disable type checking via `-T` or `transpileOnly` flag. Also this is fully opt in, you can disable ts-node and use whatever you want. Esbuild is not an option as it does not support decorator metadata. 

Also ts-node is compatible with ESM, you just need to use `ts-node-esm` binary instead of just `ts-node`.

> 99% of the time they work "out of the box"

Funny, they never worked out of box for me, not even once.

**Comment by B4nan** [comment]
> As said in the documentation, MikroORM expects the option "useTsNode": true in package.json

That is a flag only for the CLI, so it knows it should register ts-node to have out of box support for TS files. Nothing related to running apps. MikroORM does not register ts-node when you run apps, that is up to you to do it. It just tries to detect it and based on that picks the config options (e.g. `entitiesTs`). You can enforce the value via `tsNode` config option instead of depending on the auto detection.

> How to tell MikroORM to use ts-node-esm instead of ts-node?

Just use it yourself to run the script, you don't have to depend on ORM registering TS support for you, you can always just plug it in yourself before you even get to the ORM code. You can do that even for the CLI, something like `ts-node-esm node_modules/.bin/mikro-orm debug`.

**Comment by Gin-Quin** [comment]
This issue becomes more of a question, but when I execute a migration command, like this:

```
npx mikro-orm migration:up
```

Then MikroOrm is going to use `ts-node` if the option is turned on in package.json, and `node` otherwise (but then migrations must be written in JS).

Same goes for seeding. Let's say I've written some seeders in Typescript. I want to execute them with the command:

```
npx mikro-orm seeder:run
```

Is it possible to run the migration or the seed commands with `ts-node-esm`? I guess MikroOrm uses `ts-node` internally to run the different scripts.

I can use `ts-node-esm` or whatever I want for my own scripts, but from what I understand when executing migrations or seeding there is no "script" to run.

**Comment by B4nan** [comment]
> Then MikroOrm is going to use ts-node if the option is turned on in package.json, and node otherwise (but then migrations must be written in JS).

MikroORM does not _use node_, you are using `npx` which uses `node`. And just like that, you can use `ts-node-esm` or any other script to run and register what you want.

And neither it does use `ts-node` to run things, it just registers it: 

https://github.com/mikro-orm/mikro-orm/blob/972e5bac8d679303422a07a19b07a352529c4ff6/packages/core/src/utils/ConfigurationLoader.ts#L103

During that we use your `tsconfig.json`. 

I already showed how you can use `ts-node-esm`, something like this should work:

```bash
ts-node-esm node_modules/.bin/mikro-orm debug
```

Note that `ts-node-esm` is a binary, but its coming from the very same package.

**Comment by Gin-Quin** [comment]
`node_modules/.bin/mikro-orm` is a shell file, it makes no sense to pass it to `ts-node-esm` (which expects a Typescript file) 🤔

**Comment by B4nan** [comment]
This is how NPM CLI commands work, its a JS file, have you even opened it? This starts to feel like you are questioning quite a basic things that are totally unrelated to your problem, I am sorry but I dont have time to argue about this.

**Comment by Gin-Quin** [comment]
Of course I tried it.

And that's weird, because when I look at the package the `node_modules/.bin/mikro-orm` should indeed be a Javascript file, but when I actually installed `@mikro-orm/cli` and looked for the file, I found the following shell file:

```sh
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/Users/Lepzulnag/Code/talers/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="$NODE_PATH:/Users/Lepzulnag/Code/talers/node_modules/.pnpm/node_modules"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../@mikro-orm/cli/cli.js" "$@"
else
  exec node  "$basedir/../@mikro-orm/cli/cli.js" "$@"
fi
```

But I think it's actually a script file installed by pnpm (that I used) whose role is to call `cli.js` from mikro-orm.

Anyway, even if `node_modules/.bin/mikro-orm` is a Javascript file it makes no sense to pass it to `ts-node`. Javascript files can be executed with `node` ; using `ts-node-esm` instead will make no difference.

**Comment by B4nan** [comment]
Interesting, that must be indeed some pnpm related magic, can't really help with that. With yarn or npm you would see the `cli.js` file there directly. You might be able to use [`NODE_OPTIONS`](https://nodejs.org/api/cli.html#node_optionsoptions) env var.

Anyway, instead of the path to `.bin` you could use path directly to the `@mikro-orm/cli` package and use that file anyway, regardless of the pnpm thingy.

**Comment by B4nan** [comment]
Lastly, you can always create your own file, do whatever you want in there (e.g. register any kind of ts-node alternative or use it to execute that file...), and use the CLI programatically. If you want the same interface, just import the `cli.js` file.

**Comment by Gin-Quin** [comment]
Alright, thanks!

**Comment by Maikpwwq** [comment]
Config ["type": "module"] in package.json, tsconfig.json to [ts-node's ESM support](https://www.npmjs.com/package/ts-node#native-ecmascript-modules) and pass the loader flag to node in scripts, `node --loader ts-node/esm ./index.ts`.

```
{
  "compilerOptions": {
    "strict": true,
    "module": "ESNext", // ES2020
    "target": "ES2020",
    "moduleResolution": "Node",
    "lib": ["DOM", "DOM.Iterable", "ESNext"],
    "types": ["vite/client"],
    "jsx": "react-jsx",
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true
  },
  "ts-node": {
    "experimentalSpecifierResolution": "node",
    "transpileOnly": true,
    "esm": true,
  }
}
```
