### ISSUE TITLE
Running npx mikro-orm migration:create ignores database <> code differences and relies on .snapshot-mydatabase.json instead, even though migrations have not been migrated yet.

### ISSUE THREAD

**Issue by woltob** [mikro-orm/mikro-orm#3259]
**Describe the bug**
Running `npx mikro-orm migration:create` twice or after deleting the newly created migration file would not produce another one even though the migrations have not been persisted/migrated to the database via `npx mikro-orm migration:up`.

Is this a bug or expected behavior? I was just seeing that there is a new snapshot file created in v5.2 after upgrading from v4.5.10.

**Stack trace**
```
...
```

**To Reproduce**
Use Postgres, running NestJS.

**Expected behavior**

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | v16.15.1 |
| typescript | ^4.5.5 |
| mikro-orm | 5.2.1 |
| your-driver | postgres |

**Comment by B4nan** [comment]
Thats a feature, not a bug.

**Comment by woltob** [comment]
Alright, did not expect it as running `migration:create` twice then prints `No changes required, schema is up-to-date.`. One suggestion: Perhaps you could print a HINT (especially for people upgrading to v5) that it checks against a new snapshot file and not the actually database.

Another thing I've noticed upgrading:
```
  @Property({ type: JsonType, nullable: true })
  @Field((_type) => DevicePermissions)
  public permissions?: TDevicePermissions;
```
@Field are GraphQL definitions.  I had `type: DevicePermissions` set for MikroORM config and it did not get recognized as JSON (preferably jsonb) even though DevicePermissions is a custom type (object). 

Great work, loving 5.2. so far!

**Comment by B4nan** [comment]
> I had type: DevicePermissions set for MikroORM config and it did not get recognized as JSON (preferably jsonb) even though DevicePermissions is a custom type (object).

We can have only one default mapping, it used to be object, and it was a very bad default to be honest, mainly because many people simple dont understand the limitations of reflect metadata and expect things to just work (like `id: number | null`, guess what reflect metadata gives you for the type - `object`, which used to be mapped to `jsonb`). In v5 the default mapping is string, you need to set object properts explicitly (its enough to put there `type: 'json'` btw). There were many people struggling because they defined the PK badly in the first place, created schema with JSON columns for PKs and it was nearly impossible to fix that without wiping the schema (although v5 should be capable of that too).
