### ISSUE TITLE
Support for Dynamic Schema Migration

### ISSUE THREAD

**Issue by ProjectBay** [mikro-orm/mikro-orm#3319]
**Is your feature request related to a problem? Please describe.**
In a schema-based multi-tenancy environment, you have to keep track of each tenants migration. 
But maintaining migration files for each tenant is not optimal.
Therefore, having dynamic schema migrations seems like a good solution.

**Describe the solution you'd like**
The developer could migration files like this:
```javascript
await migrator.createMigration({dynamicSchema: true})
```
```javascript
export class Migration20200726091345 extends Migration {
    async up(schema: string): Promise<void> {
        this.addSql(`create table "${schema}.user" ("id" serial primary key, ...);`);
    }
}
```
```javascript
await migrator.up({schema: 'tenant-123'})
```

**Additional context**
The issue has been mentioned first by this https://github.com/mikro-orm/mikro-orm/issues/681
Since v5, EntityManager is schema supported. It would be nice to have it for the migrator too.
more references:
• https://thomasvds.com/schema-based-multitenancy-with-nest-js-type-orm-and-postgres-sql/#creating-tenants-migrations

Another solution could be, that the migrator respects the schema argument inside the MikroOrm Config file and executes the migration queries encapsulated on that schema.
When creating the migration, we would still have to assign it being dynamic, since the SQL migration query should be referencing tables without any schema specification.

**Comment by B4nan** [comment]
As [the docs says](https://mikro-orm.io/docs/multiple-schemas#note-about-migrations), wildcard schema entities are ignored in migrations due to their dynamic nature. The problem with the approach you are suggesting is that we need to generate the schema diff from something. How can we know what schema to use? Or is this just about support for running migrations, and you would be ok with adding the queries yourself?

**Comment by ProjectBay** [comment]
Thank you i got it working!
