### ISSUE TITLE
Use defined entity as pivot table for many to many

### ISSUE THREAD

**Issue by ryankauk** [mikro-orm/mikro-orm#333]
**Is your feature request related to a problem? Please describe.**
I just started utilizing the package and was trying to create a schema with a many to many relation with a pivot table. I would like to use the entity I define to add additional columns to the pivot table. When I try to use the same name it throws an error saying that the table already exists.

ie.

```typescript

@Entity()
export class Relationship extends BaseEntity {

    @ManyToOne()
    follower!: User;

    @ManyToOne()
    leader!: User;

    @Enum()
    status!: RelationshipStatus;


    constructor() {
        super();
    }

}


@Entity()
export class User extends BaseEntity {
    @ManyToMany({ entity: () => User, inversedBy: u => u.leaders, pivotTable: 'relationship', owner: true, joinColumn: 'follower', inverseJoinColumn: 'leader' })
    followers = new Collection<User>(this);

    @ManyToMany(() => User, u => u.followers, { hidden: true })
    leaders = new Collection<User>(this);

    constructor() {
        super();
    }

}
```

**Describe the solution you'd like**
Possibly allow Entity as well as string for pivotTable input

Is there a workaround you could recommend to accomplish this? Thanks 🙏

**Comment by B4nan** [comment]
If you need additional columns in the pivot table, then it is no longer pivot table. You should use 1:m instead.

Here are some links about this (its about doctrine, but it applies here as well):

> Why are many-to-many associations less common? Because frequently you want to associate additional attributes with an association, in which case you introduce an association class. Consequently, the direct many-to-many association disappears and is replaced by one-to-many/many-to-one associations between the 3 participating classes.

https://stackoverflow.com/questions/18655286/doctrine-2-how-to-handle-join-tables-with-extra-columns
https://future500.nl/articles/2013/09/06/
https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/association-mapping.html

**Comment by ryankauk** [comment]
I see thank you, this is how I was think about working around it anyways, I see that that's the intended use. Thanks for the info

**Comment by thebergamo** [comment]
@B4nan sorry for commenting in an old issue. 
Won't be the case to have some of these suggestions on the documentation?
But why? You might be wondering, by default any M:N association should become a 1:N in both ways in order to work (So, the pivot table), but in the example from the docs, having this `OrderItem` pivot table at least for me it suggested (and I see many others had similar thought, based on many issues with similar content) that I could simply have such thing and basically populate these columns (as the Pivot table for instance) automatically or simply adding one item to the collection.

If you agree, I can provide a PR with this information added or maybe a simplified way to populate (while creating) such properties directly with this simplified approach.

```ts
const order: Order = repo.create({ paid: true, shipped: false, ...others});
order.products.add(new OrderItem({ product: Referece.createFromPK(Product, 1), amount: 3}));

```

Or something similar to that.
