### ISSUE TITLE
collection.remove() silently failing when entity is not an exact reference

### ISSUE THREAD

**Issue by jnorris441** [mikro-orm/mikro-orm#3394]
**Describe the bug**

Passing an entity into collection.remove for a M:M unidirectional relation doesn't do what I expected.

If the entity object you pass in is not the same exact reference it will fail because the underlying ArrayCollection.items is a Set. ArrayCollection.remove() fails silently when this.items.delete() fails.

**To Reproduce**

This does not work:

```
let tag = await tagRepo.findOne({ id: tagId })
let media = await mediaRepo.findOne({ id: mediaId }, { populate: ['tags'] })
media.tags.remove(tag)
await mediaRepo.persistAndFlush(media)
```

However, this works:

```
let media = await mediaRepo.findOne({ id: mediaId }, { populate: ['tags'] })
let mediaTag = media.tags.getItems().find((tag) => tag.id === tagId)
media.tags.remove(mediaTag)
await mediaRepo.persistAndFlush(media)
```

**Expected behavior**
I was expecting it to look at the primary key of the entity I passed in and remove it from the collection.

**Versions**

| Dependency | Version |
| - | - |
| node | v16.13.2 |
| typescript | 4.7.4 |
| mikro-orm | 5.2.3 |
| @mikro-orm/sqlite | 5.2.3 |

**Comment by B4nan** [comment]
Hard to call this a bug, but yes, we could validate it probably.

**Comment by B4nan** [comment]
Please provide complete repro, you code should actually work, unless you do something wrong with your DI container.

**Comment by B4nan** [comment]
> mediaRepo and tagRepo are each created from orm.em.fork().getRepository()

Ok, that shouldn't work. Why would you do that?

> assuming you are relying on some kind of internal cache

Its not some kind of internal cache, its called [identity map](https://mikro-orm.io/docs/identity-map), if you dont know what it is, go read the docs, its a core concept of this ORM :] 

The problem here is you call `collection.remove()` with a reference that is not present in the collection (better say, entity managed by different EM) => such item is not there. We dont check the PK, that would be unnecessary slow in case the PK is  complex (e.g. composite PK from multiple FKs), and it woudnt work at all for not persisted entities. And we dont throw if a remove call does not find a match, changing this would be breaking, so no plans for that either.

> So maybe this issue is just about trying to use entities across forks.

This will never work, its a non-goal. You should not mix forks. Using `em.fork().getRepository()` to me seems like an antipattern, if something, you should create the fork and reuse that to get more repositories. Having each repository based on different fork will break things.

I can think of a validation for the correct EM (check if the owner if managed by same EM as the item you try to remove).

**Comment by B4nan** [comment]
Oh thanks for the downvote 🤷 If you see it this way, lets close it right ahead. I tried to explain what and why in detail, and this is what I get 🤷
