### ISSUE TITLE
Cannot use mikro-orm-cli in TypeScript with ESM and NodeNext module resolution

### ISSUE THREAD

**Issue by lixiang810** [mikro-orm/mikro-orm#3485]
## Describe the bug

With these configuration, `mikro-orm` command will not work as expected.

```json
// package.json
"type": "module",
"mikro-orm": {
  "useTsNode": true
}
```

```json
// tsconfig.json
  "compilerOptions": {
    "target": "ESNext",
    "module": "NodeNext",
    "moduleResolution": "NodeNext"
  }
  "ts-node": { "esm": true }
```

For reprodution, error stack and more details, see https://github.com/lixiang810/mikro-orm-repro

**Comment by B4nan** [comment]
You can see working ESM project here: https://stackblitz.com/fork/mikro-orm-esm-repro

The trick is the `ts-node/esm` loader, otherwise you can't dynamically load a TS file. I am not aware of any way to achieve this automatically.

**Comment by lixiang810** [comment]
> huh the repro did not have the script for CLI

I'm sure that `npm exec mikro-orm` works without adding it to script section.

**Comment by B4nan** [comment]
> I'm sure that npm exec mikro-orm works without adding it to script section.

The reason for NPM script is to have the loader registered. 

I see you even found out the trick with loaders yourself. Next time I would appreciate you put such information into the issue description. IMHO this is a wontfix, you already do the right thing to solve it. Just wrap it into NPM script.

**Comment by B4nan** [comment]
Just to shed a bit more light into this - AFAIK the `ts-node-esm` works pretty much the same as the proposed workaround here, it spawns new node process with the loader. We can't do this from inside the ORM automatically (at least I am not aware of any way).

I will be definitely experimenting with this more, especially because the new getting started guide I am working on is ESM and also talks about this problem - and I would very much like to not mention it at all and have things working out of box... But I dont think they can at this point.

**Comment by B4nan** [comment]
FYI open a GH discussion to verify we can't do better:

https://github.com/TypeStrong/ts-node/discussions/1880

**Comment by B4nan** [comment]
I think we could do one thing - we could expose `mikro-orm-esm` script, which would automatically register the ts-node/esm loader. It sounds a bit confusing as you need it only for TS projects (and it will require ts-node to be installed), but I guess its better than describing this loader env vars and stuff.

**Comment by alexojegu** [comment]
I am trying ESM, but when I use `mikro-orm-esm` I only get:
```
npx -w @tattoo/server mikro-orm-esm schema:create -r
/usr/bin/env: «node --loader ts-node/esm --no-warnings»: The file or directory does not exist
/usr/bin/env: use -[v]S to pass options in shebang lines
```

When I use a package.json script:
```
"mikro-orm": "NODE_OPTIONS='--loader ts-node/esm --no-warnings' mikro-orm"
```
All work as expected:
```
npm -w @tattoo/server run  mikro-orm schema:create -- -r

> @tattoo/server@0.0.1 mikro-orm
> NODE_OPTIONS='--loader ts-node/esm --no-warnings' mikro-orm

Schema successfully created
```

**Comment by B4nan** [comment]
Well, that sounds like `npx` bug, nothing I can help with. Maybe try moving the workspace argument to different place.

**Comment by alexojegu** [comment]
After see the CLI code and how you register the `ts-node/esm`:

https://github.com/mikro-orm/mikro-orm/blob/307d3a1dae1ababbb47595fe70b0888de3b9a557/packages/cli/src/esm.ts#L1

I have changed in my `node_modules/@mikro-orm/cli/esm.js` this:
```
#!/usr/bin/env node --loader ts-node/esm --no-warnings
```
by this (see the `-S`):
```
#!/usr/bin/env -S node --loader ts-node/esm --no-warnings
```

And all work as expected:
```
npx -w @tattoo/server mikro-orm-esm schema:create -r
Schema successfully created
```

**Comment by B4nan** [comment]
Interesting, PR welcome 👍

**Comment by nicomouss** [comment]
I am facing overall the same problem here regarding `ts-node` with ESM projects.

`ts-node` is actually the reason I have switched to `tsx` in my projects. `tsx` works great out of the box to execute TypeScript files, ESM projects or not. Never met any problems like the one I constantly got while using `ts-node` ...

Anyway, I have just (re)-installed `ts-node` in the hope to use mikro-orm CLI with a `mikro-orm.config.ts` typescript file. Only to face those problems described here, and again being frustrated by `ts-node`.

Would the option to be able to use `tsx` instead of `ts-node` something to be considered in Mikro-orm CLI ?

@B4nan `tsx` with mikro-orm works actually great if you use `EntitySchema` to define your entities (no decorator on entities, thus no reflect-metadata nor ts-morph in use). That's what I have been using while working with `mikro-orm` in my projects. Faster than `ts-node`, no headache anymore with ESM project. The only thing missing would be to have the option to make the CLI use `tsx` instead of `ts-node` in that case.

At the moment, I use the Migrator and SchemaGenerator programatically instead of the CLI, so I can execute everythings with `tsx`. Although would be nice to use the CLI if it could work out of the box with `tsx`.

**Comment by ademkoc** [comment]
I made a simple test with tsx for cli and it worked. You can try this script. @nicomouss
`NODE_OPTIONS='--import=tsx' MIKRO_ORM_CLI_ALWAYS_ALLOW_TS=1 mikro-orm migration:create`

**Comment by nicomouss** [comment]
> I made a simple test with tsx for cli and it worked. You can try this script. [@nicomouss](https://github.com/nicomouss) `NODE_OPTIONS='--import=tsx' MIKRO_ORM_CLI_ALWAYS_ALLOW_TS=1 mikro-orm migration:create`

Yes man that's very neat. Another solution I had opted to was to directly target the CLI executable with tsx:

```bash
npx tsx ./node_modules/@mikro-orm/cli/cli.js migration:create
```

Although your solution is definitely more elegant.

To make things even better, I suggest to configure things like so in package.json:

```json
{
  ...
  "mikro-orm": {
    "alwaysAllowTs": true,
    "useTsNode": false,
    "configPaths": [
      "./path/to/your/mikro-orm.config.ts"
    ]
  }
  ...
}
```

Then the command becomes the following:

```bash
NODE_OPTIONS="--import=tsx" npx mikro-orm migration:create
```

plus now without the mikro-orm warnings that ts-node is not installed.

Thanks for your contribution !
