### ISSUE TITLE
Create entity if not found

### ISSUE THREAD

**Issue by KevinMusgrave** [mikro-orm/mikro-orm#3515]
### Is your feature request related to a problem? Please describe.
I'd like to be able to check if an item already exists in the db, and if not, create it. Basically something like [Django's `get_or_create` function](https://docs.djangoproject.com/en/dev/ref/models/querysets/#get-or-create).

### Describe the solution you'd like
Something like this I guess:

```javascript
async function findOrCreate(em, type, props) {
  let x = await em.findOne(type, props);
  if (!x) {
    x = em.create(type, props);
  }
  return x;
}
```

**Comment by B4nan** [comment]
I think I would rather have something like `em.ensure(entity)` or `em.upsert(entity)`, both would automatically run the insert query if match is not found - depends on the driver support, but this would generally use `insert on conflict update` (or maybe `ignore` and let the UoW do the updates). Also I dont think we should blindly use all the properties for the `findOne` check - if there is a PK like uuid, we can use that, otherwise it should probably just throw (or we can have fallback `where` parameter to allow explicit conditions).

There was some discussion about upserts here: #3293

**Comment by KevinMusgrave** [comment]
The upsert functionality sounds good to me.

**Comment by IgorArnaut** [comment]
> I think I would rather have something like `em.ensure(entity)` or `em.upsert(entity)`, both would automatically run the insert query if match is not found - depends on the driver support, but this would generally use `insert on conflict update` (or maybe `ignore` and let the UoW do the updates). Also I dont think we should blindly use all the properties for the `findOne` check - if there is a PK like uuid, we can use that, otherwise it should probably just throw (or we can have fallback `where` parameter to allow explicit conditions).
> 
> There was some discussion about upserts here: [#3293](https://github.com/mikro-orm/mikro-orm/issues/3293)

Why would you use upsert? Its purpose is to UPDATE an entity if it exists, not to FIND it. Why does everybody recommend upsert?

**Comment by B4nan** [comment]
`em.upsert` will return a full entity instance, so it does act as a FIND too. If you want to skip the updates, you can use `onConflictAction: 'ignore'`.
