### ISSUE TITLE
entity.assign(...) crash with combo of managed entities

### ISSUE THREAD

**Issue by rvion** [mikro-orm/mikro-orm#3571]
**Describe the bug**

assigning a `managed, freshly created, entity` to another `managed, freshly created, entity` via `entity.assign` (inherited from BaseEntity) crash with an error message saying the entity is not managed.

error message says:
`To use assign() on not managed entities, explicitly provide EM instance: wrap(entity).assign(data, { em: orm.em })`

Assigning it via `em.assign` works.

entity.assign

minimal repro: 

https://stackblitz.com/edit/mikro-orm-repro-mcfbsu?file=test.ts

```ts
@Entity()
export class Foo {
  @PrimaryKey()
  id!: number;
}

@Entity()
export class User extends BaseEntity<User, 'id'> {
  @PrimaryKey()
  id!: number;

  @ManyToOne(() => Foo) // you can specify type manually as a callback
  foo!: Foo;
}

orm = await MikroORM.init({
  type: 'sqlite',
  dbName: ':memory:',
  entities: [User],
  persistOnCreate: true, // 👈 persist on create
});


test('assign via em.assign', async () => {
  const em = orm.em.fork();
  const user = em.create(User, {}, { managed: true, persist: true }); // 👈 managed: true
  const foo = em.create(Foo, {}, { managed: true, persist: true }); // 👈 managed: true
  // vvvv DIFFERENCE HERE
  em.assign(user, { foo }); // 🟢 WORKS
  expect(user.foo).toBe(foo);
});

test('assign via BaseEntity.assign()', async () => {
  const em = orm.em.fork();
  const user = em.create(User, {}, { managed: true, persist: true }); // 👈 managed: true
  const foo = em.create(Foo, {}, { managed: true, persist: true }); // 👈 managed: true
  // vvvv DIFFERENCE HERE
  user.assign({ foo }); // 🔴 CRASH
  expect(user.foo).toBe(foo);
});

```

| Dependency | Version |
| - | - |
| node | v16.14.2 |
| typescript | Version 4.8.3 |
| mikro-orm | 5.4.2 |
| your-driver | Postgres |

**Comment by rvion** [comment]
not shown in the minimal repro: `entity.assign` works well for anything else other than an other freshly created entity.
assigning any scalars via entity.assign() work well. assigning an other entity fetched also works.

**Comment by B4nan** [comment]
`managed: true` does not mean the entity will become managed automatically (yes, weird naming) - this basically controls the constructor usage, as for managed entities we dont call constructors and rather build the instance via `Object.create()`. 

This is documented in the `em.create()` jsdoc: 

> Creates new instance of given entity and populates it with given data.
The entity constructor will be used unless you provide `{ managed: true }` in the options parameter.
The constructor will be given parameters based on the defined constructor of the entity. If the constructor
parameter matches a property name, its value will be extracted from `data`. If no matching property exists,
the whole `data` parameter will be passed. This means we can also define `constructor(data: Partial<T>)` and
`em.create()` will pass the data into it (unless we have a property named `data` too).

That `persist: true` is also wrong assumtion - you dont need to persist it, you need to merge it.

```ts
const em = orm.em.fork();
const user = em.create(User, {}, { managed: true, persist: true }); // 👈 managed: true
const foo = em.create(Foo, {}, { managed: true, persist: true }); // 👈 managed: true
user.assign({ foo });
expect(user.foo).toBe(foo);
```

**Comment by rvion** [comment]
thanks a lot for the quick answer ! 🙏

(I don't know if you plan to do something in the code or in the docs, so I'll leave this open and let you close it when you want)

**Comment by B4nan** [comment]
Btw technically all you need to do to create managed entity instance is `em.merge(User, { ... })`, as it accepts POJOs too this way. 

Note that in your repro you create managed entity without providing any data. That itself doesnt make any sense - managed entity needs to have at least the primary key (plus any other non-null value).

**Comment by rvion** [comment]
> Btw technically all you need to do to create managed entity instance is em.merge(User, { ... }), as it accepts POJOs too this way.

thanks for the tip !

> Note that in your repro you create managed entity without providing any data. That itself doesnt make any sense - managed entity needs to have at least the primary key (plus any other non-null value).

yeah, sorry for the too-minimal repro, in my project, those entities are indeed both created with primary keys

**Comment by B4nan** [comment]
> what I am missing, why can't A.assign({ message: B }) just work by default ?

Because none of those entities are managed = they dont have the reference to the EM. And I kinda doubt this is actually happening, the EM will be required only if you try to work with FKs instead of entities, e.g. `assign({ rel: 1 })` and not `assign({ rel: new Rel() })`.

> em.merge(B) is not really an option, as it leads to B not being persisted, since merge reset the diff

What you apparently failed to understand is what `em.merge()` is for. It makes entity managed, just like if it was loaded from database = after that call, there cant be any queries done by flush, as it saves the snapshot. You need to merge the entity, and modify/mutate its state afterwards - those changes will be respected during flush.

Maybe first try to explain what this snippet should be actually doing, as I have no idea. What queries do you want to achieve in the end?

Also note that `assign` was never really meant to be used for new entities, you should just use `em.create()`, it works out of box with complex inputs and builds the entity graph for you.

```ts
// this will create new user entity, that has 3 relation properties, all of them using FK, so they are considered as existing entities
const e = em.create(User, { 
  mother: 123,
  father: 321,
  books: [1, 2, 3],
});
```

Lastly, dont use the string signatures (dont use string name of entity class), your snippet is not type safe because of it.

**Comment by rvion** [comment]
@B4nan 

> I kinda doubt this is actually happening, the EM will be required only if you try to work with FKs instead of entities, e.g. assign({ rel: 1 }) and not assign({ rel: new Rel() }). 

[here is a super tiny repro showing it happening](https://stackblitz.com/edit/mikro-orm-repro-mcfbsu?file=test.ts): https://stackblitz.com/edit/mikro-orm-repro-mcfbsu?file=test.ts


> Because none of those entities are managed = they dont have the reference to the EM. 

Is there a way for me to ensure all of my non-managed entities to hold a reference to EM ? I will always create them with `em.getRepository(...)create()` without having to implement custom repositories ?; I didn't ponder much on the `manged` vs `un-managed` debate; I just want `em.create` to use their constructor so I can assign default values.  My use-case is simple, I fork Em only once at the script start, then `em.create` entities, send them around, and sometimes assign them params, then at the very end of the script, I `flush` the `em`

> What you apparently failed to understand is what em.merge() is for. It makes entity managed, just like if it was loaded from database = after that call, there cant be any queries done by flush, as it saves the snapshot. You need to merge the entity, and modify/mutate its state afterwards - those changes will be respected during flush.

👍 

> Maybe first try to explain what this snippet should be actually doing, as I have no idea. What queries do you want to achieve in the end?

I just hope to be able to assign several times and the expected final query to be an insert that sets all the accumulated diffs done with successive assign. 

```ts
foo  = em.create(...)
foo.assign({a:1})
foo.assign({b:2})
// more stuff...
bar = em.create(...)
foo.assign({bar})
```
 => 

```sql
insert into bar (id) values('b7a1cdbe-8064-439b-a5b5-2d226bea6d5f')
insert into foo (a,b,bar_id) values (1,2,'b7a1cdbe-8064-439b-a5b5-2d226bea6d5f')
```

> Also note that assign was never really meant to be used for new entities, you should just use em.create(), it works out of box with complex inputs and builds the entity graph for you.

yes, I love how assign just works, that's why I was hoping I could just use-it several time successively on newly created instances before actually flushing the transaction.

**Comment by B4nan** [comment]
> Is there a way for me to ensure all of my non-managed entities to hold a reference to EM ? 

That is a definition of managed entity - that it holds the EM. Non-managed entity = no reference to EM.

I feel like you are not understanding our discussion. I told you how `em.create()` works with the `managed: true`, and that you _need_ to call `em.merge()` on that to actually make it managed. And I closed this issue with a commit, that automatically does that. If you update the ORM to latest dev version, your repro is not failing with that error anymore, as the `em.merge()` is called automatically. The test still fails, because you clearly still expect wrong outcome of this - if you create managed entity, it means the entity has to be already present in the database - that will never produce any insert query.

Adding both `managed: true` and `persist: true` is again misunderstanding of the concepts. Only not managed entities (those you want to produce insert statements) need to be persisted. Persisting managed entity is a no-op.

> // user.assign({ car: M.wrap(car).toReference() }); // ALT 4: 🔴 CRASH

You are not using [reference wrapper](https://mikro-orm.io/docs/entity-references#better-type-safety-with-referencet-wrapper) there, this makes no sense either. Feels like you just try different snippets you find in various places, without really understanding the options you are using :] 

I feel like you keep talking about several use cases at once. If you want to see insert queries, you cant create managed entities. And you cant use assign for what you want on not managed entities. But you try to make them managed and expect things to start working - and there is the fundamental misconception, if the entity is not already present in database, you cant just create a managed instance of it.

But I can also see that it does not behave exactly as expected, the `user.assign({ car })` fails if both entities are not managed, while it should fail only in case you do `user.assign({ car: 123 })`. Will try to fix that during the day.

**Comment by rvion** [comment]
@B4nan Argh ! 🤦 🤦 
My latest stackblitz was full of copy-pasta glitches, I didn't mean to write things like `managed: true` 🤦 
I also already use `"@mikro-orm/core": "5.4.3-dev.46"` in my personal project. 
The reference wrapper was also a copy-pasta error; 🤦  I use those wrapped refs in my project, but indeed does not in this stackblitz repro case 


--------

## Point A: `managed`: all clear now.

speaking about managed entities was wrong. I don't need to create `managed` entities.  Managed are for those that are already persisted; those fetched in the DB. I'll probably never or almost never need to `em.create(...,{managed:true})`. Usually, when I use create, I'll want sql to be emited when I'll flush. The fact that constructor is not called for managed entities also makes sense. all good.

## Point B: what I wanted to say

> But I can also see that it does not behave exactly as expected, the user.assign({ car }) fails if both entities are not managed, while it should fail only in case you do user.assign({ car: 123 }). Will try to fix that during the day.

yes, that's what I was trying to say;

my whole question should have been :

** how can I make this seemingly natural piece of code to work **

```ts
// Bar : {id: string}
// Foo: { id:string, a?: number, b?: number, bar?: Bar}

foo  = em.create(Foo, {id:'foo-1'})
foo.assign({a:1})
foo.assign({b:2})
bar = em.create(Bar, {id : 'bar-1'})
foo.assign({bar}) // 🔴
em.flush()

// insert into bar (id) values('bar-1')
// insert into foo (id, a, b, bar_id) values ('foo-1', 1, 2, 'bar-1')
```

The whole issue was juste about that x)

🙏 sincere thanks for you time !

**Comment by B4nan** [comment]
ok, [this](https://github.com/mikro-orm/mikro-orm/commit/6572a5946dd2c85124d934b8bd4de33751fdd680) should do it, the validation was indeed too strict. also found another bug in the assigning to collections.

**Comment by rvion** [comment]
Amazing. thanks!
