### ISSUE TITLE
Possibility to exclude loading relations during creating entity.

### ISSUE THREAD

**Issue by eugenedrvnk** [mikro-orm/mikro-orm#3610]
**Is your feature request related to a problem? Please describe.**
I have the next setup: 

```typescript
@Entity()
export class Author extends BaseEntity {
  @Property()
  name: string;

  @Property()
  email: string;

  @OneToMany(() => Book, b => b.author)
  books = new Collection<Book>(this);
}
```

```typescript
@Entity()
export class Book extends BaseEntity {

  @Property()
  title: string;

  @ManyToOne(() => Author,)
  author: Author;
}
```

I'm creating author like this:
```typescript
@Post()
  async create(@Body() body: any) {
    const author = this.authorRepository.create(body);
    await this.authorRepository.persist(author).flush();

    return author;
  }
```

And as result - receive 
```typescript
{
    "id": 10,
    "createdAt": "2022-10-18T22:41:39.749Z",
    "updatedAt": "2022-10-18T22:41:39.749Z",
    "name": "test",
    "email": "test",
    "books": []
}
```
I don't know, maybe it's possible (but I didn't find how), to exclude on "config" level of mikro-orm this "books" field and add it only on demand.

**Describe the solution you'd like**
As an only approach I've found, is to add constructor to Author class, and then create author with "new" operator, but it looks not very clear
```typescript
  constructor(name: string, email: string) {
    super();
    this.name = name;
    this.email = email;
    delete this.books;
  }
```

**Comment by B4nan** [comment]
You can mark it as `hidden` or use custom `toJSON` method:

https://mikro-orm.io/docs/serializing

This won't be an issue with a managed entity - there you would explicitly populate the collection, otherwise it woudn't be there. But in your case you create a new entity, and that by definition has initialized collections, hence they are present in the response.

> As an only approach I've found, is to add constructor to Author class, and then create author with "new" operator, but it looks not very clear

That's quite bad idea, you will break some of the internal persistence mechanisms. If something, do it inside your `create` method.
