### ISSUE TITLE
docs:  Mongodb ManyToMany in a separate collection rather than as field in the document

### ISSUE THREAD

**Issue by sushilkjaiswar** [mikro-orm/mikro-orm#3791]
Hi @B4nan 

In Mikro Orm there is a possibility of having separate pivot table for Mongoldb db rather than storing as list in the owners document? Please point to the documentation if this is a possibility. I went through online documentation where it points out that references are stores in owners file as a list but what happens if the data is large and it is a viable design to store into owners field as a list.

Example: Post and Comments relationship where each post can have large numbers of comments posted and I would like to have a another table post_comment_relation and Post entity pulls data from post_comment_relation table. Please share references if this is achieveable in Mikro Orm 's existing feature or I have to add custom code for this scenario.

**Comment by B4nan** [comment]
No, this is not possible. Mongo does not allow proper joining like SQL does (I know there is `$lookup`, but that isn't very usable due to perf limitations - you can't prune the results based on the joined values, so it ends up as full table scan equivalent of SQL queries).

You can always model this yourself as in this example: https://mikro-orm.io/docs/next/composite-keys#use-case-3-join-table-with-metadata

I don't think the `pivotEntity` trick will work in mongo for the reasons above, but you can try that as well.
