### ISSUE TITLE
cannot use read-only field for query filter

### ISSUE THREAD

**Issue by erie0210** [mikro-orm/mikro-orm#3836]
**Describe the bug**
Cannot use entity field for query fitler when it is readonly.
For example, when I declare `name` as readonly field in Author entity, and try to use it for `FilterQuery<Author>` ,
it throws this error. It would be better if I can use readonly field for filtering.

<img width="720" alt="Screen Shot 2022-12-08 at 7 56 04 PM" src="https://user-images.githubusercontent.com/91591854/206429399-ed617bd6-5c3a-4148-bf60-9d8b7ec7c917.png">

**Stack trace**
```
TS2322: Type '{ $gte: number; }' is not assignable to type 'FilterValue<string> | undefined'.   Types of property '$gte' are incompatible.     Type 'number' is not assignable to type 'ExpandScalar<FilterValue2<string>> | undefined'.
```

**To Reproduce**
made example PR based on nestjs-example-app

https://github.com/mikro-orm/nestjs-example-app/pull/50/files

**Versions**
"@mikro-orm/core": "^5.0.3",

Thanks :)

**Comment by B4nan** [comment]
Not reproducible with current versions, try upgrading, v5.0.3 is really outdated.

**Comment by B4nan** [comment]
Oh wait a sec, now I get it. `em.find(Author, { age: 50 })` works, the problem is when you instantiate the `FilterQuery` yourself and try to add it later. FYI for that you should be using `ObjectQuery` instead, but there it also don't work due to the property being readonly, that's indeed something to fix.
