### ISSUE TITLE
Upgrade Knex version

### ISSUE THREAD

**Issue by eduardofx** [mikro-orm/mikro-orm#3867]
@mikro-orm/cli@5.6.1

https://www.cve.org/CVERecord?id=CVE-2016-20018

Security information
Factors contributing to the scoring:
Snyk: [CVSS 8.6](https://security.snyk.io/vuln/SNYK-JS-KNEX-3175610) - High Severity

NVD: Not available. NVD has not yet published its analysis.
[Why are the scores different? Learn how Snyk evaluates vulnerability scores](https://docs.snyk.io/features/fixing-and-prioritizing-issues/issue-management/severity-levels#understanding-snyks-vulnerability-analysis)
Overview
[knex](http://knexjs.org/) is a query builder for PostgreSQL, MySQL and SQLite3

Affected versions of this package are vulnerable to SQL Injection due to missing escape of field objects, which allows ignoring the WHERE clause of a SQL query.

Note: Exploiting this vulnerability is possible when using MySQL DB.

**Comment by eduardofx** [comment]
@mikro-orm/cli@5.6.1

**Comment by B4nan** [comment]
Thanks for the note, I will release new patch version once the update is available. Right now I dont see any new knex versions, we depend on the latest one.

**Comment by biaomingzhong** [comment]
@B4nan Why is this being closed? The CVE issues are still showing. How do I bypass the CVE scanner?

**Comment by B4nan** [comment]
This is closed because it was never valid in the first place, it was open when we were on the latest version of knex (so there was nothing to do), and we are still on the latest version of knex now (so again, I don't understand what you expect from me now). Dependencies are updated automatically via renovate. If you have issues with knex's dependencies, why don't you tell them instead of me?

**Comment by biaomingzhong** [comment]
You are right, sorry to bother you.
