### ISSUE TITLE
Is there a createSchemaIfNotExist()?

### ISSUE THREAD

**Issue by ujwal-setlur** [mikro-orm/mikro-orm#416]
**Is your feature request related to a problem? Please describe.**
It looks like ```createSchema()``` will error out if the schema already exists. I have to wrap it in a ```try/catch``` block which is not ideal.

**Describe the solution you'd like**
```createSchemaIfNotExist()``` or something like that.

**Describe alternatives you've considered**
```try/catch``` block works, but not elegant.

**Comment by B4nan** [comment]
Why do you need to call it like this? Maybe `updateSchema` would fit better? It will create the schema or update it when its already there. Or you could first drop it and then create it, if its for testing purposes. 

I don't think we need such API (but feel free to convince me :])

**Comment by ujwal-setlur** [comment]
It wasn’t clear to me that updateSchema() would actually create the schema. I will try that. I couldn’t find much documentation about the schema API...

**Comment by B4nan** [comment]
`SchemaGenerator` has quite simple API, so you can check the implementation directly: 

https://github.com/mikro-orm/mikro-orm/blob/master/lib/schema/SchemaGenerator.ts

It will synchronize the database with metadata, so if there is a table missing, it will create it (with the very same method as `createSchema` uses.

**Comment by ujwal-setlur** [comment]
updateSchema() works. Thanks!

**Comment by ujwal-setlur** [comment]
So, updateSchema() drops tables it doesn't know about...I am trying to use Mikro-ORM in a microservices setting where each service connects independently to a DB and manages its own tables. The second service that connects drops the tables of the first one :)

What options do I have? Sorry if this is a stupid question, but I am just getting up to speed with Mikro-ORM. Also, I am using PostgreSQL. I guess I could different schemas for each service, but I gotta figure out how to specify schema to the connection string. My last resort is to use separate databases altogether, which I hope I don't have to do...

**Comment by B4nan** [comment]
Hmm I guess we could add a parameter to disable table dropping. I was planning to add a safe mode anyway (that would also disable column dropping).

**Comment by ujwal-setlur** [comment]
I think the ORM should have control over its entities, so column dropping might be ok. It should not touch entities that are not known to it.

**Comment by B4nan** [comment]
> I think the ORM should have control over its entities, so column dropping might be ok. It should not touch entities that are not known to it.

Those are 2 things, I mentioned the safe mode because that is also something I want to have. If you use the schema generator directly (not via migrations) that it can be dangerous to execute it directly, as it might drop some columns instead of renaming them (although it should not). That is where the safe mode can be used, so you can be sure that no real damage can be done to your data.

So there will be definitely way to disable just dropping of db tables, but there will be also the aforementioned safe mode that will also disable column dropping.

But by default I will keep what it does right now. It is correct to remove unknown tables. If you delete an entity, it will become unknown table and it should be removed. This behaviour is same as in doctrine (which I took for an inspiration mostly). But the schema tool there also support working with multiple schemas I believe, which is what I would like to implement too going forward (although not planned for the nearest future).

**Comment by ujwal-setlur** [comment]
So my current option is to use multiple databases, one for each service?

**Comment by B4nan** [comment]
You could also maybe register all your entities in every service if its a mono repo? Not perfect, but as a workaround it could work. 

Anyway, this is easy to implement, so it will come in few days.

**Comment by ujwal-setlur** [comment]
Ok great! All my services are in different repos. I am not a fan of mono repos :)
