### ISSUE TITLE
Cannot read property '__helper' of null

### ISSUE THREAD

**Issue by derevnjuk** [mikro-orm/mikro-orm#4234]
**Describe the bug**

When attempting to remove a `GroupMember` from the `Member` side of a `ManyToMany` relationship using a pivot table, the related `Group` entity is not updated correctly. Specifically, after removing the `GroupMember`, UoW tries to re-create the removed `GroupMember`.

**Stack trace**
```
TypeError: Cannot read property '__helper' of null
    at helper (/Users/xxx/Projects/mikro-orm-gh4216/node_modules/@mikro-orm/core/entity/wrap.js:21:19)
    at UnitOfWork.initIdentifier (/Users/xxx/Projects/mikro-orm-gh4216/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:446:45)
    at UnitOfWork.initIdentifier (/Users/xxx/Projects/mikro-orm-gh4216/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:455:18)
    at UnitOfWork.findNewEntities (/Users/xxx/Projects/mikro-orm-gh4216/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:408:14)
    at UnitOfWork.computeChangeSets (/Users/xxx/Projects/mikro-orm-gh4216/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:340:18)
    at UnitOfWork.doCommit (/Users/xxx/Projects/mikro-orm-gh4216/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:254:18)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async UnitOfWork.commit (/Users/xxx/Projects/mikro-orm-gh4216/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:240:13)
    at async SqlEntityManager.flush (/Users/xxx/Projects/mikro-orm-gh4216/node_modules/@mikro-orm/core/EntityManager.js:961:9)
    at async fork.getConnection.transactional (/Users/xxx/Projects/mikro-orm-gh4216/node_modules/@mikro-orm/core/EntityManager.js:648:17)
```

**To Reproduce**
1. Create a `ManyToMany` relationship using a pivot table, such as `GroupMember`, and the `OneToMany` relationship between the pivot table and `Group`/`Member`.
2. Query a `Group`, loading items using the eager relation.
3. Query a `Member`, loading items using the eager relation as well.
4. Attempt to remove a `GroupMember` on the `Member` side.
5. Query the same `Member` again to reproduce the behavior.

**Expected behavior**
After removing the `GroupMember` from the `Member` side, the related `Group` objects should be updated correctly, and querying them should return the expected data.

**Additional context**

For details please refer to the repository: https://github.com/derevnjuk/mikro-orm-gh4234

**Versions**

| Dependency | Version |
| - | - |
| node | >=14 |
| typescript | >=4 |
| mikro-orm | 5.6.16 |
| your-driver | pg |

**Comment by B4nan** [comment]
Thanks, got it reproduced. It took me some time to simplify the repro, here is what I ended up with:

```ts
import { Collection, Entity, ManyToOne, OneToMany, PrimaryKey, Ref, RequiredEntityData } from '@mikro-orm/core';
import { MikroORM } from '@mikro-orm/sqlite';

@Entity()
class Group {

  @PrimaryKey()
  id!: number;

  @OneToMany({
    entity: () => GroupMember,
    mappedBy: member => member.group,
    eager: true,
    orphanRemoval: true,
  })
  members = new Collection<GroupMember>(this);

  constructor(params: RequiredEntityData<Group>) {
    Object.assign(this, params);
  }

}

@Entity()
class GroupMember {

  @ManyToOne({
    entity: () => Member,
    primary: true,
    ref: true,
  })
  member!: Ref<Member>;

  @ManyToOne({
    entity: () => Group,
    primary: true,
    ref: true,
  })
  group!: Ref<Group>;

  constructor(params: RequiredEntityData<GroupMember>) {
    Object.assign(this, params);
  }

}

@Entity()
class Member {

  @PrimaryKey()
  id!: number;

  @OneToMany({
    entity: () => GroupMember,
    mappedBy: group => group.member,
    eager: true,
    orphanRemoval: true,
  })
  groups = new Collection<GroupMember>(this);

  constructor(params: RequiredEntityData<Member>) {
    Object.assign(this, params);
  }

}

let orm: MikroORM;

beforeAll(async () => {
  orm = await MikroORM.init({
    entities: [Group, Member, GroupMember],
    dbName: ':memory:',
    debug: true,
  });
  await orm.schema.refreshDatabase();
});

afterAll(() => orm.close(true));

test(`GH issue 4234`, async () => {
  const groupId = 1;
  const memberId = 2;

  {
    const group = new Group({ id: groupId });
    const member = new Member({ id: memberId });
    member.groups.add(new GroupMember({ group, member }));
    await orm.em.persist([group, member]).flush();
    orm.em.clear();
  }

  {
    await orm.em.findOne(Group, groupId);

    const member = await orm.em.findOneOrFail(Member, memberId);
    orm.em.assign(member, {
      groups: [],
    });
    orm.em.persist(member);

    await orm.em.findOne(Member, memberId);
    await orm.em.flush();
  }

  orm.em.clear();
  console.log(await orm.em.findOne(Member, memberId));
  console.log(await orm.em.findOne(Group, groupId));
});
```

Note that there are quite a lot of code smells in your version:
- using `Object.assign` for altering entity state - this can result in invalid state of the entity, e.g. value in place of entity instance, as the `EntityData` type accepts both
- eager loading to-many relations, this is a very bad practice in general, those can result in perf heavy queries (and heavy hydration too) for no reason if the collections are large (and they can get large over time, so this is quite a timebomb)
- the `PrimaryKeyType` and `PrimaryKeyProp` should be defined as optional
- there is no need to call `em.persist` on managed entities (those you fetch from the database via EM) - this is actually the culprit, if you remove this line, things work as expected
- for reproductions, its much cleaner to use `em.clear()` instead of the `RequestContext` helper, both for reading and further debugging, neither you need to wrap everything in explicit transaction - repro needs to be minimal and this is exactly what makes it more complex for no reason
- you are missing assertions, you just call `findOne` in the end, without saying what is expected there, I guess you expect both calls to return the entity, with empty collection, right? that's how it works if I skip that problematic `em.persist` call

The whole `Act` section is really weird, you load the member entity twice and call persist on it. Basically both the `persist` and the second `findOne` are there for no reason (they break things, and that's indeed something to fix, but you don't need them there at all, they should end up as no-op really).
