### ISSUE TITLE
GCP Cloud Spanner Support

### ISSUE THREAD

**Issue by geekflyer** [mikro-orm/mikro-orm#430]
Hi,

nice work on mikro-orm!
I'm looking to add support for [GCP Spanner](https://cloud.google.com/spanner).
I understand this a major chunk of work, so probably not something I'd ask you to do, but rather something I would contribute in a PR.

Are you generally open to such a contribution (i.e. adding GCP Spanner support)?

Also I went a bit over the codebase and it looks like for all the SQL drivers you're using knex under the hood. Unfortunately knex doesn't support Spanner either.
So I was wondering if I should add spanner support to knex first, or if I should try to integrate spanner without knex into mikro-orm (if that's even possible).
The Google provided Spanner client https://github.com/googleapis/nodejs-spanner actually is a bit higher-level than your typical SQL driver, and provides some higher-level facilities for CRUD operations, JSON mapping etc. so I'm kind of optimistic that I can create this driver without knex.

Anyways - just wanted to hear your thoughts on the whole approach if any.

Thanks!

**Comment by B4nan** [comment]
I don't want to include more drivers into the repository directly, I would like to see drivers like this being 3rd party packages (the reason is simple, I don't want to maintain things I don't fully understand or use).

You can definitely do it without knex (mongo driver being an example), although it will be probably more work. Basically you will need to implement something similar to `AbstractSqlDriver` and `AbstractSqlConnection` classes.

https://github.com/mikro-orm/mikro-orm/blob/master/lib/drivers/AbstractSqlDriver.ts
https://github.com/mikro-orm/mikro-orm/blob/master/lib/connections/AbstractSqlConnection.ts

Note that currently schema generator is dependent on the `AbstractSqlDriver`, so if you want to have schema support, it would be possible only via knex. I am planning to split the package so I might be adding more abstractions there so decouple it.

So closing this now as I am not interested in having it part of the repo, but feel free to ask anything either here or on slack.
