### ISSUE TITLE
Custom Type not working as expected

### ISSUE THREAD

**Issue by fider-apptimia** [mikro-orm/mikro-orm#435]
**Describe the bug**
Custom Types are not storing data in desired format:

**To Reproduce**
1. Create custom type
```js
export class MyType extends Type {
  convertToDatabaseValue(jsValue: string): number {
    const dbValue = Number.parseInt(jsValue);
    return dbValue; // returns number
  }

  convertToJSValue(dbValue: number): string {
    // PROBEM IS HERE - dbValue is string not number
    return dbValue.toString();
  }

  getColumnType() {
    return 'integer';
  }
}
```

2. Define entity:
```js
@Entity()
export class TestEnt {
  @Property({ type: MyType )
  prop!: string;
}
```

3. Persist entity entity:
```js
const ent = new TestEnt();
ent.prop = '123';
await em.persistAndFlush(ent);
```

**Expected behavior**
`convertToJSValue` should be called with number returned by `convertToDatabaseValue` - instead it is called with string - so imo data is stored as string instead of number.

**Other info**
- **without** calling `persistAndFlush`:
  - `getColumnType()` called 2x
  - `convertToDatabaseValue()` called 0x
  - `convertToJSValue()` called 0x

- **with** calling `persistAndFlush` (no `find` or `query` called explicitly):
  - `getColumnType()` called 2x
  - LATER:
  - `convertToDatabaseValue()` called 3x
  - LATER:
  - `convertToJSValue()` called 1x

**Versions**
Node v12.14.1
mikro-orm@3.5.2
sqlite3@4.1.1
typescript@3.8.3

**Comment by B4nan** [comment]
Thanks for the report, will release new version later today or tomorrow. 

It was stored properly as int (you can always verify that in the db schema directly), problem was in internal handling, where MikroORM did call the `convertToJSValue` even when not needed (on existing entities instead of on raw db values). In fact it was not supposed to be called here, as you are not fetching anything from the db.

**Comment by fider-apptimia** [comment]
Thanks for quick response & fix.
