### ISSUE TITLE
Creating new pivot entities does not update managed entity relation mappings

### ISSUE THREAD

**Issue by stabai** [mikro-orm/mikro-orm#4527]
**Describe the bug**
When a many-to-many relationship is defined using the [`pivotEntity`](https://mikro-orm.io/docs/collections#custom-pivot-table-entity) option, creating new objects of the pivot entity type does not seem to update the `EntityManager`'s relation mappings. As a result, future queries to the related entities will not reflect the new relationships until `em.clear()` is called.

**Stack trace**
N/A

**To Reproduce**
See this replit and its code to explore a reproduction of the problem:
https://replit.com/@ShawnTabai/mikroorm-pivotentity-relation-bug?v=1

Assuming that database structure of `Product`, `Order`, and `OrderItem`, the steps to reproduce the behavior:
1. Create and persist two `Product`s
2. Create and persist an `Order` containing one of those `Product`s
3. Find the order, and load the count of `OrderItem`s
4. *Note that the count is 1*
5. Create and persist an `OrderItem` linking the other `Product` to the same `Order`
6. Find the order again, and load the count of `OrderItem`s
7. *Note that the count is 1*
8. Clear the cache of the `EntityManager`
9. Find the order again, and load the count of `OrderItem`s
10. *Note that the count is 2*

**Expected behavior**
The count should have increased to 2 on step 7, without needing to clear the `EntityManager`

**Additional context**
N/A

**Versions**

| Dependency | Version |
| - | - |
| node | 16.18.1 |
| tsx | 3.12.7 |
| typescript | 5.1.6 |
| mikro-orm | 5.7.12 |
| mikro-orm/sqlite | 5.7.12 |

**Comment by etotheipluspi** [comment]
+1 it would be great to get an update on this, creating a workaround on top of mikro-orm to manage this is a brittle.

**Comment by B4nan** [comment]
You don't clear the EM, and in the `logOrderProductCount` you do `em.findOne` based on the PK - this only gives you the exact same entity reference you already had, without querying the database - in other words, `fetchedOrder` is exactly the same as `order1`, its not a "new fetched entity", its the exact same `order1`, without any queries being fired, or hydration happening. And you use `loadCount` on the collection of it - method that queries the count only once and caches the value for later use - on the exact same collection instance as in `order`. This method will never give you any other number than the one you already have, as it already has the cached number, that is the definition of how it should work.

The cached number would be updated if you would work with the relation itself, so if you would add or remove items from the `orders` collection, but since you work with the pivot entity, there can't be any propagation happening - there is no link from the pivot entity back to the orders collection. Pivot entities used in M:N are used only for the joined columns inference, there are no pivot entities used under the hood.

There is a `refresh` option in the `loadCount` method you can use to disregard the cached value - when used, it will work the way you expect:

```ts
async function logOrderProductCount(em: EntityManager) {
  const orderData = { id: 'order1' };
  const fetchedOrder = await em.findOneOrFail(Order, orderData);
  const productCount = await fetchedOrder.products.loadCount({ refresh: true });
  console.log({ ...orderData, productCount });
}
```

An alternative to this would be to define the 1:m relations to the pivot entity, so propagation can work. But still, there is no connection to your M:N relations, you would have to check the 1:M instead, and that would work as well. Here is a complete repro for that:

```ts
import { Collection, Entity, ManyToMany, ManyToOne, OneToMany, PrimaryKey, Property } from '@mikro-orm/core';
import { EntityManager, MikroORM } from '@mikro-orm/sqlite';

@Entity()
export class Order {

  @PrimaryKey()
  id!: string;

  @ManyToMany({ entity: () => Product, pivotEntity: () => OrderItem })
  products = new Collection<Product>(this);

  @OneToMany({ entity: () => OrderItem, mappedBy: 'order' })
  items = new Collection<OrderItem>(this);

}

@Entity()
export class Product {

  @PrimaryKey()
  id!: string;

  @ManyToMany({ entity: () => Order, mappedBy: o => o.products })
  orders = new Collection<Order>(this);

  @OneToMany({ entity: () => OrderItem, mappedBy: 'product' })
  items = new Collection<OrderItem>(this);

}

@Entity()
export class OrderItem {

  @ManyToOne({ primary: true })
  order!: Order;

  @ManyToOne({ primary: true })
  product!: Product;

  @Property({ default: 1 })
  amount!: number;

}

let orm: MikroORM;

beforeAll(async () => {
  orm = await MikroORM.init({
    dbName: ':memory:',
    entities: [Order, Product, OrderItem],
  });
  await orm.schema.createSchema();
});

afterAll(() => orm.close(true));

test('4527', async () => {
  async function logOrderProductCount(em: EntityManager) {
    const fetchedOrder = await em.findOneOrFail(Order, { id: 'order1' });
    const productCount = await fetchedOrder.products.loadCount();
    const itemCount = await fetchedOrder.items.loadCount();
    console.log({ id: 'order1', productCount, itemCount });
  }

  console.log('Creating base records...');
  const product1 = orm.em.create(Product, { id: 'product1' });
  const product2 = orm.em.create(Product, { id: 'product2' });
  await orm.em.flush();
  console.log('Created product1 and product2');

  const order1 = orm.em.create(Order, { id: 'order1', products: [product1] });
  await orm.em.flush();
  console.log('Created order1 with product1');
  await logOrderProductCount(orm.em);

  const order1Product2 = orm.em.create(OrderItem, {
    order: order1,
    product: product2,
    amount: 999,
  });
  await orm.em.flush();
  console.log('Added product2 to order1');
  await logOrderProductCount(orm.em);

  console.log('Cleared EntityManager');
  orm.em.clear();
  await logOrderProductCount(orm.em);
});
```

Few notes on the repro:
- `em.create` is sync method, no need to await it
- `em.create` will call `em.persist` automatically, no need to do it yourself

I will close this, as the repro seems to be invalid, but feel free to ask follow-up questions.
