### ISSUE TITLE
Support for Sqlite on React Native

### ISSUE THREAD

**Issue by gfrancischini** [mikro-orm/mikro-orm#453]
**Is your feature request related to a problem? Please describe.**
Today Mikro-ORM seems not to support RN due to the dependencies of node native libraries and also the file system. Looking at the source code it seems that a more "generic" approach could be taken on the main core to reuse it with RN. Also the cmd application could get a specific project that could rely on the node-fs without hurting the core project.

**Describe the solution you'd like**
I would like to propose breaking down some of the project (core and cmd) and also removing the dependence of node native modules.

**Comment by B4nan** [comment]
Breakdown into multiple packages in planned for v4. I am pretty sure 2 packages won't be enough. 

> and also removing the dependence of node native modules.

What does this mean? Every dependency has its purpose, I can't just remove things without loosing some features (and I am not planning to lose features because of RN support, that was never a goal). Anyway, as I said, already planned, but the breakdown itself, not a RN support. If you want something more, you need to be specific. 

Btw you might achieve this via webpack right now I think, here is an example project with PG (and there was a guy who was using it with angular universal some time ago):

https://github.com/thekevinbrown/express-ts-webpack-example-app

**Comment by B4nan** [comment]
Closing this as the split into packages is already merged in v4 (`dev` branch) via #475. Please subscribe here for updates about v4: #527

**Comment by likern** [comment]
@B4nan Hello! Is there some additional features / things that MikroORM can do, while TypeORM can't?

I'm not sure, but I think both projects are equally powerful. Yet TypeORM provides support for React Native, without depending on Node.js packages (I don't use any webpack or Node.js hacks)

I think this can be achieved in MikroORM too. 
I totally understand that it might not be the goal. But knowing it's already supported by TypeORM can be useful.

**Comment by B4nan** [comment]
I would be open for merging support for it (as well as helping with the actual PR), but I as never used react native myself, it's a bit out of scope for me. 

Regarding the differences, there are many things that work differently because of identity map and unit of work. Check the readme for a brief summary: 

https://github.com/mikro-orm/mikro-orm/#-unit-of-what

Latest version of MikroORM also supports batch insert/update/delete that works automatically, more about that in a blog post:

https://medium.com/dailyjs/mikroorm-4-1-lets-talk-about-performance-b184d612f1d5

**Comment by mkieblesz** [comment]
What about storing schema on the api side and write custom migration file generator for sqlite and run it directly with non-mikro-orm sqlite driver? We still would be able to use knex directly like here https://gist.github.com/B4nan/ed1fd1c1d8c37b7ebe80d86bc26a7c05

**Comment by gigq** [comment]
Is this still not possible out of the box after packages were split out? It was closed with V4 but looking at Mike's solution it still seems like something that isn't really supported. Was just considering this instead of TypeORM for a react native project.

**Comment by B4nan** [comment]
Same as 3 years ago, I have no experience with this so it would be hard for me to do it, but I am open for a PR (as well as for helping with it). One of the things I want to do in the long run is to drop knex as the core implementation part for SQL drivers, and do the query building ourselves (we already do it for many parts, mainly for performance reasons as knex is kinda slow. 

Then knex, or any of its modern alternatives like kysely or whatnot, could be used on top of MikroORM interchangeably - and adding new SQL drivers could be much easier. 

FYI we don't use the migrations from knex anyhow (so removing that bit is totally safe), we use umzug instead (and that is another dependency I could see being dropped, it's not doing much for us).

Also v6 could be already in a better shape for this, as the require calls are mostly removed, see #3814.
