### ISSUE TITLE
docs: Migrations: How to use EntityManager in migrations?

### ISSUE THREAD

**Issue by zetti-caletti** [mikro-orm/mikro-orm#4605]
Why is there no EntityManager available in Migrations?
I want to insert some data in the database and want to use migration instead of seeders, because with migrations I can automate the migration call in CI/CD.  But there are only native methods like nativeDelete and find with string instead of entity name. Whats the reason for this?

If I call this.driver.createEntityManager() and try to use it, it hangs with the error: "knex connection timeout"

For example I have the job to introduce a new project status and then I also need to insert that new data in the database:
```
async up(): Promise<void> {
    const em = this.driver.createEntityManager(true);
    const projectStatus = new ProjectStatus('reviewNeeded');

    await em.persistAndFlush(projectStatus);
}

async down(): Promise<void> {
    const em = this.driver.createEntityManager(true);
    const projectStatus = await em.findOne(ProjectStatus, 'reviewNeeded');

    await em.removeAndFlush(projectStatus);
}
```

If I haven't misunderstood seeders, this is a task for migrations because I cannot rollback seeders, right?

**Comment by B4nan** [comment]
You shouldn't be really using EM in your migrations, migrations are meant for schema changes, you can alter the data as well, but those should also use native queries preferably.

The problem you are facing is caused by existing transaction context in the migration scope, that you are ignoring - the EM you create via driver does not know about it. Something like this should fix it:

```ts
const em = this.driver.createEntityManager(true);
em.setTransactionContext(this.ctx);
```

I guess we should have a shortcut in the migration class that is doing this. I haven't added that mainly because of what I said above - this is not really a place where you should be using EM, this will have unnecessary perf penalty, migrations were designed to be mainly about SQL queries.

**Comment by zetti-caletti** [comment]
> 

Hehe I just also found your solution here [https://github.com/mikro-orm/mikro-orm/issues/2670#issuecomment-1020463343](https://github.com/mikro-orm/mikro-orm/issues/2670#issuecomment-1020463343) right now.
Now it works. Thanks.
But then my question: Why shouldn't you use EntityManager in Migrations and use raw queries instead? In raw queries there can happen type errors, etc. I mean Mikro-orm is an ORM and in ORM you use entities.

Yes a shortcut would be nice: this.getEntityManager() or something like this :)

**Comment by zetti-caletti** [comment]
For schema changes you need raw queries, thats true. But for inserting or removing data in database and easy access to EntityManager would be nice and it should be documented, because now there is something about inserting or removing data in migrations in the docs.

**Comment by B4nan** [comment]
It's just something that feels overcomplicated for a migration, but the bottom line is - use whatever suits the job, especially if you find it more readable and maintainable. It's not like this approach is forbidden or something, but things were not designed with it in mind - the EM factory method on the driver level was added because of something else, and I only realized things can work in migrations because of people finding it first and asking the same question as you did :]

If you want to use it only because of the mapping of field <-> property names, you could use the query builder for that as well, or the `em.native*` methods like `em.nativeUpdate()`, as those are basically a query builder shortcuts.

Agreed this should be documented, and we should probably have the EM getter on the migration class to make it easier. It's the same problem as with `this.execute()` and `this.driver.execute()`, the former will respect the current context.
