### ISSUE TITLE
forceObject when defineConfig

### ISSUE THREAD

**Issue by wenerme** [mikro-orm/mikro-orm#4881]
**Is your feature request related to a problem? Please describe.**

I want to `forceObject: true` when defineConfig, I don't find a way to do this https://mikro-orm.io/docs/serializing#explicit-serialization . seems forceUndefined = skipNull, maybe can add some extra serialize options when defineConfig ?

**Describe the solution you'd like**

global forceObject config

**Describe alternatives you've considered**
 property level option ?

**Additional context**

**Comment by B4nan** [comment]
That is a static method, it cannot respect any configuration, it does not have a way to read it.

**Comment by B4nan** [comment]
I guess we could store the config reference on the entity prototype during discovery, and replace that with the right instance once the entity gets managed, that should cover most of the use cases.

**Comment by wenerme** [comment]
> I guess we could store the config reference on the entity prototype during discovery, and replace that with the right instance once the entity gets managed, that should cover most of the use cases.

Dose this affect the multi em instance ?

**Comment by wenerme** [comment]
> That is a static method, it cannot respect any configuration, it does not have a way to read it.

How about use the context hook ? the static methdo try to read the config from context that match the current managed em  ?

**Comment by B4nan** [comment]
> Dose this affect the multi em instance ?

Well, yes, but don't tell me you would like to have different serialization configs for those.

> How about use the context hook ?

What's that? You mean the request context? That's an optional feature, I need a universal solution (and yet again, the callback to obtain a context is described in the config).

> the static methdo try to read the config from context that match the current managed em ?

If an entity is managed, it already has the right EM link attached on it, and that is what would be always preferred. The problem is really just with not managed entities (and I think its safe to say those are not really serialized for most of the times).

**Comment by B4nan** [comment]
Implemented in v6 via 9a4de460b40d04c83f03d66556f5e1efb5d5fdb0
