### ISSUE TITLE
Feature: Forked Logger

### ISSUE THREAD

**Issue by mboudreau** [mikro-orm/mikro-orm#5022]
**Is your feature request related to a problem? Please describe.**
I'm using Mikro with Express with Winston as a logger (but this doesn't really matter) - when a request is received, we add context to the logger so that all subsequent logs have metadata added to it to easier tracing/filtering in Datadog.  We'd like to be able to add this same context to all Mikro logs, but since the `logger` config property is global, there's no way of adding that per request context to the logs with accuracy.  

**Describe the solution you'd like**
As part of calling `RequestContext.create(orm.em, next, { ... });`, you could add `logger` as part of the `CreateContextOptions`, which would then be passed to the forked EntityManager.  There are some things that need to be global no matter what, but I was hoping that anything that could be request context specific be logged as such.

**Describe alternatives you've considered**
I've tried working with the global logger, logger factory, etc, but because we have many requests per seconds, they keep "competing" with each other over who gets to set the context and most of the data coming out of it is not related to the correct request.  Only way to do this would be to initialize Mikro for every request, which seems ridiculous as it would add the overhead of connecting to the DB for every request and make our API slower.

Thanks for all the work that's been done on this library, it's been very useful for us.  Cheers.

**Comment by B4nan** [comment]
The problem here is that it's not the EM that would be logging, it's the connection class (and there is only one connection instance for all the forks - it represents the connection library instance we use, e.g. knex).

FYI v6 already allows to toggle logging via `FindOptions` and set up query labels (https://mikro-orm.io/docs/next/logging#logger-customization), and has a concept of a [logger context](https://mikro-orm.io/docs/next/logging#providing-additional-context-to-a-custom-logger). We should probably try to leverage that instead of making more logger instances. I guess the EM could have its own base logger context that would be filled in when logging (via the `FindOptions`)?

> I've tried working with the global logger, logger factory, etc, but because we have many requests per seconds, they keep "competing" with each other over who gets to set the context and most of the data coming out of it is not related to the correct request. Only way to do this would be to initialize Mikro for every request, which seems ridiculous as it would add the overhead of connecting to the DB for every request and make our API slower.

The correct way right now would be to leverage async local storage (which is how the `RequestContext` helper already works - you can do the same yourself too), calling `init` for each request is indeed a bit too crazy :]  (on the other hand, that's kinda what serverless folks are doing, so it's not that far out of space, heh)

**Comment by mboudreau** [comment]
Yeah, I understand that, I was just hoping that there would be a way to inject context with the logs so we can trace our users' requests.

We are on serverless (aws lambda) and yeah, doing an init for each request would be ridiculous and will eat up our connection pool way too quickly, as well as the connection overhead and make our API slower than what we'd like.

Having that logger context is definitely a step in the right direction.  If we could for do this for all operations, this would be an adequate solution, albeit a bit clunky and would involve a lot more boilerplate on my side, but I'd rather that than nothing at all.

**Comment by B4nan** [comment]
I think the solution with EM specific context base will work fine and should be easy to implement.

**Comment by darkbasic** [comment]
> The correct way right now would be to leverage async local storage

Which is really convenient to develop with but also a huge can of worms.
`asyncLocalStorage.run` had worked decently well for me so far but we had to move away from `asyncLocalStorage.enterWith` in graphql-modules because it had the tendency to lose the context. If I recall correctly we use the former in mikro-orm.
