### ISSUE TITLE
docs: some missing V5 -> V6 breaking changes

### ISSUE THREAD

**Issue by darky** [mikro-orm/mikro-orm#5103]
* TypeScript, `em.insert` in V6 requires strict `Entity` payload, but on V5 can receive `Partial<Entity>`

```typescript
@Entity()
class Entity {
  @PrimaryKey()
  id: number;
  
  @Property({ defaultRaw: 'current_timestamp' })
  createdAt?: Date;
}

await em.insert(Entity, {id: 1}) // works on V5, but not on V6

await em.insert(Entity, {id: 1, createdAt: new Date()}) // works on V6
```
  
 * `em.remove` on V6 requires `Reference`, but on V5 can work with plain unfetched `Entity`
  
```typescript
@Entity()
class Entity {
  constructor({id}) {
    this.id = id;
  }

  @PrimaryKey()
  id: number;
}

await em.remove(new Entity({id: 1})) // works on V5, but not on V6

await em.remove(em.getReference(Entity, 1)) // works on V6
```

**Comment by B4nan** [comment]
> em.remove on V6 requires Reference, but on V5 can work with plain unfetched Entity

Gave this a closer look, and its caused by 1b09d263f94f4c216936f6f85673810f7c6f9099, which adds entities to the identity map on `em.persist` if they have a PK. Because of that, we need to ignore such entities in `em.remove`, as they don't exist in the database yet. I think we can restore the old behavior by also allowing to issue the delete query if the entity is not in persist stack (as that is when we want to ignore the remove call - as it cancels the previous persist call instead of making a delete query).
