### ISSUE TITLE
Increase strictness and safeness in the codebase

### ISSUE THREAD

**Issue by AlexAegis** [mikro-orm/mikro-orm#541]
Having stricter TypeScript checks will lead to a safer codebase. Consider incorporating the following flags one by one into your codebase. 

```json
		"noImplicitAny": true,
		"noImplicitReturns": true,
		"noImplicitThis": true,
		"noUnusedParameters": true,
		"strictBindCallApply": true,
		"strictNullChecks": true,
		"strictFunctionTypes": true,
		"strictPropertyInitialization": true,
```

Also, omit the `suppressImplicitAnyIndexErrors` flag.

**Comment by B4nan** [comment]
Disabling `suppressImplicitAnyIndexErrors` has its purpose, as it gets super tedious to do what is needed without falling back to code full of type casting to `as T[keyof T]`. I've been there, and I am not planing to revert this. 

Note that we have `strict` flag enabled, which means:

> Enable all strict type checking options.
> Enabling --strict enables --noImplicitAny, --noImplicitThis, --alwaysStrict, --strictBindCallApply, --strictNullChecks, --strictFunctionTypes and --strictPropertyInitialization.

So only thing from your suggestions that is not implemented is `noImplicitReturns` (which I am also not planning to change now, but I am open for PR) and `noUnusedParameters` (which don't really works well with inheritance, it repots unused params where they need to be present because of contracts from interfaces).

**Comment by B4nan** [comment]
Lol looks like the problem with `noUnusedParameters` can be worked around by prefixing the unused params with `_`, interesting.

But the bottom line is that I invested **a lot** of my time in making this repository strict, there are more checks than just the TS compiler, namely the codeclimate static analyses is really strict. Enabling `noUnusedParameters` in TS does report _only_ those false positives where I would have to add the `_` prefix.

**Comment by AlexAegis** [comment]
That's great to hear! Sorry, I did not know the strict flag enables all the others too, I thought it's only for the Javascript native strict mode.

I work for a rather large company, and one of our legacy tools is going to be re-implemented. I plan to use this ORM there but it's still under discussion.
