### ISSUE TITLE
Monorepo config support

### ISSUE THREAD

**Issue by AlexAegis** [mikro-orm/mikro-orm#545]
Hi!

I tried out MikroORM in an NX Workspace, and to use it there, I see a blocker.

> Really easy to try out, there is a `create-nx-workspace` npm package out there and it can scaffold up a workspace with nestjs in no time

In an NX Monorepo setup, every single project uses the same top-level package.json, but MikroORM CLI relies on the config specified in the package.json.

```shell
.
├── angular.json
├── apps
│   ├── demo-server
│   │   ├── src
│   │   └── tsconfig.json
│   └── demo-server-2
│       ├── src
│       └── tsconfig.json
├── nx.json
├── package.json
├── tsconfig.json
└── tslint.json
```

> In this setup, demo-server and demo-server-2 needs separate configurations for the CLI, but there is only one package.json!

I suppose I could make a shim package.json file, for only this but it would be rather ugly.
I suggest that aside the package.json config (Lot of other libraries do it, I see no problem with that) to introduce an additional, optional config file that the CLI can pick up. Like `mikroorm.config.json` or something like that.

I really like that the config itself is in JS/TS because this enables me to write some extra logic to handle multiple environments.

**Comment by AlexAegis** [comment]
And as a comment I'd mention that this is not necessarily an NX-like solution, that would be to integrate the mikroorm cli into the angular cli that NX uses, and call the specific app through that. In this setup the mikroorm config could be in the angular.json file that contains the project specific configs.

But it's way simpler just to introduce another file, and that could be used in other similar environments too.

**Comment by B4nan** [comment]
So you say you have 2 backend packages, each needs different orm config. How does introducing new config file help here? It would still need to be in the root, I don't want to traverse blindly every folder to look for it. 

Or you would like to execute the CLI from inside the child package folder?

**Comment by AlexAegis** [comment]
Yes, I would. How else would you differentiate between the two packages with the same package.json? 

But you wouldn't have to blindly traverse every folder anyway, just every parent. That's how npm picks up package.json, that's why you can use it from an inner folder.

**Comment by B4nan** [comment]
So you could create the nested `package.json` (just with the ORM settings) which would behave exactly like you want, right?

**Comment by B4nan** [comment]
So this whole request is to prefer different file (if found) than `package.json`, right? So you don't have to imitate it when you don't need it?

**Comment by AlexAegis** [comment]
Yes as I said I could create a shim `package.json` with just the orm settings but I fear that some other tool might pick it up for something that it isn't. (Maybe not)

Traversing up makes sense because in a setup like this it could then fall back to a top level one. And the cli could be used from inside the project not just where the config is.

Yes. Me `cd`ing into a subproject is the least I could do.

What I would do is the following:

I would introduce two new flags, `--config`, which would receive a json string (For much easier implementation than introducing a separate flag for each option), and `--config-file`, which would receive a path that should be read as the config. (I like flexibility, and this could help integrate the cli into anything else later on. Like the mentioned NX CLI and an IDE, VS Code can run tasks, and in these tasks I could then specify entries like, generate migrations for this project, and that project, each with their separate config files specified with `--config-file`.)

1. If either of these flags exist, use that. If not, continue.
2. Check the current folder for the config file
3. If it doesn't exist check for a package.json file that has the config.
4. If that doesn't exist either, go up a folder.

Repeat 2-4 until a config is found or the root folder is hit.

I think this would make for a flexible config read.

**Comment by B4nan** [comment]
Ok I guess I am fine with the parent-folder-lookup approach, although not a big priority.

**Comment by DenKorn** [comment]
I would add that this issue is blocker for normal use of MikroORM in the NestJS sub-apps.

**Comment by mmcxii** [comment]
Wanted to bump the idea that the ability to pass a config path to the CLI via a flag would be a fantastic add. My company and I are hoping to use Mikro ORM in an NX monorepo with several small services each with their own database. Unfortunately without being able to provide a config I'm not sure how I'd get the CLI to interact with a specific app's database for the purpose of running migrations, creating and updating the schema, etc.

If this is a feature I could help implement I would be happy to help however I could as this is essentially the only thing stopping us from using Mikro.

**Comment by johannesschobel** [comment]
Dear @B4nan , i am running also into the same issue as described here. I have a mono-repository with a lot of different nestjs backend apis, which act as independent services. Each service, in turn, has its own database.

When i do not rely on the `mikro-orm.config.ts` file, and just use the `MikroOrmModule`, the services work fine, i.e., i can pass in their own configuration. However, in order to run `migrations`, i need the config-file. Unfortunately, this file needs to be "linked" in my `package.json` file. As i use `nrwl/nx`, i only have one global `package.json` file for my entire mono-repository. Therefore, i cannot define and use multiple connections.

Do you have any solutions for this? I think, using an additional `--config` param would be fine. Or we could restructure the `mikroorm` property in the `package.json` to look like this:

```json
{
  "name": "your-app",
  "dependencies": { ... },
  "mikro-orm": {
    "app1": {
      "useTsNode": true,
      "configPaths": [
        "./apps/app1/src/mikro-orm.config.ts",
        "./dist/app1/mikro-orm.config.js"
      ]
    },
    "app2": {
      "useTsNode": true,
      "configPaths": [
        "./apps/app2/src/mikro-orm.config.ts",
        "./dist/app2/mikro-orm.config.js"
      ]
    }
  }
}
```

and then call it via

```bash
npx mikro-orm migration:create --config=app1
```

What do you think?

**Comment by B4nan** [comment]
You don't need to use the CLI at all, create a small script and use `Migrator` programatically.

https://mikro-orm.io/docs/migrations/#using-the-migrator-programmatically

**Comment by johannesschobel** [comment]
thank you very much for your support - i will take a look at it and give feedback :+1: 
From what i've seen so far, `Mikro-ORM` looks awesome!

All the best

**Comment by mmcxii** [comment]
@B4nan Thanks for the pointer!

```
// scripts/createMigration.ts

import { mikroOrmConfig } from "../src/config/mikro-orm.config";

(async () => {
  try {
    const orm = await MikroORM.init({
      ...mikroOrmConfig,
    });

    const migrator = orm.getMigrator();

    await migrator.createMigration();

    await orm.close(true);
  } catch (error) {
    console.error(error);

    process.exit(1);
  }
})();
```

This is what I came up with based on the docs and in a minimal testing repo it's working (I have another set of scripts for calling  `migrator.up()` and `migrator.down()`). Is this how you would go about making a migration script or is there some egregious error I've made? Obviously migrations are a pretty important thing to get right and I'd hate to use a good tool the wrong way.

**Comment by B4nan** [comment]
Yes, looking good. It's not necessary to clone the config, it won't be mutated by the ORM, but it won't hurt anything either :]

**Comment by johannesschobel** [comment]
Dear @mmcxii ,
did you manage to create / run migrations in a `nrwl/nx` context? I tried to copy/paste your example, but get some errors.

If i create the file `ROOT/scripts/create-migration.ts` (whereas, `ROOT` is the main root directory of the project) and call it via `ts-node ./scripts/create-migration.ts` i get the following errors:
```bash
ts-node ./scripts/create-migration    

/usr/lib/node_modules/ts-node/src/index.ts:421
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
apps/foobar-api/src/app/modules/cards/entities/card.entity.ts:1:36 - error TS2307: Cannot find module '@foobar/api/core' or its corresponding type declarations.

1 import { IdentifiableEntity } from '@foobar/api/core';
                                     ~~~~~~~~~~~~~~~~~~
```

This is mainly, because the project root directory does not have a `tsconfig.json` file. Note that `nrwl/nx` restructured the workspace - the root directory only has a `tsconfig.base.json` file.

If i, however, add a `tsconfig.json` file, which looks like this:
```json
{
  "extends": "./tsconfig.base.json"
}
```

it cannot find my `@foobar/api/core` library.

Do you have a working example, where i can use `migrations` in the context of an `nrwl/nx` workspace? i would highly (!) appreciate your work and help to push me into the right direction!

All the best and thanks for your time

**Comment by mmcxii** [comment]
@johannesschobel 

So I kind of got it working with that script I had, but then I realized I was kind of heading in the wrong direction. Postgres has a feature called schemas which Mikro-ORM natively supports like this `@Entity({ table and: "schemaName.tableName" })`. By using Postgres schemas to handle scoping we can then perform joins on these tables even though they are isolated from one another, whereas if we used entirely separate databases we would not be able to use SQL joins to link data and would instead have to do that manually in the app.

With that in mind I decided on a pattern of using one library for defining my entity schemas `libs/database/entities` and then another lib for each entity to Nest `libs/server/user`, `libs/server/todoItem`, etc.

Now to your point, I believe in your tsconfig you also need to specify `"module":"commonjs"` in the compilerOptions for Mikro to pick up on it properly. I will check my working repo tomorrow just to confirm all of this and deploy it and link it back here for reference.

**Comment by johannesschobel** [comment]
Dear @mmcxii , thank you for your response.
the approach you described would be the `nx-preferred` style, i guess. Thats what i used for `typeorm-related` setups as well. In this context, i created a (quick and dirty!) minimal repository with all dependencies installed:

# [Minimal Repository HERE](https://github.com/johannesschobel/nx-nest-mikroorm-playground)

This repo contains (basically as you described):
- the latest nx version
- a nestjs application with just a database connection
- a data library with one entity
- a module that consumes the entity from the external library
- this module is used in the nestjs application
- docker-compose file for easy testing ;)

## Questions

1) **Create Database Tables**
The application itself starts, however the databse tables are not created (i.e., like in `typeorm` when you use `synchronize: true`). I did not find anything related to this in `mikro-orm`. So i guess, we **must** create `migrations` or  `schema generators` to build up the database.

2) **Migrations**
As asked before - where do you put your mikro-orm database scripts in order to be executed?

Maybe you can pull my repo and submit a pull-request with respective changes? This way we would be able to create a minimal viable repository and then link it in the official docs? I am pretty sure that others will also find this interesting. What do you think @B4nan ?

All the best and thank you very much for your time and efforts!

**Comment by mmcxii** [comment]
@johannesschobel

1. You're correct in that we must create the tables manually using migrations or the schema generator. You could call the schema generator as part of the `onAppBootstrap` lifecycle event while in `dev` mode, however for me it's not so big of a deal to just use the CLI (`mikro-orm schema:update --run`) whenever I want to make small changes. In this way I'm always in control and I'm less likely to let something slip into production that I don't mean to.

2. I've gone back and forth on a couple locations for where I want to keep my migrations. Initially I kept them in the library with the entity definitions at `<root>/libs/database/entities/migrations` but after further usage yesterday I'm somewhat inclined to keep them closer to the root at `<root>/database/migrations`. I'm thinking this is preferable if only so I don't have to go digging four levels deep to find my migrations if I ever need to audit or review them. Either way it doesn't matter to the CLI since the path can specified.

I'll upload my repo today when I get to work (should be in about two hours from now) and we can compare the two.

**Comment by johannesschobel** [comment]
Dear @mmcxii ,I would appreciate a repository to get some inspiration.
Thanks a lot

**Comment by mmcxii** [comment]
@johannesschobel @B4nan 

Before I upload my sample repo I wanted to go in and implement the structure that is used in the other example repos so this could eventually be used in the docs. However I'm running into a circular dependency issue with two entities that reference each other.

Using these entities causes no issues (note that entities must be referenced by a string name though):

```ts
// base.entity.ts
@Entity({
  abstract: true,
})
export abstract class BaseEntity {
  @PrimaryKey()
  id!: number;
}

// book.entity.ts
@Entity()
export class Book extends BaseEntity {
  @ManyToOne("Author")
  author: Author;
}

// author.entity.ts
@Entity()
export class Author extends BaseEntity {
  @OneToMany("Book", "author", { cascade: [Cascade.ALL] })
  books = new Collection<Book>(this);
}
```

However, adding additional relations causes a circular dependency issue which crashes the build process. For example, adding this column to the `Author` entity:

```ts
@ManyToOne("Book")
favouriteBook?: Book;
```

Here is the stack trace coming from Webpack:
```
ReferenceError: Cannot access 'Author' before initialization
    at Module.Author (/.../mikro-orm-nx-workspace-example/dist/apps/server/api/main.js:226:98)
    at Module../libs/database/entities/src/lib/book.entity.ts (/.../mikro-orm-nx-workspace-example/dist/apps/server/api/webpack:/libs/database/entities/src/lib/book.entity.ts:8:11)
    at __webpack_require__ (/.../mikro-orm-nx-workspace-example/dist/apps/server/api/webpack:/webpack/bootstrap:19:1)
    at Module../libs/database/entities/src/lib/author.entity.ts (/.../mikro-orm-nx-workspace-example/dist/apps/server/api/main.js:231:70)
    at __webpack_require__ (/.../mikro-orm-nx-workspace-example/dist/apps/server/api/webpack:/webpack/bootstrap:19:1)
    at Module../libs/database/entities/src/mikro-orm.config.ts (/.../mikro-orm-nx-workspace-example/dist/apps/server/api/webpack:/libs/database/entities/src/mikro-orm.config.ts:1:1)
    at __webpack_require__ (/.../mikro-orm-nx-workspace-example/dist/apps/server/api/webpack:/webpack/bootstrap:19:1)
    at Module../libs/database/entities/src/index.ts (/.../mikro-orm-nx-workspace-example/dist/apps/server/api/webpack:/libs/database/entities/src/index.ts:1:1)
    at __webpack_require__ (/.../mikro-orm-nx-workspace-example/dist/apps/server/api/webpack:/webpack/bootstrap:19:1)
    at Module../libs/server/orm/src/lib/orm.module.ts (/.../mikro-orm-nx-workspace-example/dist/apps/server/api/main.js:360:107)
```

The two lines referenced from the compiled app are:

```js
231 /* harmony import */ var _book_entity__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ./book.entity */ "./libs/database/entities/src/lib/book.entity.ts");
```

```js
360 /* harmony import */ var _mikro_orm_nx_workspace_example_database_entities__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! @mikro-orm-nx-workspace-example/database/entities */ "./libs/database/entities/src/index.ts");
```

And for posterity's sake here is the Mikro-ORM config:
```ts
import "dotenv/config";
import { Options } from "@mikro-orm/core";

import { Author } from "./lib/author.entity";
import { Book } from "./lib/book.entity";

export default {
  type: "postgresql" as const,
  host: process.env.DATABASE_HOST,
  port: Number.parseInt(process.env.DATABASE_PORT, 10),
  dbName: process.env.DATABASE_NAME,
  user: process.env.DATABASE_USER,
  password: process.env.DATABASE_PASS,
  entities: [Author, Book],
  migrations: {
    path: "./database/migrations",
  },
} as Options;
```

**Comment by mmcxii** [comment]
I've gone ahead and published my repo in its "working" state so it can be cloned, edited, etc.

https://github.com/mmcxii/mikro-orm-nx-workspace-example

**Comment by johannesschobel** [comment]
you sir, @mmcxii , are awesome! thanks a lot for your help. I will take a look at it during the holidays!

**Comment by mmcxii** [comment]
Alright, been doing some due diligence this morning and I can confirm that if you spin up a vanilla Nest.js project, implement the Author, Book, BookTag, and Publisher schema that has been used for demonstration purposes it **can** be compiled using the Nest.js CLI with the `--webpack` flag enabled. So to me that means that the blocking issue with nx is the webpack config being used by the NX CLI.

**Comment by mmcxii** [comment]
@johannesschobel @B4nan I've put together a working example using Lerna and the Nest.js CLI instead of NX. Anyone can clone and use this however they want.

https://github.com/mmcxii/mikro-orm-lerna-monorepo-example

**Comment by mmcxii** [comment]
@B4nan @johannesschobel I've made some interesting discoveries with NX and Mikro. I believe the key to making them work is setting this in the tsconfig for the app:

```json
{
  "compilerOptions":  {
    "module": "commonjs"
  }
}
```

We must specify this because in the tsconfig.base.json at the root of an NX workspace the module property is set to `"esnext"`. *However*, we do still get circular dependency warnings in the console above the App logs that look like this:

```
WARNING in Circular dependency detected:
apps/api/src/modules/orm/entities/author.enity.ts -> apps/api/src/modules/orm/entities/book.entity.ts -> apps/api/src/modules/orm/entities/author.enity.ts

WARNING in Circular dependency detected:
apps/api/src/modules/orm/entities/book.entity.ts -> apps/api/src/modules/orm/entities/author.enity.ts -> apps/api/src/modules/orm/entities/book.entity.ts

WARNING in Circular dependency detected:
apps/api/src/modules/orm/entities/bookTag.entity.ts -> apps/api/src/modules/orm/entities/book.entity.ts -> apps/api/src/modules/orm/entities/bookTag.entity.ts

WARNING in Circular dependency detected:
apps/api/src/modules/orm/entities/publisher.entity.ts -> apps/api/src/modules/orm/entities/book.entity.ts -> apps/api/src/modules/orm/entities/publisher.entity.ts
```

There is an open issue on the NX repo regarding these circular dependency warnings

https://github.com/nrwl/nx/issues/2975

It seems that they are aware of this so hopefully these warnings can be suppressed sometime soon!

**Comment by B4nan** [comment]
> I forgot to mention I did encounter one interesting bug while using NX

Not a bug, this is working as intended, just `@Enum()` will work only with ts-morph (and that is incompatible with webpack). Few other limitations: 

https://mikro-orm.io/docs/metadata-providers/#limitations-and-requirements

**Comment by mmcxii** [comment]
Ah I missed that, thank you for correcting me.

**Comment by alexy4744** [comment]
I wrote an NX executor that creates a `package.json` shim before running MikroORM CLI. I have been using it for development as a workaround and it is the easiest way for me to have different config paths per project since it creates the shims on the fly with values from your `workspace.json`.

You can check it out here: https://github.com/alexy4744/packages/tree/master/packages/nx-mikro-orm-cli

**Comment by B4nan** [comment]
Looking at this now, and I see I forgot to mention there is actually env var - `MIKRO_ORM_CLI` - to provide/override the config path - it has been there since v3.

**Comment by B4nan** [comment]
So with the latest changes in v5, the `package.json` will be checked recursively in the parent folders too, and we can override the CLI settings via env vars:

- `MIKRO_ORM_CLI`: the path to ORM config file
- `MIKRO_ORM_CLI_USE_TS_NODE`: register ts-node
- `MIKRO_ORM_CLI_TS_CONFIG_PATH`: path to the tsconfig.json (for ts-node)

(as mentioned above, `MIKRO_ORM_CLI` has been there for long time already, so that can be used right ahead)

**Comment by iyobo** [comment]
@B4nan should those paths be relative?

**Comment by B4nan** [comment]
Can be relative to current working directory, but you should be able to pass in absolute paths as well

**Comment by B4nan** [comment]
You need to configure `migrations.path`, can be done via `MIKRO_ORM_MIGRATIONS_PATH` env var too, that way you dont need the `-p` at all.

**Comment by AzSiAz** [comment]
Working by using env var, thanks :smile:

**Comment by canhbk** [comment]
> * MIKRO_ORM_CLI_TS_CONFIG_PATH

@B4nan Could you tell me where to find all environment variables that `mikro-orm` supported? Thanks

**Comment by B4nan** [comment]
What about using the search in docs?

**Comment by canhbk** [comment]
> What about using the search in docs?
> 
> But this will be always more up to date:
> 
> https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/utils/ConfigurationLoader.ts#L173

Cool! This is what I need. Thanks!
