### ISSUE TITLE
Down Migrations

### ISSUE THREAD

**Issue by AlexAegis** [mikro-orm/mikro-orm#550]
Hi! This is more like a question: I've seen no traces of down migrations being generated, nor it being in the v4 milestones. Is this planned?

As far as I looked into the code, it's Knex that does the schema generation and assuming from this merge https://github.com/knex/knex/pull/3228 it's capable of down migrations.
But it's umzug that handles the migrations itself.

May I ask why umzug is needed if Knex can (supposedly) handle it?

**Comment by B4nan** [comment]
Well you are mixing two things, one is beeing able to run down migrations, that is supported, both in knex and umzug. Second is being able to generate down migration (the actual queries). None of those tools are capable of that. 

Umzug is used because I am planning to support mongo migrations too (although without schema diffing), so want to have one way for all drivers. 

And no, there are no plans for generating down migrations in near future, it would require quite a lot of refactoring. You need to write them manually if you want them.

**Comment by AlexAegis** [comment]
Thank you for your answer!
