### ISSUE TITLE
Possible official package to integrate with nestjs?

### ISSUE THREAD

**Issue by dpyzo0o** [mikro-orm/mikro-orm#552]
**Is your feature request related to a problem? Please describe.**
I just wonder if there is plan to have an official support for integration with nestjs since nestjs is the most popular framework in nodejs/typescript ecosystem.

**Comment by B4nan** [comment]
I believe this is more of a question for nestjs maintainers, which was already asked and they suggested to go for the community package. I would personally also like to see official package (on their end), mainly because I think it would help to propagate the package (especially if it would be part of their docs).

From usage perspective I think the current `nestjs-mikro-orm` package works fine, although the maintainer does not maintain it very much :/ Also I really dislike the fact that the root of the repository is an example project and the library is hidden in a subfolder. 

https://github.com/nestjs/nest/issues/4265

**Comment by B4nan** [comment]
I was kinda expecting that response :/ Not sure why Kamil thinks that it should fit here (there is no FW integration package) and not to their repo (that already contains many integration packages). I do read it as "we don't want to maintain more code", which is understandable (but the reasoning does not make sense to me).

**Comment by dpyzo0o** [comment]
I would just assume they don't want to add official support simply because mikro-orm is not that popular :)

**Comment by DavideCarvalho** [comment]
It’s sad because MikroORM is a really good replacement for TypeORM (since it is not that active anymore)
