### ISSUE TITLE
Spatial support (MongoDB)

### ISSUE THREAD

**Issue by murbanowicz** [mikro-orm/mikro-orm#582]
I would like to discuss Spatial support, in this case for Mongo, but we can discuss it for the whole mikro-orm.

I have started working on basic spatial stuff with mikro-orm in my project and I found some stuff missing:

- Types: solved by creating one of them: Point
- Operators: mikro-orm at the moment is missing operators like `$near fortunately the interface is open so it does not require any `ts-ignore` stuff. Can be for sure improved.
Docs: https://docs.mongodb.com/manual/geospatial-queries/#geospatial-query-operators
- Spatial index. Needs to be added with some custom approach (waiting for answer from @B4nan on slack). Could be improved by ready to use `@2DSphereIndex` 

I was thinking about something like `@mikroorm/spatial` where we could create dedicated types and indexes for all platforms. I am happy to help with that. 

Not sure about query operators in case of Mongo (add it to base types or make it somehow extensible?), the same about maybe extending the repository for SQL platforms so end users would not have to write SQL on their own or we could create some helpers, like SQL generators working with MikroORM, similar to what e.g. `npgsql` do with EF:
`var nearbyCities = context.Cities.Where(c => c.Location.Distance(somePoint) < 100);`

**Comment by B4nan** [comment]
Improved mongo index support is already in `dev` branch, you will be able to set any kind of index in v4: https://github.com/mikro-orm/mikro-orm/commit/12b3f52eccec9c062e27719af44d1868557afd90

If you are imagining something like `@mikro-orm/spatial`, then please build that first as a separate package. I don't really want to maintain more code that I don't fully understand or use, that is my biggest concern. In general it sounds like a good addition, there are others doing something alike in the SQL (postgres to be precise). If I were to introduce new package, I want it to be rather complete, not just "few types I needed", but a whole set of what is possible (and therefore, what anyone can need). So I think it would be first better to start that separately and let that evolve before we consider merging. If there will be some roadblock in the ORM core, I will be happy to introduce more extension points. 

As said, I can imagine some custom types being merged into the mongo package if they are mongo only.

Regarding operators, I am not sure what is missing - `$near` and other spatial operators should be supported out of box by mongo itself, right? Or you mean just to improve the typings? It's a bit tricky because of the SQL drivers and shared interfaces (I can already see someone creating issue about `$near` operator not working with some SQL driver). We could definitely introduce custom mongo flavoured `FilterQuery` that would be exported from `@mikro-orm/mongodb` package. 

For SQL operators, I could imagine a way to extend the current set, but it could be quite tricky to support strict typings of that. But in general, one can already use custom SQL fragments even via entity manager API, so its not that big deal if we don't do it at all:

```typescript
// pseudocode, just to show how an SQL fragment can be used
em.find(User, { 'city near (?, ?)': [lat, lng] });
```

**Comment by B4nan** [comment]
I will close this one due to inactivity. As said above, I believe the right way for something more "robust" is a separate project (I am currently not interested in building it on my own). Will be happy to add more extension points if needed. Also as said, I am open for merging additional custom types, ideally driver independent.
