### ISSUE TITLE
problem with getting entity that persisted

### ISSUE THREAD

**Issue by seunggu** [mikro-orm/mikro-orm#595]
**Describe the bug**
I have made project with domain event in DDD.
After i persist entity, i want get persisted entity in another service.
but it didn`t.

It looks after persisting, UnitOfWork only save entity in persist stack.
when i try merge this entity and flush, it didn`t flushed to database.

I want persisted entity is saved in identity map, but not originalEntityData.
Is there another way?

**Expected behavior**
After i persist entity, i want get persisted entity in another service.

**Versions**

| Dependency | Version |
| - | - |
| node | 12.14.0 |
| typescript | 3.9.3 |
| mikro-orm | 3.6.14 |
| mysql2 | 2.1.0 |

**Comment by B4nan** [comment]
Not sure I follow. You can't expect `persist` call to do anything with identity map, as you can persist entity without PK, but to have it merged (aka part of identity map), you need that PK first (aka you need to flush).

**Comment by seunggu** [comment]
@B4nan 

um,, I saved entity that have uuid based id.
should i flush entity first in this case?

**Comment by B4nan** [comment]
It does not really matter if you use uuid PK or auto increment one, entities that are in the identity map will result in update queries. Only managed entities are there. That is how the distinction whether to use insert or update query is being made.

So yes, you need to flush if you want to have (new) entity in the identity map. Or pass the entity yourself in your code to the service instead off trying to retrieve it from identity map.

**Comment by seunggu** [comment]
@B4nan 

Um, I like implicitly transaction in mikro-orm.
Orignally transaction also manage saved entity.
How about entity manager find entity in persist stack too?

**Comment by B4nan** [comment]
I don't wanna do that, it would bring a lot of inconsistencies to how the internals work. `em.find()` returns only managed entities. What you suggest would work only for uuid like PKs to start with (and I don't want to have differences in how internals work just because of that), and more importantly it would result in unpredictable things, as you could get not-managed entities from `em.find()`, and those would behave differently from the managed ones (you can make updates to managed entities and call flush, here it would not work).

You are talking about DDD, but the clear way here is to pass the entity instance thru your code, instead of counting on internals of the ORM. 

What I can offer is to expose a getter for the `UoW.persistStack` so you can do this yourself (keep in mind we are in javascript, you can already access it, with help of `@ts-ignore` comment).

**Comment by seunggu** [comment]
@B4nan 

Ok, Thank you for your reply!
