### ISSUE TITLE
Refer to column in update queries

### ISSUE THREAD

**Issue by mikicho** [mikro-orm/mikro-orm#598]
**Is your feature request related to a problem? Please describe.**
I want to update a column base on its value:
```
update t set points = points + 1 where id = '321";
```

**Describe the solution you'd like**
Maybe something like Sequelize literals?
https://github.com/sequelize/sequelize/issues/7268#issuecomment-280904532

**Describe alternatives you've considered**
1. Use knex directly.
2. write a raw query
3. find + update

**Additional context**
N/A

**Comment by B4nan** [comment]
And you would like to do this via query builder, right? 

I can imagine something like this:

```typescript
const qb = orm.em.createQueryBuilder(Book2);
qb.update({ price: qb.raw('price + 1') }).where({ uuid: '123' });

// update `book2` set `price` = price + 1 where `uuid_pk` = ?
```

**Comment by mikicho** [comment]
Thanks!
1. But we can't do this in MikroORM because now the entity manager doesn't know about this change, isn't it?
2. I imagine something like this:
```
orm.em.getRepository(Entity).update({ id: 'dsa' }, { price: 'price + 1' });
```

**Comment by B4nan** [comment]
Don't expect this to work with entity manager (or identity map) - if you want that, you need to load the entity first.

We are talking about update query without the need to load the entity.

**Comment by mikicho** [comment]
> We are talking about update query without the need to load the entity.

So from identity map POV it's ok to not "update" it right? it won't cause a "hole" in the identity map?

**Comment by B4nan** [comment]
I am not going to add `em.update()`, MikroORM is based on change set tracking, this would just cause a lot of confusion. You can design such method yourself in a custom repository, if you need it.

And I still don't understand why you are concerned with identity map. You wanted a way to update entity without loading it, that means it is not in the identity map. Even if it would be present there, it does not really matter if you do updates directly to the database - it won't have any side effects. Of course if the entity would be already loaded, it would still have the old value, but there is no way to solve this easily, not without reloading the entity - maybe in postgres via `returning` statement, but nothing that would work across all drivers, therefore nothing I want to have implemented in the ORM.

If you want the MikroORM way, load the entity first, use version field to make sure there are no concurrent updates and make the increment in your code rather than in SQL. If you want increment on db level, without loading the entity first, we can have the API with `qb.raw()` for sure, that's easy to add (will do it anyway).

**Comment by mikicho** [comment]
Thanks!!

> load the entity first, use version field to make sure there are no concurrent updates

What about `select for update`? is it possible in MikroORM?

**Comment by B4nan** [comment]
Yes, `LockMode.PESSIMISTIC_WRITE` will result in `select for update` query.

https://mikro-orm.io/docs/transactions/#pessimistic-locking

**Comment by mikicho** [comment]
Another thing that came into my mind.. what about update it in raw query for example AND delete it from the identity map manually? is it possible? do you recommend consumers to "mass with" the identity map?

**Comment by B4nan** [comment]
You can remove entity from identity map via `UoW.unsetIdentity()`, but to do that, you first need to have the entity. So you would first need to try `UoW.getById()` to see if its there.

By removing something from identity map you could potentially loose some updates that were already made on that entity (if you remove it from there, you can't expect any updates for it, flush will simply ignore it).

**Comment by mikicho** [comment]
Ok, thanks!
