### ISSUE TITLE
JSONB columns are always updated

### ISSUE THREAD

**Issue by whitelake-city** [mikro-orm/mikro-orm#6270]
### Describe the bug

GIVEN a postgres db with a table `user`
AND the `user` has a column with type `jsonb` called `address` and a column `name` with type `varchar`
WHEN loading the `user` 
AND applying a change to the field `name` (not address!)
THEN the update statement will contain updates for both the `name` and `address` column

EXPECTED the address column is not updated.

### Reproduction

I am absolutely sure that the description is sufficient.

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.4

### Node.js version

20.18.0

### Operating system

Linux

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Discord](https://discord.gg/w8bjxFHS7X).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
> I am absolutely sure that the description is sufficient.

No, it is not sufficient, it's actually the very opposite since you haven't shared any details. We have many tests for this (the main one being https://github.com/mikro-orm/mikro-orm/blob/master/tests/features/custom-types/json-properties.test.ts but also dozens of other regression tests touching this). I need to see a [complete reproduction](https://github.com/mikro-orm/reproduction), let's reopen with one.

**Comment by whitelake-city** [comment]
@B4nan I am sorry. I added a working reproduction PR.
