### ISSUE TITLE
JSONB columns are always updated

### ISSUE THREAD

**Issue by whitelake-city** [mikro-orm/mikro-orm#6273]
### Describe the bug

GIVEN a table `user`
AND the `user` has a column with type `jsonb` called `address` and a column `name` with type `varchar`
WHEN loading the `user` 
AND applying a change to the field `address` with the same properties but in different order. e.g. from {zip:null,street:null} to {street:null, zip:null}
AND applying a change to the field `name` from `Bob` to `Alice`
THEN the update statement will contain updates for both the `name` and `address` column

EXPECTED the address column is not updated.

### Reproduction

https://github.com/whitelake-city/mikroorm-reproduction/pull/1

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.4

### Node.js version

20.18.0

### Operating system

Linux

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Discord](https://discord.gg/w8bjxFHS7X).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
In the future we could probably resolve this if we start comparing runtime values instead of the database values, since that is the main problem here - we get a JSON string and we compare that to another based on your values. I already tried to make this happen some time ago, but it turned out to be really hard, I spent a good week of work on that before I surrendered. So I can't promise it will ever happen, it would be quite a significant change to internals that would need to be part of a major version and would potentially change things for many users.
