### ISSUE TITLE
Ordering on multiple columns

### ISSUE THREAD

**Issue by njeirath** [mikro-orm/mikro-orm#643]
I'm curious if it's possible to order on multiple columns using a method like `findAndCount`.  I see the type for `orderBy` is `QueryOrderMap` which makes sense for a single column but if trying to sort on two columns I'd imagine the column order could not be enforced since a map won't necessarily maintain ordering.  

For example, say I had a table:
Category | Price
------------ | -------------
A | 1.23
B | 8.23
A | 2.21
B | 1.93

And I want to sort first on category then on price (the equivalent of `ORDER BY table.category, table.price`). Using a map as currently implemented seems like this is not possible unless there is another way to achieve this that I'm missing. I realize I can grab the knex connection and craft the query myself if necessary but wanted to see if there was a way to achieve this without doing that.

**Comment by B4nan** [comment]
> ...since a map won't necessarily maintain ordering.

Actually that is no longer true, just define multiple keys, they will maintain the order. And I am quite sure that even in earlier days, the possible issue with the order of object keys not being stable would be visible only with really large objects (which is far away from this ordering use case)... 

https://www.stefanjudis.com/today-i-learned/property-order-is-predictable-in-javascript-objects-since-es2015/

**Comment by njeirath** [comment]
Ah I hadn't realized this.  Thanks for the link.
