### ISSUE TITLE
Logger `chalk.grey` color is almost invisible on dark background

### ISSUE THREAD

**Issue by MunifTanjim** [mikro-orm/mikro-orm#654]
**Describe the bug**

`chalk.grey` color (`blackBright (alias: gray, grey)`) is not visible / almost invisble on dark color scemes.

**To Reproduce**
1. turn on `debug` in config

**Expected behavior**

Should use a more visible color.

**Additional context**

`chalk.dim` is a good choice.

**`chalk.grey` (current)**:

 
![Screenshot from 2020-07-12 19-35-21](https://user-images.githubusercontent.com/8050659/87247743-6ef62980-c477-11ea-93a6-e4ccfe966f90.png)

![Screenshot from 2020-07-12 19-36-29](https://user-images.githubusercontent.com/8050659/87247749-74537400-c477-11ea-98c3-e073de48cb99.png)

**`chalk.dim` (proposed)**:

![Screenshot from 2020-07-12 19-35-44](https://user-images.githubusercontent.com/8050659/87247745-70bfed00-c477-11ea-8fb7-59606753a346.png)

![Screenshot from 2020-07-12 19-36-04](https://user-images.githubusercontent.com/8050659/87247747-7289b080-c477-11ea-914a-718052a3517a.png)

**Comment by B4nan** [comment]
This looks more like you using some (badly defined) custom color scheme, as you are literally the only one reporting such issue. This is how it looks on my end:

![image](https://user-images.githubusercontent.com/615580/87276181-17d86f00-c4e0-11ea-85a4-feaa8f6fa17d.png)
(webstorm's terminal)

![image](https://user-images.githubusercontent.com/615580/87276234-350d3d80-c4e0-11ea-9f05-4090dce2e9ea.png)
(iterm)

The color is supposed to be grey, and the text should be white in general (with highlights), your color scheme uses yellow or green instead of white? why would anyone do that, those colors are used for highlighting, using it for the base text color does not make sense to me... 

Tried the `dim` version, looks fine in iterm, but has no difference in webstorm (the color is white instead of grey)...

**Comment by MunifTanjim** [comment]
> custom color scheme

Not really. I'm using Gruvbox Color Scheme with Alacritty. :thinking: It's a pretty popular color scheme.

Gruvbox Color Scheme: https://github.com/morhetz/gruvbox

Alacritty config: https://github.com/MunifTanjim/.dotfiles/blob/77e39350814eb5bedb9a6a5dc1c0ee64fa644c89/private_dot_config/alacritty/alacritty.yml#L172-L211

I have TrueColor support enabled in my terminal.

**Comment by B4nan** [comment]
This looks like you are overriding the values of the theme? 

![image](https://user-images.githubusercontent.com/615580/87295319-4c125680-c505-11ea-8858-2db678480f6d.png)

**Comment by MunifTanjim** [comment]
> This looks like you are overriding the values of the theme?

Those values come directly from the Gruvbox color scheme:

![image](https://user-images.githubusercontent.com/8050659/87295748-7a089280-c527-11ea-82e1-29c9012f414b.png)

That is how color scheme is defined for [Alacritty](https://github.com/alacritty/alacritty)

**Comment by MunifTanjim** [comment]
Okay, I got the issue. I'm using `bright black` as my background color. And `chalk.grey` is actually `chalk.blackBright`. So they are the same.

But using `bright black` as the background color is quite common for this color scheme.

**Comment by B4nan** [comment]
I will close this one, for me this looks really just like a misconfiguration. Will reconsider if there will be more people having this issue, but as you are the first one 🤷
