### ISSUE TITLE
Does not check for cached entities in identity map for queries on multiple ids

### ISSUE THREAD

**Issue by ayushmaanbhav** [mikro-orm/mikro-orm#664]
**Describe the bug**
Does not check for cached entities in identity map for queries on multiple ids like:
- find({id: {$in: [...]}})
- find([...])

**Expected behavior**
Should check the identity map for cached entities from the given ids and get them when possible.

**Version Info**
node: 12.8.2
typescript: 3.9.6
mikro-orm: 3.6.14
your-driver: mongodb

**Comment by B4nan** [comment]
This is correct behaviour, only queries for the PK itself will use identity map (e.g. `findOne(Book, 123)`). Identity map is not a caching mechanism, it is there to maintain identity of the entity - and in this sense it is working fine, you will always get the right entities even with your example (but it will make the DB call).

**Comment by ayushmaanbhav** [comment]
I dont understand then, why does it not call db when using findOne?

Also one more thing, how do i query on a multikey mongo index? (index over an array)

**Comment by B4nan** [comment]
`findOne` does the identity map lookup only when you provide plain PK, so `findOne(Book, 1)` (or `findOne(Book, { id: 1 })`). There is no "query parsing/analysis", it's simple as that - you provide anything more complex than just a PK and it will make the db call as the db is where the conditions are applied. So `findOne(Book, { id: { $in: [1, 2, 3] } })` will make the db call too. The UoW lookup is then made after we know the PK, so you still get the instance from UoW if it is already loaded. 

> Also one more thing, how do i query on a multikey mongo index? (index over an array)

Not sure what you mean. In mongo you can do basically the very same query as you would do on the native collection, there might be some TS issues due to strict `FilterQuery` type, but in the end the condition is passed down to the mongo collection API, so you can just cast as `any` to get around those (if you for example want to use some mongo specific operator like `$exists`).

**Comment by ayushmaanbhav** [comment]
One issue was with my understanding of `identity-map`, which is clarified now.
One more issue is that it doesn't support query on `multi-key` indexes and `nested.path` indexes (also doesn't support ensuring `nested.path` indexes). Casting it to `any` works for now and I am creating `nested.path` indexes by getting the underlying connection.

**Comment by ayushmaanbhav** [comment]
Thanks for the info and your time, if you have any tips for handling `nested.path` indexes please suggest.

**Comment by B4nan** [comment]
Not sure I follow? You mean PKs when you say indexes? I don't see how this could be about indexes. Identity map lookups do support composite keys, if that is what you mean - you need to pass ordered tuple to trigger the lookup (e.g. if `User` have two primary keys, you can do this `em.findOne(User, ['Firstname', 'Lastname'])`).

Ideally show examples of what you are talking about.

**Comment by ayushmaanbhav** [comment]
@B4nan No, this one is not about PKs. Its regarding queries on multi-key indexes. Multi-key indexes are supposed to be queried like:
{name: [...values]}

The problem is that when mikro detects an array in these type of queries, it converts then to:
{name: {$in: [...values]}}

So currently I am using underlying driver to bypass mikro's query transform magic.
