### ISSUE TITLE
[V4] "knex: Unknown configuration option 'client'" when using sqlite

### ISSUE THREAD

**Issue by CyriacBr** [mikro-orm/mikro-orm#685]
**Describe the bug**
When using sqlite, this error is thrown when mikro-orm is initializing:
```bash
 knex: Unknown configuration option 'client' value function Client_SQLite3(config) {
      Client.call(this, config);
      if (isUndefined(config.useNullAsDefault)) {
        this.logger.warn(
          'sqlite does not support inserting default values. Set the ' +
            '`useNullAsDefault` flag to hide this warning. ' +
            '(see docs http://knexjs.org/#Builder-insert).'
        );
      }
    }. Note that it is case-sensitive, check documentation for supported values.

      at Object.Knex [as default] (../../node_modules/@mikro-orm/knex/node_modules/knex/lib/knex.js:38:13)
      at SqliteConnection.createKnexClient (../../node_modules/@mikro-orm/knex/src/AbstractSqlConnection.ts:67:16)
      at SqliteConnection.connect (../../node_modules/@mikro-orm/sqlite/src/SqliteConnection.ts:12:24)
```

**Stack trace**
See above

**To Reproduce**
1. Set this config:
```ts
{
  metadataProvider: TsMorphMetadataProvider,
  entities: [BaseEntity, Author, Book, Address, WithBadEnum, BookTag],
  dbName: 'test.db',
  type: 'sqlite',
  debug: true,
  cache: {
    enabled: true,
    pretty: true,
    options: { cacheDir: process.cwd() + '/test/temp' },
  },
  highlight: true,
};
```
2. Run `const orm = await MikroORM.init(ormConfig);`

**Additional context**
[Reproduction here](https://github.com/CyriacBr/mikro-resources/tree/next/packages/fixtures), simply uncomment the mysql part in the config.

**Versions**
V4 latest versions.

**Comment by xeladejo** [comment]
Try with the latest alpha `npm install --save @mikro-orm/core@next` (or yarn equivalent) I too had some troubles with first alphas, but now all is working well (with `4.0.0-alpha.7` in my case).

**Comment by B4nan** [comment]
Yeah I was also going to mention I see you have alpha 0 there, be sure to use the latest one.

**Comment by B4nan** [comment]
Indeed, this is caused by using `alpha.0` - it was released under `latest` dist tag automatically (due to being a new package), the rest is under `next` dist tag. Specify the version manually and verify it in the lock file. 

Unfortunately there is one issue with loading TS files via ts-node in the latest alpha (`alpha.7` and `alpha.8` are affected) caused by this: https://github.com/mikro-orm/mikro-orm/commit/00e378172cfb13ca33874da8cc8ee9dd6cd79e07

To get around that now, just define the enums in your entities like this:

```typescript
@Entity()
export class WithBadEnum extends BaseEntity {
  @Enum(() => FooEnum)
  enum!: FooEnum;
}
```

Or use `4.0.0-alpha.6` (be sure to remove the `^` from the beginning to install exactly that version).

Will revert the commit and ship `alpha.9` probably tomorrow that fixes this issue.

**Comment by merceyz** [comment]
@B4nan Don't know if you saw this https://github.com/mikro-orm/mikro-orm/pull/515#issuecomment-661809465 so i'll reiterate it here, `requireFrom` is not needed on absolute paths :)

**Comment by B4nan** [comment]
Yes I did, and I already reverted it. It's weird that it is not patched via `ts-node`, but whatever, verified that the paths are really absolute, so we should be fine with plain `require` (although with that ugly eslint ignore comment - that was the reason why I did the change originally :D).
