### ISSUE TITLE
generate-entities maps JSONB columns to strings

### ISSUE THREAD

**Issue by travigd** [mikro-orm/mikro-orm#746]
**Describe the bug**
I have a column named `metadata` which is a Postgres JSONB column.
The generated code from the `generate-entities` command is:
```
  @Property({ columnType: "jsonb", nullable: true })
  metadata?: string;
```
which then barfs when I try to load a row since it expects metadata to be of type string (not an object).
**Stack trace**
```
(node:31197) UnhandledPromiseRejectionWarning: ValidationError: Trying to set Users.metadata of type 'string' to '[object Object]' of type 'object'
```

**Versions**
```
$ npx mikro-orm --version
3.6.15
```

**Comment by B4nan** [comment]
This has been already fixed in v4, tests include jsonb columns and they correctly generate `object` type (without explicit `columnType` as the default in postgres for object columns is `jsonb` in v4).

So [try upgrading](https://mikro-orm.io/docs/upgrading-v3-to-v4) (no plans to backport things).

Here the test snapshot:
https://github.com/mikro-orm/mikro-orm/blob/master/tests/__snapshots__/EntityGenerator.test.ts.snap#L163

And here the SQL dump it is based on:
https://github.com/mikro-orm/mikro-orm/blob/master/tests/postgre-schema.sql#L41
