### ISSUE TITLE
Support for read replica connections?

### ISSUE THREAD

**Issue by rex-remind101** [mikro-orm/mikro-orm#77]
Is there a way to setup read replica connections? something like https://github.com/typeorm/typeorm/blob/master/docs/multiple-connections.md#replication supported?

**Comment by B4nan** [comment]
Multiple connections are currently not supported. I am working on knex integration that will allow connection pooling, but sadly there is no support for replication in knex. It should be relatively ease to implement though. I will tag this with help wanted till I find some free time for it.

**Comment by stephenh** [comment]
@B4nan out of curiosity, we could make this work by just having two orm instances, i.e.:

```
const writerOrm = await MikroORM.init({
  entitiesDirs: ['./dist/entities'], // path to your JS entities (dist), relative to `baseDir`
  dbName: 'my-db-name',
  clientUrl: 'writer-url',
  autoFlush: false, // read more here: https://b4nan.github.io/mikro-orm/unit-of-work/
});
```

```
const readerOrm = await MikroORM.init({
  entitiesDirs: ['./dist/entities'], // path to your JS entities (dist), relative to `baseDir`
  dbName: 'my-db-name',
  clientUrl: 'reader-url',
  autoFlush: false, // read more here: https://b4nan.github.io/mikro-orm/unit-of-work/
});
```

And then we'd use the `readerOrm`/`writerOrm` as appropriate? Or does `MikroORM.init` have some global state that means there can be only one of them?

**Comment by B4nan** [comment]
There is global state where all entity metadata are stored (because decorators can be executed before the ORM init happens so we need global state to store those metadata), so if you would use same entities for both of them, that shouldn't be a problem. 

Another sort of global state is hidden in `RequestContext` - once you register it, ORM will internally ask for EM from the context to provide clean identity map for each request. But you could work this out manually without using `RequestContext` - it's there to ease integration with DI tools, but you can always fork it manually and pass the fork to your request handler. 

So generally it should be doable if you share the same entities and you handle the request context manually via something like `app.use((req, res, next) => req.em = orm.em.fork());` and using the `req.em` variable in the request handler directly.

**Comment by B4nan** [comment]
Thinking about this a bit more now, and the approach with multiple orm instances is probably bad idea. Another problem that would be hard to solve is that every entity has current entity manager instance injected during discovery process. That instance is used for example when calling entity.init(). 

I started working on some improvements in metadata discovery in #91, so each Orm instance will have its own metadata storage that will be used internally. 

To fix the problem with em instance in entities, I think I could just replace it when merging the entity, so all managed entities will have correct reference to its own EM. 

After that it should be possible to go this way, but I will try to add support for read connections in v3 natively so one does not have to hack things like this.

**Comment by B4nan** [comment]
Available for testing via `next` tag (`3.0.0-alpha.3`).

**Comment by B4nan** [comment]
Closing as resolved.

**Comment by stephenh** [comment]
Nice! I scanned the diff and it looks good. I recently switched projects so don't need read replicas personally anymore (but am still planning on setting up mikro-orm on the new project soon-ish). cc @hamiltop as an FYI.
