### ISSUE TITLE
Error: cannot use 'in' operator to search for 'schema' 4.0.0-alpha-0

### ISSUE THREAD

**Issue by Quadriphobs1** [mikro-orm/mikro-orm#796]
**Describe the bug**
This is my first time setup of MikroOrm with nestJs and it looks like the schema isn't working with the error

**Stack trace**
```
TypeError: Cannot use 'in' operator to search for 'schema' in ./dist/modules/registration/entities/registration.entity.js
    at MetadataDiscovery.prepare 
    at MetadataDiscovery.discoverEntity
...
```

**Expected behavior**
Tried same thing with the example `https://github.com/mikro-orm/nestjs-realworld-example-app`
After cloning the repo `yarn upgrade-interactive --latest` and run `schema:create -r`

**Versions**

| Dependency | Version |
| - | - |
| node | 14 |
| typescript | 4.0.2 |
"@mikro-orm/core": "^4.0.0-alpha.0",
    "@mikro-orm/migrations": "^4.0.0-alpha.0",
    "@mikro-orm/nestjs": "^4.0.0-alpha.3",
    "@mikro-orm/postgresql": "^4.0.0-alpha.0",
    "@mikro-orm/reflection": "^4.0.0-alpha.0",

**Comment by B4nan** [comment]
Upgrade to latest version, currently being 4.0.0-rc.4

**Comment by Quadriphobs1** [comment]
@B4nan  Upgrading brings up another error  `TypeError: Cannot read property 'name' of undefined`

```
 "@mikro-orm/core": "^4.0.0-rc.4",
    "@mikro-orm/migrations": "^4.0.0-rc.4",
    "@mikro-orm/nestjs": "^4.0.0-rc.4",
    "@mikro-orm/postgresql": "^4.0.0-rc.4",
    "@mikro-orm/reflection": "^4.0.0-rc.4",

```

**Comment by B4nan** [comment]
And the full stack trace looks like what? Ideally prepare (minimal) reproduction repo, will be happy to take a look, but it's hard to guess without seeing the whole setup.

Also note that `@mikro-orm/nestjs` should stay on `^4.0.0-alpha.3` (that comes from different repository, only the internal packages have aligned versions. This whole "mess" is caused by the introduction of new packages, as the very first version (`alpha.0`) was automatically released as `latest`, rest is released (correctly) under `next`.
