### ISSUE TITLE
Support virtual property getters

### ISSUE THREAD

**Issue by B4nan** [mikro-orm/mikro-orm#82]
If you can have virtual property like `fullName`, that will be computed based on `firstName` and `lastName`:

```typescript
@Property({ name: 'fullName' })
getFullName() {
  return this.firstName + this.lastName;
}
```

When defined like this, the property `fullName` will be available as part of serialized response (output of `entity.toJSON()`).

**Comment by NickBolles** [comment]
would getters be supported?
```typescript
@Property()
get fullname() {
  return this.firstName + this.lastName;
}
```

**Comment by B4nan** [comment]
I would love to support that, hopefully there wont be any problem with it but never tried decorators on top of getter.

**Comment by B4nan** [comment]
Just FYI getters are also supported.

**Comment by NickBolles** [comment]
@B4nan I just had another thought, what about setters? It can be helpful for doing validation/updating values. for example keeping an email address lowercase. Also, side-note onUpdate doesn't seem to have access to the current value. Both would be interesting to have support for, although I think a setter is more versatile because it's reflected in memory too.

```typescript
  private _address!: string;
  @Property({
    type: String
  })
  get address(): string {
    return this._address;
  }
  set address(val: string) {
    this._address = val && val.length ? val.toLocaleLowerCase() : val;
  }
```

**Comment by B4nan** [comment]
This should be already supported in v3, will add a test case to be sure...

About update hooks, feel free to create new issue if you see something not working properly.

**Comment by B4nan** [comment]
Closing as resolved. Available for testing via `next` tag.
