### ISSUE TITLE
Any recommendation for a good fixtures library that works well with Mikro ORM?

### ISSUE THREAD

**Issue by maphe** [mikro-orm/mikro-orm#862]
I'm looking for a fixture library that works well with Mikro ORM entities. 

I was wondering if you've had to use some factory/fixtures on a project with Mikro ORM and if you had any recommendations.

I've played around with the following 2 but did not get great results:
- https://github.com/willryan/factory.ts
- https://github.com/CyriacBr/class-fixtures-factory (and its Mikro ORM wrapper: https://www.npmjs.com/package/@mikro-resources/fixtures)

The error messages were not very specific in either case but it seems like both libs were not doing great with Collections, among other things...

**Comment by B4nan** [comment]
Never used things like those (literally never, not just with MikroORM :]). Maybe better to open issue in the [`@mikro-resources`](https://github.com/CyriacBr/mikro-resources) if that don't work for you, the author is on our slack channel as well. I believe it's the only library specifically for MikroORM. 

Looking at the [changelog](https://github.com/CyriacBr/mikro-resources/blob/develop/CHANGELOG.md), there were no releases in last 6 months, so it might be not compatible with v4.

If collections are the problem, you could use any tool to generate DTOs, where you have arrays instead of collections, and convert those to entities via `em.create()`.

**Comment by whocaresk** [comment]
@maphe, Hello, i've used `typeorm-fixtures-cli` (https://github.com/RobinCK/typeorm-fixtures) with some little tweaks. No issues so far. Here is my setup: https://gist.github.com/whocaresk/6d36fc7be8cc7976b38cc2ba74746c0a   
Version: `{"typeorm-fixtures-cli": "1.6.0"}`
