### ISSUE TITLE
Allow defining multiple entities in a single file in folder based discovery

### ISSUE THREAD

**Issue by Langstra** [mikro-orm/mikro-orm#922]
**Describe the bug**
While running schema:create or schema:update I get an error that it cannot find the Client entity and it should be provided in the entities array. The only problem with this is that I actually have provided it in the entities array.

I get this error on a class `Client` that extends `Oidc`. Client has a OneToMany relation with ClientCredentials and ClientCredentials (a normal entity) has a ManyToOne relations to Client. This is the relation on which the error occurs.

**Stack trace**
```
MetadataError: Entity 'Client' was not discovered, please make sure to provide it in 'entities' array when initializing the ORM (used in ClientCredentials.client)
    at Function.fromUnknownEntity (/path/to/project/node_modules/@mikro-orm/cli/node_modules/@mikro-orm/core/errors.js:121:16)
    at /path/to/project/node_modules/@mikro-orm/cli/node_modules/@mikro-orm/core/metadata/MetadataValidator.js:53:46
    at Array.forEach (<anonymous>)
    at /path/to/project/node_modules/@mikro-orm/cli/node_modules/@mikro-orm/core/metadata/MetadataValidator.js:51:67
    at Array.forEach (<anonymous>)
    at MetadataValidator.validateDiscovered (/path/to/project/node_modules/@mikro-orm/cli/node_modules/@mikro-orm/core/metadata/MetadataValidator.js:51:20)
    at MetadataDiscovery.findEntities (/path/to/project/node_modules/@mikro-orm/cli/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:75:24)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at MetadataDiscovery.discover (/path/to/project/node_modules/@mikro-orm/cli/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:34:9)
    at Function.init (/path/to/project/node_modules/@mikro-orm/cli/node_modules/@mikro-orm/core/MikroORM.js:40:24)
    at Function.handleSchemaCommand (/path/to/project/node_modules/@mikro-orm/cli/commands/SchemaCommandFactory.js:65:21) {
  entity: undefined
}
```

**To Reproduce**
Oidc class:
```
@Entity({
  tableName: 'oidc',
  discriminatorColumn: 'kind',
  discriminatorValue: 'Oidc',
})
export class Oidc {
  @PrimaryKey()
  id: string;

  @Property({ columnType: 'varchar' })
  kind: Kind;

  @Property({ type: 'json' })
  payload: AdapterPayload;

  @Property()
  expiresAt: Date;
}
```

Client class:
```
@Entity({
  discriminatorValue: Kind.Client,
})
export class Client extends Oidc {
  @OneToMany({
    entity: () => ClientCredentials,
    mappedBy: 'client',
    orphanRemoval: true,
  })
  clientCredentials = new Collection<ClientCredentials>(this);
}
```

ClientCredentials class:
```
@Entity({ tableName: 'client_credentials' })
export class ClientCredentials {
  @ManyToOne({ primary: true, hidden: true })
  client!: IdentifiedReference<Client>;

  @ManyToOne({ primary: true, hidden: true })
  organization!: IdentifiedReference<Organization>;

  [PrimaryKeyType]: [number, number];

  @Property({ nullable: true })
  deletedAt?: Date;
}
```

**Expected behavior**
Should create/update the schema.

**Versions**

| Dependency | Version |
| - | - |
| node | 14.4.0 |
| typescript | 3.9.0 |
| mikro-orm | 4.1.1 |
| mysql | 4.1.1 |
| mikro-orm/nest | 4.2.0 |

**Comment by B4nan** [comment]
Please create full reproduction that I can try, there are lots of details missing here (e.g. the actual configuration).

**Comment by milo526** [comment]
We created a repository with one very simple step to reproduce the issue, please see [this repository](https://github.com/RiskChallenger/nest-mikro-orm-sti).

As outlined in the readme over there, run `yarn && yarn mikro-orm schema:update -d`

Thank you for looking into this!

**Comment by B4nan** [comment]
Folder based discovery do not support multiple entities in single file, that's the problem here most probably.

**Comment by Langstra** [comment]
I changed the configuration to this:
```
import { Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { MikroOrmModule } from '@mikro-orm/nestjs';
import { Client, Oidc } from './entities/Oidc.entity';
import { ClientCredentials } from './entities/ClientCredentials.entity';

@Module({
  imports: [
    MikroOrmModule.forRoot({
      entities: [Oidc, Client, ClientCredentials],
      dbName: 'my-db-name.sqlite3',
      type: 'sqlite',
    }),
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

However, I am still getting the same error. What I am trying right now is not folder based discovery anymore, right?

So then I moved every entity to its own file, after that it worked fine. Should be mark this as a bug and have a fix for it? At least the error message should be clearer and explain better what the problem is.

**Comment by B4nan** [comment]
The error message is fine, it says the entity was not discovered, and that is exactly what happened (and there is no way to know why). It's quite weird that it is the same with the explicit approach (`entities: [Oidc, Client, ClientCredentials]`), maybe that is (another) bit different issue, will look into that too (is the logger really telling you those 3 entities are processed? folder discover has different logs that this). 

I'd like to support this (having multiple entities in single file), the issue is with base entities that currently do not have any class decorator - and having such is required to be able to allow having multiple entities. Requiring it is a breaking change, will take a look at what's possible, I hope we could still preserve current behaviour, while allowing to import multiple entities (not base entities tho) from single file. We can add a special decorator for abstract entities too, keeping it optional for know, if one want's to have base entity in a file where multiple entities are, then using it will be mandatory.

The main problem is, that currently with folder based discovery, one file always results in (at most) one discovered entity. And it will be always the one that corresponds to the file name, where it is defined. In your example repo, you have `Oidc.entity.ts`, so only `Oidc` entity is discovered from that file, rest will be always ignored.

**Comment by B4nan** [comment]
Looking into that issue with explicit approach, and indeed that is a user error - you have 2 configs in your app, one for CLI and one for nest, and you changed only the nest config while testing via CLI - so the error was the same, because nothing changed in the config. 

https://github.com/RiskChallenger/nest-mikro-orm-sti/blob/main/src/app.module.ts
https://github.com/RiskChallenger/nest-mikro-orm-sti/blob/main/mikro-orm.config.ts

You should prefer to define the CLI config and import that in the `AppModule` so you do not fall into this trap :]

Btw I managed to get around that limitations of multiple entities in single file, so in v4.2 this will work fine without changes.

**Comment by Langstra** [comment]
Thanks for fixing
