### ISSUE TITLE
Attempt to create unique index twice during tests in SQLite

### ISSUE THREAD

**Issue by ujwal-setlur** [mikro-orm/mikro-orm#939]
per discussion on slack:

https://github.com/ujwal-setlur/mikro-orm-bug-reproduction

1. npm install
2. npm run test

**Comment by B4nan** [comment]
Ok I see. You are initialing the ORM for each request, which is messing up with the metadata. You can't call `MikroORM.init()` multiple times, that needs to happen only once.

**Comment by B4nan** [comment]
I was looking into this in a bit more detail, and your problem is that you call `jest.resetModules();` which probably resets require cache, so all decorators are executed again when executing second test case. The entity level index/unique decorators basically add to an array of indexes, if you execute it twice, you will get duplicates in the metadata. Removing `jest.resetModules();` fixes the issue. 

Another way would be to reset the global storage when you call `jest.resetModules();`:

```ts
  const a = Utils.getGlobalStorage('metadata');
  Object.keys(a).forEach(k => delete a[k]);
  const b = Utils.getGlobalStorage('subscribers');
  Object.keys(b).forEach(k => delete b[k]);
```

We could add a shortcut to do this for sure.

**Comment by ujwal-setlur** [comment]
That worked! Your explanation makes sense. Thanks!
